/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module assembler;

import std.stdio;
import std.string;
import std.algorithm;
import std.traits;
import std.array;
import std.regex;
import mips;
import ir;
import utils;

Assembly parseAsm(string code, string labelPrefix = "", size_t instrIndexStart = 0)
{
    AsmInstr[] output;
    AsmDataEntry[] dataEntries;
    
    size_t[string] sections; // label -> instruction index
    size_t[string] dataLabels;
    size_t instrIndex = instrIndexStart;
    
    string textSection = labelPrefix ~ ".text";
    string dataSection = labelPrefix ~ ".data";
    string currentSection = textSection;
    string currentDataLabel = "";

    foreach(i, line; code.splitLines)
    {
        line = line.strip;
        if (line.empty || line.startsWith(";")) continue;

        if (line.endsWith(":"))
        {
            auto label = labelPrefix ~ line[0..$-1].strip;
            if (currentSection != dataSection)
                throw new Exception("Illegal label \"" ~ label ~ "\" in section \"" ~ currentSection ~ "\"");
            dataLabels[label] = instrIndex;
            currentDataLabel = label;
            continue;
        }
        if (line.startsWith("."))
        {
            auto label = labelPrefix ~ line[0..$].strip;
            sections[label] = instrIndex;
            currentSection = label;
            currentDataLabel = "";
            continue;
        }
        if (line.startsWith("\""))
        {
            auto str = line[1..$-1].strip;
            if (currentDataLabel.length)
                dataEntries ~= AsmDataEntry(currentDataLabel, parseEscapes(str));
            else
                throw new Exception("Unlabeled ASCII data \"" ~ str ~ "\"");
            continue;
        }
        
        if (currentSection != textSection)
            throw new Exception("Instruction code should be in \".text\" section, current section is \"" ~ currentSection ~ "\"");

        string[] parts = line.splitter(regex(r"[\s,()]+")).filter!(s => !s.empty).array;

        if (parts.length == 0) continue;

        string op = parts[0].toLower;
        string[] args = parts[1..$];

        if (op == "nop")
            output ~= AsmInstr(Op.NOP);
        
        else if (op == "add" && args.length == 3)
            output ~= AsmInstr(Op.ADD, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "addu" && args.length == 3)
            output ~= AsmInstr(Op.ADDU, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "addi" && args.length == 3)
            output ~= AsmInstr(Op.ADDI, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "addiu" && args.length == 3)
            output ~= AsmInstr(Op.ADDIU, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "sub" && args.length == 3)
            output ~= AsmInstr(Op.SUB, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "subu" && args.length == 3)
            output ~= AsmInstr(Op.SUBU, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "mult" && args.length == 2)
            output ~= AsmInstr(Op.MULT, args[0].makeReg, args[1].makeReg, makeNone, i);
        else if (op == "multu" && args.length == 2)
            output ~= AsmInstr(Op.MULTU, args[0].makeReg, args[1].makeReg, makeNone, i);
        else if (op == "div" && args.length == 2)
            output ~= AsmInstr(Op.DIV, args[0].makeReg, args[1].makeReg, makeNone, i);
        else if (op == "divu" && args.length == 2)
            output ~= AsmInstr(Op.DIVU, args[0].makeReg, args[1].makeReg, makeNone, i);
        else if (op == "mflo" && args.length == 1)
            output ~= AsmInstr(Op.MFLO, args[0].makeReg, makeNone, makeNone, i);
        else if (op == "mfhi" && args.length == 1)
            output ~= AsmInstr(Op.MFHI, args[0].makeReg, makeNone, makeNone, i);
        else if (op == "mtlo" && args.length == 1)
            output ~= AsmInstr(Op.MTLO, args[0].makeReg, makeNone, makeNone, i);
        else if (op == "mthi" && args.length == 1)
            output ~= AsmInstr(Op.MTHI, args[0].makeReg, makeNone, makeNone, i);
        
        else if (op == "j" && args.length == 1)
        {
            AsmOperand imm;
            if (args[0].startsWith("."))
                imm = makeLabel(labelPrefix ~ args[0]);
            else
                imm = makeImm(args[0]);
            output ~= AsmInstr(Op.J, imm, makeNone, makeNone, i);
        }
        else if (op == "jr" && args.length == 1)
            output ~= AsmInstr(Op.JR, args[0].makeReg, makeNone, makeNone, i);
        else if (op == "jal" && args.length == 1)
        {
            AsmOperand imm;
            if (args[0].startsWith("."))
                imm = makeLabel(labelPrefix ~ args[0]);
            else
                imm = makeImm(args[0]);
            output ~= AsmInstr(Op.JAL, imm, makeNone, makeNone, i);
        }
        else if (op == "jalr" && args.length >= 1)
        {
            if (args.length == 1)
                output ~= AsmInstr(Op.JALR, makeReg(RA), args[0].makeReg, makeNone, i);
            else
                output ~= AsmInstr(Op.JALR, args[0].makeReg, args[1].makeReg, makeNone, i);
        }
        
        else if (op == "li" && args.length == 2)
        {
            AsmOperand imm;
            if (args[1].startsWith("."))
                imm = makeLabel(labelPrefix ~ args[1]);
            else
                imm = makeImm(args[1]);
            output ~= AsmInstr(Op.LI, args[0].makeReg, imm, makeNone, i);
        }
        else if (op == "lui" && args.length == 2)
            output ~= AsmInstr(Op.LUI, args[0].makeReg, args[1].makeImm, makeNone, i);
        else if (op == "move" && args.length == 2)
            output ~= AsmInstr(Op.MOVE, args[0].makeReg, args[1].makeReg, makeNone, i);
        else if (op == "clear" && args.length == 1)
            output ~= AsmInstr(Op.CLEAR, args[0].makeReg, makeNone, makeNone, i);
        else if (op == "neg" && args.length == 2)
            output ~= AsmInstr(Op.NEG, args[0].makeReg, args[1].makeReg, makeNone, i);
        else if (op == "not" && args.length == 2)
            output ~= AsmInstr(Op.NOT, args[0].makeReg, args[1].makeReg, makeNone, i);
        
        else if (op == "slt" && args.length == 3)
            output ~= AsmInstr(Op.SLT, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "slti" && args.length == 3)
            output ~= AsmInstr(Op.SLTI, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "sltu" && args.length == 3)
            output ~= AsmInstr(Op.SLTU, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "sltiu" && args.length == 3)
            output ~= AsmInstr(Op.SLTIU, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        
        else if (op == "and" && args.length == 3)
            output ~= AsmInstr(Op.AND, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "andi" && args.length == 3)
            output ~= AsmInstr(Op.ANDI, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "or" && args.length == 3)
            output ~= AsmInstr(Op.OR, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "ori" && args.length == 3)
            output ~= AsmInstr(Op.ORI, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "xor" && args.length == 3)
            output ~= AsmInstr(Op.XOR, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "xori" && args.length == 3)
            output ~= AsmInstr(Op.XORI, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "nor" && args.length == 3)
            output ~= AsmInstr(Op.NOR, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "sll" && args.length == 3)
            output ~= AsmInstr(Op.SLL, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "sllv" && args.length == 3)
            output ~= AsmInstr(Op.SLLV, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "srl" && args.length == 3)
            output ~= AsmInstr(Op.SRL, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "srlv" && args.length == 3)
            output ~= AsmInstr(Op.SRLV, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        else if (op == "sra" && args.length == 3)
            output ~= AsmInstr(Op.SRA, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "srav" && args.length == 3)
            output ~= AsmInstr(Op.SRAV, args[0].makeReg, args[1].makeReg, args[2].makeReg, i);
        
        else if (op == "lw" && args.length == 3)
            output ~= AsmInstr(Op.LW, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        else if (op == "lh" && args.length == 3)
            output ~= AsmInstr(Op.LH, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        else if (op == "lhu" && args.length == 3)
            output ~= AsmInstr(Op.LHU, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        else if (op == "lb" && args.length == 3)
            output ~= AsmInstr(Op.LB, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        else if (op == "lbu" && args.length == 3)
            output ~= AsmInstr(Op.LBU, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        else if (op == "lwl" && args.length == 3)
            output ~= AsmInstr(Op.LWL, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        else if (op == "lwr" && args.length == 3)
            output ~= AsmInstr(Op.LWR, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        else if (op == "sw" && args.length == 3)
            output ~= AsmInstr(Op.SW, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        else if (op == "sh" && args.length == 3)
            output ~= AsmInstr(Op.SH, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        else if (op == "sb" && args.length == 3)
            output ~= AsmInstr(Op.SB, args[0].makeReg, args[1].makeImm, args[2].makeReg, i);
        
        else if (op == "beq" && args.length == 3)
            output ~= AsmInstr(Op.BEQ, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "bne" && args.length == 3)
            output ~= AsmInstr(Op.BNE, args[0].makeReg, args[1].makeReg, args[2].makeImm, i);
        else if (op == "blez" && args.length == 2)
            output ~= AsmInstr(Op.BNE, args[0].makeReg, args[1].makeImm, makeNone, i);
        else if (op == "bgtz" && args.length == 2)
            output ~= AsmInstr(Op.BGTZ, args[0].makeReg, args[1].makeImm, makeNone, i);
        else if (op == "bgez" && args.length == 2)
            output ~= AsmInstr(Op.BGEZ, args[0].makeReg, args[1].makeImm, makeNone, i);
        else if (op == "bltz" && args.length == 2)
            output ~= AsmInstr(Op.BLTZ, args[0].makeReg, args[1].makeImm, makeNone, i);
        else if (op == "bgezal" && args.length == 2)
            output ~= AsmInstr(Op.BGEZAL, args[0].makeReg, args[1].makeImm, makeNone, i);
        else if (op == "bltzal" && args.length == 2)
            output ~= AsmInstr(Op.BLTZAL, args[0].makeReg, args[1].makeImm, makeNone, i);
        else if (op == "b" && args.length == 2)
            output ~= AsmInstr(Op.BEQ, args[0].makeReg, args[0].makeReg, args[1].makeImm, i);
        else if (op == "bal" && args.length == 1)
            output ~= AsmInstr(Op.BGEZAL, makeReg(R0), makeReg(R0), args[0].makeImm, i);
        
        else if (op == "syscall" && args.length >= 0)
        {
            if (args.length == 0)
                output ~= AsmInstr(Op.SYSCALL, makeImm(0), makeNone, makeNone, i);
            else
                output ~= AsmInstr(Op.SYSCALL, args[0].makeImm, makeNone, makeNone, i);
        }
        else if (op == "break" && args.length >= 0)
        {
            if (args.length == 0)
                output ~= AsmInstr(Op.BREAK, makeImm(0), makeNone, makeNone, i);
            else
                output ~= AsmInstr(Op.BREAK, args[0].makeImm, makeNone, makeNone, i);
        }
        
        // TODO: coprocessor instructions
        
        else
            throw new Exception("Unknown instruction: " ~ op);
        
        instrIndex++;
    }

    Assembly ass = new Assembly();
    ass.instructions = output;
    ass.dataEntries = dataEntries;
    ass.sections = sections;
    ass.dataLabels = dataLabels;
    return ass;
}
