/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module ast;

import types;

enum EK { Num, Str, Var, Unary, Binary, Assign, IncDec, Call, Index, Cast, Member }

class Expr
{
    EK kind;
    int line;
    string op;      // operator text (Unary, Binary, Assign, IncDec)
    string name;    // identifier (Var, Call) or raw string contents (Str)
    long num;       // Num
    Expr a, b;
    Expr[] args;    // Call
    CType ty;       // Cast target
    bool post;      // IncDec: postfix form
    bool uns;       // Num: unsigned literal
    bool arrow;     // Member: '->' instead of '.'

    this(EK k, int ln)
    {
        kind = k;
        line = ln;
    }
}

Expr numExpr(long v, int line)
{
    auto e = new Expr(EK.Num, line);
    e.num = v;
    return e;
}

enum SK { Block, Decl, ExprS, If, While, DoWhile, For, Return, Break, Continue, Empty }

class Stmt
{
    SK kind;
    int line;
    Stmt[] stmts;           // Block
    bool scoped = true;     // Block: opens a new scope?
    Expr e;                 // condition / expression / return value / declaration initializer
    Expr step;              // For
    Stmt forInit;           // For
    Stmt thenS;             // If / loop body
    Stmt elseS;             // If
    CType ty;               // Decl
    string name;            // Decl
    int arrLen = -1;        // Decl: -1 = scalar

    this(SK k, int ln)
    {
        kind = k;
        line = ln;
    }
}

struct Param
{
    CType ty;
    string name;
}

class Func
{
    CType ret;
    string name;
    Param[] params;
    Stmt body_;     // null for a prototype
    int line;
}

class GlobalDecl
{
    CType ty; // element type for arrays
    string name;
    int line;
    bool isArray;
    int arrLen = -1;
    bool hasInit;
    long[] inits;
    bool strInit;
    ubyte[] strBytes;
    string attrFilename;
}

class Program
{
    Func[] funcs;
    GlobalDecl[] globals;
}
