/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module codegen;

import std.format: format;
import std.file: read, readText, exists;

import error;
import lexer;
import types;
import ast;
import parser;
import utils;
import mips;
import ir;
import assembler;
import psxexe: STACK_ADDR;

// ---------------------------------------------------------------------------
// Register pools
// ---------------------------------------------------------------------------

enum int NTEMPS = 10;
immutable Reg[10] tempRegs = [T0, T1, T2, T3, T4, T5, T6, T7, T8, T9];
immutable Reg[8]  sRegs    = [S0, S1, S2, S3, S4, S5, S6, S7];
immutable Reg[4]  argRegs  = [A0, A1, A2, A3];

// Stack frame layout (offsets from $sp):
//   0 .. 39                 spill area for $t0-$t9 (saved around calls)
//   40 .. localsTop         locals that live in memory (arrays, address-taken, overflow)
//   savedBase ..            saved $s registers
//   raOff                   saved $ra
enum int TEMP_SAVE_AREA = 40;

// ---------------------------------------------------------------------------
// Code generator
// ---------------------------------------------------------------------------

struct Val
{
    Reg r;
    bool isTemp;    // true if r is an expression temporary owned by the caller
}

enum Storage { InReg, InStack, InGlobal }

class Var
{
    string name;
    CType ty;           // scalar type, or element type for arrays
    Storage st;
    Reg reg;            // InReg
    int offset;         // InStack: offset from $sp
    string label;       // InGlobal
    bool isArray;
    int arrLen;
}

enum LK { RegVar, Mem }

struct LValue
{
    LK kind;
    Reg reg;            // RegVar: the variable's register. Mem: base register.
    long off;           // Mem: byte offset from base
    CType ty;
    bool tempAddr;      // Mem: base register is a temporary owned by this lvalue
    bool isArr;         // Mem: designates an array member (decays to its address)
}

struct FuncInfo
{
    CType ret;
    CType[] params;
    bool defined;
}

struct Lbl
{
    string name;
    size_t idx;
}

struct PMove
{
    Var v;
    Reg src;
}

bool fits16(long v)
{
    return v >= -32768 && v <= 32767;
}

int log2i(long v)
{
    int n = 0;
    while ((1L << n) < v)
        n++;
    return n;
}

bool isPow2(long v)
{
    return v > 0 && (v & (v - 1)) == 0;
}

ubyte[] toBytes(long v, int size)
{
    ubyte[] b;
    foreach (i; 0 .. size)
        b ~= cast(ubyte)((v >> (8 * i)) & 0xFF);
    return b;
}

string invertCmp(string op)
{
    switch (op)
    {
        case "==": return "!=";
        case "!=": return "==";
        case "<":  return ">=";
        case ">=": return "<";
        case ">":  return "<=";
        default:   return ">"; // "<="
    }
}

class CodeGen
{
    Program prog;
    Assembly ass;
    AsmInstr[] program;

    Var[string] globals;
    FuncInfo[string] funcs;
    string[string] strPool;
    int labelCounter;
    int strCounter;

    // Per-function state
    AsmInstr[] cur;
    Lbl[] curLbls;
    Var[string][] scopes;
    int[] savedS;
    int td;                     // number of temporaries in use
    int nextS, maxS;            // $s register allocation
    int localsTop;
    bool hasCall;
    CType curRet;
    string retLabel;
    bool[string] addrTaken;
    string[] breakStack, contStack;
    PMove[] pmoves;
    int curLine;

    // ------------------------------------------------------------------
    // Emission helpers
    // ------------------------------------------------------------------

    void emit(Op op, AsmOperand a, AsmOperand b, AsmOperand c)
    {
        cur ~= AsmInstr(op, a, b, c, cast(size_t) curLine);
    }

    void rrr(Op op, Reg d, Reg s, Reg t)
    {
        emit(op, makeReg(d), makeReg(s), makeReg(t));
    }

    void rri(Op op, Reg d, Reg s, long imm)
    {
        emit(op, makeReg(d), makeReg(s), makeImm(imm));
    }

    void mem(Op op, Reg rt, long off, Reg base)
    {
        emit(op, makeReg(rt), makeImm(off), makeReg(base));
    }

    void nop()
    {
        emit(Op.NOP, makeNone(), makeNone(), makeNone());
    }

    void move(Reg d, Reg s)
    {
        if (d != s)
            emit(Op.MOVE, makeReg(d), makeReg(s), makeNone());
    }

    void li(Reg d, long v)
    {
        emit(Op.LI, makeReg(d), makeImm(v), makeNone());
    }

    void liLabel(Reg d, string label)
    {
        emit(Op.LI, makeReg(d), makeLabel(label), makeNone());
    }

    void jump(string label)
    {
        emit(Op.J, makeLabel(label), makeNone(), makeNone());
        nop();
    }

    void branch2(Op op, Reg a, Reg b, string label)
    {
        emit(op, makeReg(a), makeReg(b), makeLabel(label));
        nop();
    }

    void branch1(Op op, Reg a, string label)
    {
        emit(op, makeReg(a), makeLabel(label), makeNone());
        nop();
    }

    void emitLoad(CType ty, Reg rt, long off, Reg base)
    {
        int sz = ty.size();
        Op lop = Op.LW;
        if (sz == 2)
            lop = ty.uns ? Op.LHU : Op.LH;
        else if (sz == 1)
            lop = ty.uns ? Op.LBU : Op.LB;
        mem(lop, rt, off, base);
        nop(); // load delay slot
    }

    void emitStore(CType ty, Reg rt, long off, Reg base)
    {
        int sz = ty.size();
        mem(sz == 4 ? Op.SW : (sz == 2 ? Op.SH : Op.SB), rt, off, base);
    }

    // Sign-extend a register holding a char / short variable.
    void narrowReg(Reg r, CType ty)
    {
        if (ty.isPtr)
            return;
        if (ty.base == Base.Char)
        {
            if (ty.uns)
            {
                rri(Op.ANDI, r, r, 0xFF);
            }
            else
            {
                rri(Op.SLL, r, r, 24);
                rri(Op.SRA, r, r, 24);
            }
        }
        else if (ty.base == Base.Short)
        {
            if (ty.uns)
            {
                rri(Op.ANDI, r, r, 0xFFFF);
            }
            else
            {
                rri(Op.SLL, r, r, 16);
                rri(Op.SRA, r, r, 16);
            }
        }
    }

    string newLabel()
    {
        return format("L%s", labelCounter++);
    }

    void placeLabel(string name)
    {
        curLbls ~= Lbl(name, cur.length);
    }

    // ------------------------------------------------------------------
    // Temporaries
    // ------------------------------------------------------------------

    Reg allocTemp()
    {
        if (td >= NTEMPS)
            throw err(curLine, "expression too complex (out of temporary registers)");
        return tempRegs[td++];
    }

    void release(Val v)
    {
        if (v.isTemp)
            td--;
    }

    // Destination for a fresh result: the requested register, or a new temporary.
    Val dest0(int want)
    {
        if (want >= 0)
            return Val(cast(Reg) want, false);
        return Val(allocTemp(), true);
    }

    // Release operands (LIFO), then pick a destination. A released temporary is
    // naturally reused as the destination.
    Val dest1(int want, Val a)
    {
        release(a);
        return dest0(want);
    }

    Val dest2(int want, Val a, Val b)
    {
        release(b);
        release(a);
        return dest0(want);
    }

    // ------------------------------------------------------------------
    // Symbols
    // ------------------------------------------------------------------

    void pushScope()
    {
        Var[string] m;
        scopes ~= m;
        savedS ~= nextS;
    }

    void popScope()
    {
        scopes = scopes[0 .. $ - 1];
        nextS = savedS[$ - 1];
        savedS = savedS[0 .. $ - 1];
    }

    Var lookup(string name, int line)
    {
        foreach_reverse (ref sc; scopes)
        {
            if (auto p = name in sc)
                return *p;
        }
        if (auto p = name in globals)
            return *p;
        throw err(line, "undefined variable '" ~ name ~ "'");
    }

    int allocStack(int bytes)
    {
        int off = localsTop;
        localsTop += (bytes + 3) & ~3;
        if (localsTop > 32000)
            throw err(curLine, "stack frame too large");
        return off;
    }

    Var declareLocal(string name, CType ty, int arrLen, int line)
    {
        if (name in scopes[$ - 1])
            throw err(line, "redeclaration of '" ~ name ~ "'");
        if (ty.base == Base.Void && ty.ptr == 0)
            throw err(line, "variable '" ~ name ~ "' cannot have type void");

        auto v = new Var();
        v.name = name;
        v.ty = ty;
        if (arrLen >= 0)
        {
            v.isArray = true;
            v.arrLen = arrLen;
            v.st = Storage.InStack;
            v.offset = allocStack(arrLen * ty.size());
        }
        else if (isStructVal(ty))
        {
            v.st = Storage.InStack;
            v.offset = allocStack(ty.size());
        }
        else if ((name in addrTaken) || nextS >= 8)
        {
            v.st = Storage.InStack;
            v.offset = allocStack(4);
        }
        else
        {
            v.st = Storage.InReg;
            v.reg = sRegs[nextS++];
            if (nextS > maxS)
                maxS = nextS;
        }
        scopes[$ - 1][name] = v;
        return v;
    }

    string internString(string raw)
    {
        if (auto p = raw in strPool)
            return *p;
        string label = format("str_%s", strCounter++);
        ass.dataEntries ~= AsmDataEntry(label, parseEscapes(raw) ~ cast(ubyte) 0);
        strPool[raw] = label;
        return label;
    }

    // ------------------------------------------------------------------
    // Types of expressions
    // ------------------------------------------------------------------

    CType typeOf(Expr e)
    {
        switch (e.kind)
        {
            case EK.Num:
                return CType(Base.Int, 0, e.uns);

            case EK.Str:
                return CType(Base.Char, 1);

            case EK.Var:
            {
                Var v = lookup(e.name, e.line);
                CType t = v.ty;
                if (v.isArray)
                    t.ptr++;
                return t;
            }

            case EK.Unary:
            {
                if (e.op == "*")
                {
                    CType t = typeOf(e.a);
                    if (!t.isPtr)
                        throw err(e.line, "cannot dereference a non-pointer");
                    return t.deref();
                }
                if (e.op == "&")
                {
                    if (e.a.kind == EK.Var && lookup(e.a.name, e.a.line).isArray)
                        return typeOf(e.a);
                    if (e.a.kind == EK.Member && memberField(e.a).isArray)
                        return typeOf(e.a);
                    return typeOf(e.a).addr();
                }
                if (e.op == "!")
                    return CType(Base.Int, 0);
                // - and ~ : promoted operand type
                return isUint(typeOf(e.a)) ? CType(Base.Int, 0, true) : CType(Base.Int, 0);
            }

            case EK.Binary:
            {
                CType lt = typeOf(e.a);
                CType rt = typeOf(e.b);
                if (e.op == "+")
                {
                    if (lt.isPtr && !rt.isPtr) return lt;
                    if (rt.isPtr && !lt.isPtr) return rt;
                }
                else if (e.op == "-")
                {
                    if (lt.isPtr && !rt.isPtr) return lt;
                }
                if (inList(e.op, ["==", "!=", "<", "<=", ">", ">=", "&&", "||"]))
                    return CType(Base.Int, 0);
                if (e.op == "<<" || e.op == ">>")
                    return isUint(lt) ? CType(Base.Int, 0, true) : CType(Base.Int, 0);
                return (isUint(lt) || isUint(rt)) ? CType(Base.Int, 0, true) : CType(Base.Int, 0);
            }

            case EK.Assign:
            case EK.IncDec:
                return typeOf(e.a);

            case EK.Call:
            {
                if (e.name == "bios_a" || e.name == "bios_b" || e.name == "bios_c")
                    return CType(Base.Int, 0);
                if (auto p = e.name in funcs)
                    return p.ret;
                throw err(e.line, "call to undefined function '" ~ e.name ~ "'");
            }

            case EK.Index:
            {
                CType t = typeOf(e.a);
                if (!t.isPtr)
                    throw err(e.line, "subscripted value is neither array nor pointer");
                return t.deref();
            }

            case EK.Member:
            {
                Field f = memberField(e);
                CType t = f.ty;
                if (f.isArray)
                    t.ptr++;
                return t;
            }

            case EK.Cast:
                return e.ty;

            default:
                assert(0);
        }
    }

    // ------------------------------------------------------------------
    // Expressions
    // ------------------------------------------------------------------

    // Resolve the field named by a Member expression.
    Field memberField(Expr e)
    {
        CType bt = typeOf(e.a);
        if (e.arrow)
        {
            if (!(bt.ptr == 1 && bt.base == Base.Struct))
                throw err(e.line, "'->' needs a pointer to a struct");
        }
        else
        {
            if (!isStructVal(bt))
                throw err(e.line, "'.' needs a struct value (use '->' on pointers)");
        }
        StructDef sd = structDefs[bt.sname];
        foreach (f; sd.fields)
        {
            if (f.name == e.name)
                return f;
        }
        throw err(e.line, format("struct %s has no member '%s'", bt.sname, e.name));
    }

    // `want` is a hint: the result may be placed in that register. Callers must
    // check Val.r.
    Val genExpr(Expr e, int want = -1)
    {
        curLine = e.line;

        long cv;
        if (e.kind != EK.Num && constEval(e, cv))
            return genConst(cv, want);

        switch (e.kind)
        {
            case EK.Num:
                return genConst(e.num, want);

            case EK.Str:
            {
                Val d = dest0(want);
                liLabel(d.r, internString(e.name));
                return d;
            }

            case EK.Var:    return genVar(e, want);
            case EK.Unary:  return genUnary(e, want);
            case EK.Binary: return genBinary(e, want);
            case EK.Assign: return genAssign(e, want, false);
            case EK.IncDec: return genIncDec(e, want, false);
            case EK.Call:   return genCall(e, want, false);
            case EK.Cast:   return genCast(e, want);

            case EK.Member:
            {
                LValue lv = genLValue(e);
                if (lv.isArr)
                {
                    // array member decays to its address
                    Val da = dest1(want, Val(lv.reg, lv.tempAddr));
                    if (da.r != lv.reg || lv.off != 0)
                        rri(Op.ADDIU, da.r, lv.reg, lv.off);
                    return da;
                }
                return loadLV(lv, want, false);
            }

            case EK.Index:
            {
                LValue lv = genLValue(e);
                return loadLV(lv, want, false);
            }

            default:
                assert(0);
        }
    }

    Val genConst(long v, int want)
    {
        if (v == 0 && want < 0)
            return Val(R0, false);
        Val d = dest0(want);
        li(d.r, v);
        return d;
    }

    Val genVar(Expr e, int want)
    {
        Var v = lookup(e.name, e.line);
        if (v.isArray)
        {
            Val d = dest0(want);
            if (v.st == Storage.InStack)
                rri(Op.ADDIU, d.r, SP, v.offset);
            else
                liLabel(d.r, v.label);
            return d;
        }
        if (v.st == Storage.InReg)
            return Val(v.reg, false);
        LValue lv = genLValue(e);
        return loadLV(lv, want, false);
    }

    // ---- lvalues ----

    LValue genLValue(Expr e)
    {
        curLine = e.line;
        switch (e.kind)
        {
            case EK.Var:
            {
                Var v = lookup(e.name, e.line);
                if (v.isArray)
                    throw err(e.line, "cannot assign to array '" ~ v.name ~ "'");
                if (v.st == Storage.InReg)
                    return LValue(LK.RegVar, v.reg, 0, v.ty, false);
                if (v.st == Storage.InStack)
                    return LValue(LK.Mem, SP, v.offset, v.ty, false);
                Reg a = allocTemp();
                liLabel(a, v.label);
                return LValue(LK.Mem, a, 0, v.ty, true);
            }

            case EK.Unary:
            {
                if (e.op != "*")
                    throw err(e.line, "expression is not assignable");
                CType pt = typeOf(e.a);
                if (!pt.isPtr)
                    throw err(e.line, "cannot dereference a non-pointer");
                CType et = pt.deref();
                if (et.ptr == 0 && et.base == Base.Void)
                    throw err(e.line, "cannot dereference void*");
                Val pv = genExpr(e.a);
                return LValue(LK.Mem, pv.r, 0, et, pv.isTemp);
            }

            case EK.Index:
            {
                CType bt = typeOf(e.a);
                if (!bt.isPtr)
                    throw err(e.line, "subscripted value is neither array nor pointer");
                CType et = bt.deref();
                if (et.ptr == 0 && et.base == Base.Void)
                    throw err(e.line, "cannot index void*");
                int esz = et.size();

                long ci;
                if (constEval(e.b, ci) && fits16(ci * esz))
                {
                    long off = ci * esz;
                    if (e.a.kind == EK.Var)
                    {
                        Var av = lookup(e.a.name, e.a.line);
                        if (av.isArray && av.st == Storage.InStack && fits16(av.offset + off))
                            return LValue(LK.Mem, SP, av.offset + off, et, false);
                    }
                    Val bv = genExpr(e.a);
                    return LValue(LK.Mem, bv.r, off, et, bv.isTemp);
                }

                Val basev = genExpr(e.a);
                Val idx = scaleVal(genExpr(e.b), esz);
                Val sum = dest2(-1, basev, idx);
                rrr(Op.ADDU, sum.r, basev.r, idx.r);
                return LValue(LK.Mem, sum.r, 0, et, true);
            }

            case EK.Member:
            {
                Field f = memberField(e);
                if (e.arrow)
                {
                    Val pv = genExpr(e.a);
                    LValue la = LValue(LK.Mem, pv.r, f.offset, f.ty, pv.isTemp);
                    la.isArr = f.isArray;
                    return la;
                }
                LValue blv = genLValue(e.a);
                if (blv.kind != LK.Mem)
                    throw err(e.line, "internal error: struct held in a register");
                if (!fits16(blv.off + f.offset))
                    throw err(e.line, "struct member offset too large");
                blv.off += f.offset;
                blv.ty = f.ty;
                blv.isArr = f.isArray;
                return blv;
            }

            default:
                throw err(e.line, "expression is not assignable");
        }
    }

    // Load the value of an lvalue. With keepAddr the address temporary (if any)
    // stays allocated and a fresh temporary receives the value.
    Val loadLV(LValue lv, int want, bool keepAddr)
    {
        if (isStructVal(lv.ty))
            throw err(curLine, "a struct cannot be used as a value here (use its members, &, or '=')");
        if (lv.kind == LK.RegVar)
            return Val(lv.reg, false);
        Val d;
        if (keepAddr)
            d = dest0(want);
        else
            d = dest1(want, Val(lv.reg, lv.tempAddr));
        emitLoad(lv.ty, d.r, lv.off, lv.reg);
        return d;
    }

    void storeLV(LValue lv, Val v)
    {
        if (lv.kind == LK.RegVar)
        {
            move(lv.reg, v.r);
            narrowReg(lv.reg, lv.ty);
        }
        else
        {
            emitStore(lv.ty, v.r, lv.off, lv.reg);
        }
    }

    // After a store to a memory lvalue: free temporaries and produce the
    // expression's value (v is on top of the temporary stack, the lvalue's
    // address temporary, if any, is just below it).
    Val finishStore(LValue lv, Val v, bool discard)
    {
        if (discard)
        {
            release(v);
            if (lv.tempAddr)
                td--;
            return Val(R0, false);
        }
        if (lv.tempAddr)
        {
            if (v.isTemp)
            {
                move(lv.reg, v.r);
                release(v);
                return Val(lv.reg, true);
            }
            td--;
            return v;
        }
        return v;
    }

    // v << log2(size), reusing v's temporary when possible.
    Val scaleVal(Val v, int size)
    {
        if (size <= 1)
            return v;
        if (isPow2(size))
        {
            Val d = dest1(-1, v);
            rri(Op.SLL, d.r, v.r, log2i(size));
            return d;
        }
        // Non power of two (e.g. a 12-byte struct): multiply by a constant.
        Reg k = allocTemp();
        li(k, size);
        td--;                           // k is free again, but its register stays intact
        Val dm = dest1(-1, v);
        emit(Op.MULT, makeReg(v.r), makeReg(k), makeNone());
        emit(Op.MFLO, makeReg(dm.r), makeNone(), makeNone());
        return dm;
    }

    // ---- assignment, ++/-- ----

    Val genAssign(Expr e, int want, bool discard)
    {
        LValue lv = genLValue(e.a);
        bool isReg = (lv.kind == LK.RegVar);
        Val res;

        if (lv.isArr)
            throw err(e.line, "cannot assign to an array member");
        if (isStructVal(lv.ty))
        {
            if (e.op != "=")
                throw err(e.line, "invalid operator for structs");
            if (!discard)
                throw err(e.line, "a struct assignment cannot be used as a value");
            genStructCopy(lv, e.b, e.line);
            return Val(R0, false);
        }

        if (e.op == "=")
        {
            if (isReg)
            {
                Val v = genExpr(e.b, lv.reg);
                if (v.r != lv.reg)
                {
                    move(lv.reg, v.r);
                    release(v);
                }
                narrowReg(lv.reg, lv.ty);
                return Val(lv.reg, false);
            }
            res = genExpr(e.b);
        }
        else
        {
            string bop = e.op[0 .. $ - 1];
            long rscale = (lv.ty.isPtr && (bop == "+" || bop == "-")) ? elemSize(lv.ty) : 1;
            Val cur = loadLV(lv, -1, true);
            res = binopRhs(bop, cur, e.b, rscale, isReg ? lv.reg : -1,
                           opUnsigned(bop, lv.ty, typeOf(e.b)));
            if (isReg)
            {
                if (res.r != lv.reg)
                {
                    move(lv.reg, res.r);
                    release(res);
                }
                narrowReg(lv.reg, lv.ty);
                return Val(lv.reg, false);
            }
        }

        storeLV(lv, res);
        return finishStore(lv, res, discard);
    }

    Val genIncDec(Expr e, int want, bool discard)
    {
        // Prefix form (or value not needed): same as  x += 1  /  x -= 1
        if (!e.post || discard)
        {
            auto c = new Expr(EK.Assign, e.line);
            c.op = (e.op == "++") ? "+=" : "-=";
            c.a = e.a;
            c.b = numExpr(1, e.line);
            return genAssign(c, want, discard);
        }

        // Postfix with a used value: result is the old value.
        CType t = typeOf(e.a);
        long step = t.isPtr ? elemSize(t) : 1;
        if (e.op == "--")
            step = -step;

        LValue lv = genLValue(e.a);
        if (lv.isArr)
            throw err(e.line, "cannot modify an array member");
        if (lv.kind == LK.RegVar)
        {
            Reg old = allocTemp();
            move(old, lv.reg);
            rri(Op.ADDIU, lv.reg, lv.reg, step);
            narrowReg(lv.reg, lv.ty);
            return Val(old, true);
        }

        Val curv = loadLV(lv, -1, true);
        Reg nw = allocTemp();
        rri(Op.ADDIU, nw, curv.r, step);
        emitStore(lv.ty, nw, lv.off, lv.reg);
        td--; // release nw
        return finishStore(lv, curv, false);
    }

    // dst = <struct lvalue expression>: unrolled word / halfword / byte copy.
    void genStructCopy(LValue dst, Expr srcExpr, int line)
    {
        CType st = typeOf(srcExpr);
        if (!isStructVal(st) || st.sname != dst.ty.sname)
            throw err(line, "struct assignment needs the same struct type on both sides");
        LValue src = genLValue(srcExpr);
        if (src.kind != LK.Mem || dst.kind != LK.Mem)
            throw err(line, "internal error: struct held in a register");

        StructDef sd = structDefs[dst.ty.sname];
        int chunk = (sd.align_ >= 4) ? 4 : sd.align_;
        int n = sd.size / chunk;
        if (n > 32)
            throw err(line, "struct too large to copy inline (limit 32 words)");

        CType ct = CType(chunk == 4 ? Base.Int : (chunk == 2 ? Base.Short : Base.Char), 0, true);
        Reg t = allocTemp();
        foreach (i; 0 .. n)
        {
            emitLoad(ct, t, src.off + i * chunk, src.reg);
            emitStore(ct, t, dst.off + i * chunk, dst.reg);
        }
        td--;                       // t
        if (src.tempAddr)
            td--;
        if (dst.tempAddr)
            td--;
    }

    // ---- unary / cast / address-of ----

    Val genUnary(Expr e, int want)
    {
        if (e.op == "*")
        {
            LValue lv = genLValue(e);
            return loadLV(lv, want, false);
        }
        if (e.op == "&")
            return genAddrOf(e, want);

        Val a = genExpr(e.a);
        Val d = dest1(want, a);
        if (e.op == "-")
            rrr(Op.SUBU, d.r, R0, a.r);
        else if (e.op == "~")
            rrr(Op.NOR, d.r, a.r, R0);
        else if (e.op == "!")
            rri(Op.SLTIU, d.r, a.r, 1);
        else
            throw err(e.line, "unsupported unary operator " ~ e.op);
        return d;
    }

    Val genAddrOf(Expr e, int want)
    {
        Expr t = e.a;
        if (t.kind == EK.Var)
        {
            Var v = lookup(t.name, t.line);
            if (v.isArray)
                return genVar(t, want);
            if (v.st == Storage.InStack)
            {
                Val ds = dest0(want);
                rri(Op.ADDIU, ds.r, SP, v.offset);
                return ds;
            }
            if (v.st == Storage.InGlobal)
            {
                Val dg = dest0(want);
                liLabel(dg.r, v.label);
                return dg;
            }
            throw err(e.line, "internal error: address of a register variable");
        }

        LValue lv = genLValue(t);
        if (lv.kind != LK.Mem)
            throw err(e.line, "cannot take the address of this expression");
        Val dm = dest1(want, Val(lv.reg, lv.tempAddr));
        if (dm.r != lv.reg || lv.off != 0)
            rri(Op.ADDIU, dm.r, lv.reg, lv.off);
        return dm;
    }

    Val genCast(Expr e, int want)
    {
        Val v = genExpr(e.a, want);
        if (!e.ty.isPtr && (e.ty.base == Base.Char || e.ty.base == Base.Short))
        {
            Val d = dest1(want, v);
            if (e.ty.uns)
            {
                rri(Op.ANDI, d.r, v.r, (e.ty.base == Base.Char) ? 0xFF : 0xFFFF);
            }
            else
            {
                int sh = (e.ty.base == Base.Char) ? 24 : 16;
                rri(Op.SLL, d.r, v.r, sh);
                rri(Op.SRA, d.r, d.r, sh);
            }
            return d;
        }
        return v;
    }

    // ---- binary operators ----

    Val genBinary(Expr e, int want)
    {
        if (e.op == "&&" || e.op == "||")
            return genLogicalValue(e, want);

        CType lt = typeOf(e.a);
        CType rt = typeOf(e.b);
        bool lp = lt.isPtr;
        bool rp = rt.isPtr;

        long lscale = 1;
        long rscale = 1;
        bool ptrDiff = false;
        if (e.op == "+" && lp && !rp)        rscale = elemSize(lt);
        else if (e.op == "+" && rp && !lp)   lscale = elemSize(rt);
        else if (e.op == "-" && lp && !rp)   rscale = elemSize(lt);
        else if (e.op == "-" && lp && rp)    ptrDiff = true;

        Val l = genExpr(e.a);
        if (lscale > 1)
            l = scaleVal(l, cast(int) lscale);

        bool uns = opUnsigned(e.op, lt, rt);
        Val res = binopRhs(e.op, l, e.b, rscale, ptrDiff ? -1 : want, uns);

        if (ptrDiff)
        {
            int sz = elemSize(lt);
            if (sz > 1)
            {
                if (isPow2(sz))
                {
                    Val d = dest1(want, res);
                    rri(Op.SRA, d.r, res.r, log2i(sz));
                    return d;
                }
                Reg k = allocTemp();
                li(k, sz);
                td--;
                Val dq = dest1(want, res);
                emit(Op.DIV, makeReg(res.r), makeReg(k), makeNone());
                emit(Op.MFLO, makeReg(dq.r), makeNone(), makeNone());
                return dq;
            }
        }
        return res;
    }

    // Evaluate `l op rhs` where l is already evaluated. rscale scales the
    // right operand (pointer arithmetic).
    Val binopRhs(string op, Val l, Expr rhs, long rscale, int want, bool uns)
    {
        long c;
        if (constEval(rhs, c))
        {
            long cs = c * rscale;
            if (op == "+" && fits16(cs))
            {
                Val d = dest1(want, l);
                rri(Op.ADDIU, d.r, l.r, cs);
                return d;
            }
            if (op == "-" && fits16(-cs))
            {
                Val d = dest1(want, l);
                rri(Op.ADDIU, d.r, l.r, -cs);
                return d;
            }
            if ((op == "&" || op == "|" || op == "^") && cs >= 0 && cs <= 0xFFFF)
            {
                Val d = dest1(want, l);
                rri(op == "&" ? Op.ANDI : (op == "|" ? Op.ORI : Op.XORI), d.r, l.r, cs);
                return d;
            }
            if ((op == "<<" || op == ">>") && cs >= 0 && cs < 32)
            {
                Val d = dest1(want, l);
                rri(op == "<<" ? Op.SLL : (uns ? Op.SRL : Op.SRA), d.r, l.r, cs);
                return d;
            }
            if (op == "<" && fits16(cs))
            {
                Val d = dest1(want, l);
                rri(uns ? Op.SLTIU : Op.SLTI, d.r, l.r, cs);
                return d;
            }
            if (op == "*" && cs > 1 && isPow2(cs))
            {
                Val d = dest1(want, l);
                rri(Op.SLL, d.r, l.r, log2i(cs));
                return d;
            }
            if (op == "/" && uns && cs > 1 && isPow2(cs))
            {
                Val d = dest1(want, l);
                rri(Op.SRL, d.r, l.r, log2i(cs));
                return d;
            }
            if (op == "%" && uns && cs > 1 && isPow2(cs) && cs - 1 <= 0xFFFF)
            {
                Val d = dest1(want, l);
                rri(Op.ANDI, d.r, l.r, cs - 1);
                return d;
            }
        }

        Val r = genExpr(rhs);
        if (rscale > 1)
            r = scaleVal(r, cast(int) rscale);
        return emitBin(op, l, r, want, uns);
    }

    Val emitBin(string op, Val l, Val r, int want, bool uns)
    {
        Val d = dest2(want, l, r);
        Reg a = l.r;
        Reg b = r.r;
        Reg x = d.r;

        switch (op)
        {
            case "+":  rrr(Op.ADDU, x, a, b); break;
            case "-":  rrr(Op.SUBU, x, a, b); break;
            case "*":
                emit(Op.MULT, makeReg(a), makeReg(b), makeNone());
                emit(Op.MFLO, makeReg(x), makeNone(), makeNone());
                break;
            case "/":
                emit(uns ? Op.DIVU : Op.DIV, makeReg(a), makeReg(b), makeNone());
                emit(Op.MFLO, makeReg(x), makeNone(), makeNone());
                break;
            case "%":
                emit(uns ? Op.DIVU : Op.DIV, makeReg(a), makeReg(b), makeNone());
                emit(Op.MFHI, makeReg(x), makeNone(), makeNone());
                break;
            case "&":  rrr(Op.AND, x, a, b); break;
            case "|":  rrr(Op.OR, x, a, b); break;
            case "^":  rrr(Op.XOR, x, a, b); break;
            case "<<": rrr(Op.SLLV, x, a, b); break;
            case ">>": rrr(uns ? Op.SRLV : Op.SRAV, x, a, b); break;
            case "<":  rrr(uns ? Op.SLTU : Op.SLT, x, a, b); break;
            case ">":  rrr(uns ? Op.SLTU : Op.SLT, x, b, a); break;
            case "<=":
                rrr(uns ? Op.SLTU : Op.SLT, x, b, a);
                rri(Op.XORI, x, x, 1);
                break;
            case ">=":
                rrr(uns ? Op.SLTU : Op.SLT, x, a, b);
                rri(Op.XORI, x, x, 1);
                break;
            case "==":
                rrr(Op.XOR, x, a, b);
                rri(Op.SLTIU, x, x, 1);
                break;
            case "!=":
                rrr(Op.XOR, x, a, b);
                rrr(Op.SLTU, x, R0, x);
                break;
            default:
                throw err(curLine, "unsupported operator " ~ op);
        }
        return d;
    }

    // && / || used as a value: materialize 0 or 1.
    Val genLogicalValue(Expr e, int want)
    {
        string lFalse = newLabel();
        string lEnd = newLabel();
        genBranch(e, lFalse, false);
        Val d = dest0(want);
        li(d.r, 1);
        jump(lEnd);
        placeLabel(lFalse);
        li(d.r, 0);
        placeLabel(lEnd);
        return d;
    }

    // ---- conditions ----

    // Jump to `target` if e is true (jumpIfTrue) or false (!jumpIfTrue);
    // otherwise fall through.
    void genBranch(Expr e, string target, bool jumpIfTrue)
    {
        curLine = e.line;

        long cv;
        if (constEval(e, cv))
        {
            if ((cv != 0) == jumpIfTrue)
                jump(target);
            return;
        }

        if (e.kind == EK.Unary && e.op == "!")
        {
            genBranch(e.a, target, !jumpIfTrue);
            return;
        }

        if (e.kind == EK.Binary)
        {
            string op = e.op;
            if (op == "&&")
            {
                if (jumpIfTrue)
                {
                    string skip = newLabel();
                    genBranch(e.a, skip, false);
                    genBranch(e.b, target, true);
                    placeLabel(skip);
                }
                else
                {
                    genBranch(e.a, target, false);
                    genBranch(e.b, target, false);
                }
                return;
            }
            if (op == "||")
            {
                if (jumpIfTrue)
                {
                    genBranch(e.a, target, true);
                    genBranch(e.b, target, true);
                }
                else
                {
                    string skip = newLabel();
                    genBranch(e.a, skip, true);
                    genBranch(e.b, target, false);
                    placeLabel(skip);
                }
                return;
            }
            if (op == "==" || op == "!=" || op == "<" || op == "<=" || op == ">" || op == ">=")
            {
                bool uns = opUnsigned(op, typeOf(e.a), typeOf(e.b));
                genCmpBranch(jumpIfTrue ? op : invertCmp(op), e.a, e.b, target, uns);
                return;
            }
        }

        Val v = genExpr(e);
        branch2(jumpIfTrue ? Op.BNE : Op.BEQ, v.r, R0, target);
        release(v);
    }

    // Jump to target if `a op b` holds.
    void genCmpBranch(string op, Expr a, Expr b, string target, bool uns)
    {
        long c;
        if (constEval(b, c) && c == 0 && (op == "<" || op == "<=" || op == ">" || op == ">="))
        {
            Val z = genExpr(a);
            if (!uns)
            {
                Op bop = (op == "<") ? Op.BLTZ : (op == "<=") ? Op.BLEZ : (op == ">") ? Op.BGTZ : Op.BGEZ;
                branch1(bop, z.r, target);
            }
            else if (op == ">=")
            {
                jump(target);                       // unsigned x >= 0 is always true
            }
            else if (op == ">")
            {
                branch2(Op.BNE, z.r, R0, target);   // x > 0  <=>  x != 0
            }
            else if (op == "<=")
            {
                branch2(Op.BEQ, z.r, R0, target);   // x <= 0  <=>  x == 0
            }
            // unsigned x < 0 is never true: no branch
            release(z);
            return;
        }

        Val l = genExpr(a);
        Val r = genExpr(b);

        if (op == "==" || op == "!=")
        {
            branch2(op == "==" ? Op.BEQ : Op.BNE, l.r, r.r, target);
            release(r);
            release(l);
            return;
        }

        Op slt = uns ? Op.SLTU : Op.SLT;
        Val t = dest2(-1, l, r);
        if (op == "<")
        {
            rrr(slt, t.r, l.r, r.r);
            branch2(Op.BNE, t.r, R0, target);
        }
        else if (op == ">=")
        {
            rrr(slt, t.r, l.r, r.r);
            branch2(Op.BEQ, t.r, R0, target);
        }
        else if (op == ">")
        {
            rrr(slt, t.r, r.r, l.r);
            branch2(Op.BNE, t.r, R0, target);
        }
        else // "<="
        {
            rrr(slt, t.r, r.r, l.r);
            branch2(Op.BEQ, t.r, R0, target);
        }
        release(t);
    }

    // ---- calls ----

    Val genCall(Expr e, int want, bool discard)
    {
        string name = e.name;
        bool bios = (name == "bios_a" || name == "bios_b" || name == "bios_c");
        Expr[] args = e.args;
        long biosFn = 0;

        if (bios)
        {
            if (args.length < 1 || !constEval(args[0], biosFn))
                throw err(e.line, name ~ "() needs a constant function number as its first argument");
            args = args[1 .. $];
        }
        else
        {
            auto pf = name in funcs;
            if (pf is null)
                throw err(e.line, "call to undefined function '" ~ name ~ "'");
            if (!pf.defined)
                throw err(e.line, "function '" ~ name ~ "' is declared but never defined");
            if (args.length != pf.params.length)
                throw err(e.line, format("'%s' expects %s argument(s) but %s given",
                                         name, pf.params.length, args.length));
        }
        if (args.length > 4)
            throw err(e.line, "at most 4 call arguments are supported");

        hasCall = true;
        int d0 = td; // temporaries that are live across the call

        Val[] vals;
        foreach (a; args)
            vals ~= genExpr(a);

        // Save live temporaries
        foreach (i; 0 .. d0)
            mem(Op.SW, tempRegs[i], 4 * i, SP);

        foreach (i, v; vals)
            move(argRegs[i], v.r);

        if (bios)
        {
            li(T1, biosFn);
            li(T2, name == "bios_a" ? 0xA0 : (name == "bios_b" ? 0xB0 : 0xC0));
            emit(Op.JALR, makeReg(RA), makeReg(T2), makeNone());
            nop();
        }
        else
        {
            emit(Op.JAL, makeLabel("f_" ~ name), makeNone(), makeNone());
            nop();
        }

        // Restore live temporaries
        foreach (i; 0 .. d0)
            mem(Op.LW, tempRegs[i], 4 * i, SP);
        if (d0 > 0)
            nop(); // load delay slot

        foreach_reverse (v; vals)
            release(v);

        if (discard)
            return Val(R0, false);

        Val d = dest0(want);
        move(d.r, V0);
        return d;
    }

    // ------------------------------------------------------------------
    // Statements
    // ------------------------------------------------------------------

    void genExprStmt(Expr e)
    {
        curLine = e.line;
        Val v;
        if (e.kind == EK.Assign)
            v = genAssign(e, -1, true);
        else if (e.kind == EK.IncDec)
            v = genIncDec(e, -1, true);
        else if (e.kind == EK.Call)
            v = genCall(e, -1, true);
        else
            v = genExpr(e);
        release(v);
        td = 0;
    }

    void genStmt(Stmt s)
    {
        curLine = s.line;
        switch (s.kind)
        {
            case SK.Block:
            {
                if (s.scoped)
                    pushScope();
                foreach (c; s.stmts)
                    genStmt(c);
                if (s.scoped)
                    popScope();
                break;
            }

            case SK.Decl:
                genDecl(s);
                break;

            case SK.ExprS:
                genExprStmt(s.e);
                break;

            case SK.If:
            {
                string lElse = newLabel();
                genBranch(s.e, lElse, false);
                td = 0;
                genStmt(s.thenS);
                if (s.elseS !is null)
                {
                    string lEnd = newLabel();
                    jump(lEnd);
                    placeLabel(lElse);
                    genStmt(s.elseS);
                    placeLabel(lEnd);
                }
                else
                {
                    placeLabel(lElse);
                }
                break;
            }

            case SK.While:
            {
                string lCond = newLabel();
                string lEnd = newLabel();
                placeLabel(lCond);
                genBranch(s.e, lEnd, false);
                td = 0;
                breakStack ~= lEnd;
                contStack ~= lCond;
                genStmt(s.thenS);
                breakStack = breakStack[0 .. $ - 1];
                contStack = contStack[0 .. $ - 1];
                jump(lCond);
                placeLabel(lEnd);
                break;
            }

            case SK.DoWhile:
            {
                string lTop = newLabel();
                string lCont = newLabel();
                string lEnd = newLabel();
                placeLabel(lTop);
                breakStack ~= lEnd;
                contStack ~= lCont;
                genStmt(s.thenS);
                breakStack = breakStack[0 .. $ - 1];
                contStack = contStack[0 .. $ - 1];
                placeLabel(lCont);
                genBranch(s.e, lTop, true);
                td = 0;
                placeLabel(lEnd);
                break;
            }

            case SK.For:
            {
                pushScope();
                if (s.forInit !is null)
                    genStmt(s.forInit);
                string lCond = newLabel();
                string lStep = newLabel();
                string lEnd = newLabel();
                placeLabel(lCond);
                if (s.e !is null)
                {
                    genBranch(s.e, lEnd, false);
                    td = 0;
                }
                breakStack ~= lEnd;
                contStack ~= lStep;
                genStmt(s.thenS);
                breakStack = breakStack[0 .. $ - 1];
                contStack = contStack[0 .. $ - 1];
                placeLabel(lStep);
                if (s.step !is null)
                    genExprStmt(s.step);
                jump(lCond);
                placeLabel(lEnd);
                popScope();
                break;
            }

            case SK.Return:
            {
                if (s.e !is null)
                {
                    if (curRet.ptr == 0 && curRet.base == Base.Void)
                        throw err(s.line, "void function cannot return a value");
                    Val v = genExpr(s.e, V0);
                    move(V0, v.r);
                    release(v);
                    td = 0;
                }
                jump(retLabel);
                break;
            }

            case SK.Break:
                if (breakStack.length == 0)
                    throw err(s.line, "'break' outside of a loop");
                jump(breakStack[$ - 1]);
                break;

            case SK.Continue:
                if (contStack.length == 0)
                    throw err(s.line, "'continue' outside of a loop");
                jump(contStack[$ - 1]);
                break;

            default:
                break;
        }
    }

    void genDecl(Stmt s)
    {
        Var v = declareLocal(s.name, s.ty, s.arrLen, s.line);
        if (s.e !is null)
        {
            if (v.isArray)
                throw err(s.line, "local array initializers are not supported");
            auto target = new Expr(EK.Var, s.line);
            target.name = s.name;
            auto asg = new Expr(EK.Assign, s.line);
            asg.op = "=";
            asg.a = target;
            asg.b = s.e;
            genExprStmt(asg);
        }
    }

    // ------------------------------------------------------------------
    // Functions and program
    // ------------------------------------------------------------------

    // Find variables whose address is taken (they must live in memory).
    void scanExpr(Expr e)
    {
        if (e is null)
            return;
        if (e.kind == EK.Unary && e.op == "&" && e.a !is null && e.a.kind == EK.Var)
            addrTaken[e.a.name] = true;
        scanExpr(e.a);
        scanExpr(e.b);
        foreach (x; e.args)
            scanExpr(x);
    }

    void scanStmt(Stmt s)
    {
        if (s is null)
            return;
        scanExpr(s.e);
        scanExpr(s.step);
        scanStmt(s.forInit);
        scanStmt(s.thenS);
        scanStmt(s.elseS);
        foreach (c; s.stmts)
            scanStmt(c);
    }

    void genFunc(Func f)
    {
        cur = null;
        curLbls = null;
        scopes = null;
        savedS = null;
        breakStack = null;
        contStack = null;
        pmoves = null;
        td = 0;
        nextS = 0;
        maxS = 0;
        localsTop = TEMP_SAVE_AREA;
        hasCall = false;
        curRet = f.ret;
        curLine = f.line;
        retLabel = newLabel();
        addrTaken = null;
        scanStmt(f.body_);

        if (f.params.length > 4)
            throw err(f.line, "functions may have at most 4 parameters");

        pushScope();
        foreach (i, prm; f.params)
        {
            Var v = declareLocal(prm.name, prm.ty, -1, f.line);
            pmoves ~= PMove(v, argRegs[i]);
        }
        genStmt(f.body_);
        popScope();

        placeLabel(retLabel);

        // Peephole: drop a trailing "j ret; nop" (a return as the last statement).
        if (cur.length >= 2
            && cur[$ - 2].op == Op.J
            && cur[$ - 2].operand1.type == AsmOperandType.Label
            && cur[$ - 2].operand1.label == retLabel
            && cur[$ - 1].op == Op.NOP)
        {
            cur = cur[0 .. $ - 2];
            foreach (ref l; curLbls)
            {
                if (l.idx > cur.length)
                    l.idx = cur.length;
            }
        }

        AsmInstr[] bodyInstrs = cur;
        Lbl[] bodyLbls = curLbls;
        cur = null;
        curLbls = null;

        int savedBase = (localsTop + 3) & ~3;
        int raOff = savedBase + 4 * maxS;
        int frame = (raOff + 4 + 7) & ~7;
        if (frame > 32000)
            throw err(f.line, "stack frame too large");

        // Prologue
        placeLabel("f_" ~ f.name);
        rri(Op.ADDIU, SP, SP, -frame);
        if (hasCall)
            mem(Op.SW, RA, raOff, SP);
        foreach (i; 0 .. maxS)
            mem(Op.SW, sRegs[i], savedBase + 4 * i, SP);
        foreach (pm; pmoves)
        {
            if (pm.v.st == Storage.InReg)
            {
                move(pm.v.reg, pm.src);
                narrowReg(pm.v.reg, pm.v.ty);
            }
            else
            {
                emitStore(pm.v.ty, pm.src, pm.v.offset, SP);
            }
        }

        // Body
        size_t bodyBase = cur.length;
        foreach (l; bodyLbls)
            curLbls ~= Lbl(l.name, l.idx + bodyBase);
        cur ~= bodyInstrs;

        // Epilogue ($ra is reloaded first so the load delay is covered)
        if (hasCall)
            mem(Op.LW, RA, raOff, SP);
        foreach (i; 0 .. maxS)
            mem(Op.LW, sRegs[i], savedBase + 4 * i, SP);
        rri(Op.ADDIU, SP, SP, frame);
        emit(Op.JR, makeReg(RA), makeNone(), makeNone());
        nop();

        flush();
    }

    void genAsmFunc(Func f)
    {
        cur = null;
        curLbls = null;
        scopes = null;
        savedS = null;
        breakStack = null;
        contStack = null;
        pmoves = null;
        td = 0;
        nextS = 0;
        maxS = 0;
        localsTop = TEMP_SAVE_AREA;
        hasCall = true;
        curRet = f.ret;
        curLine = f.line;
        retLabel = newLabel();
        addrTaken = null;
        
        if (f.params.length > 4)
            throw err(f.line, "functions may have at most 4 parameters");

        pushScope();
        foreach (i, prm; f.params)
        {
            Var v = declareLocal(prm.name, prm.ty, -1, f.line);
            pmoves ~= PMove(v, argRegs[i]);
        }
        
        if (f.attrFilename != "")
        {
            string asmFilename = f.attrFilename;
            if (!exists(asmFilename))
                throw err(f.line, "can't find file \"" ~ asmFilename ~ "\"");
            string asmCode = readText(asmFilename);
            Assembly extAsm = parseAsm(asmCode, asmFilename, cur.length);
            cur ~= extAsm.instructions;
            ass.dataEntries ~= extAsm.dataEntries;
        }
        
        popScope();

        placeLabel(retLabel);

        // Peephole: drop a trailing "j ret; nop" (a return as the last statement).
        if (cur.length >= 2
            && cur[$ - 2].op == Op.J
            && cur[$ - 2].operand1.type == AsmOperandType.Label
            && cur[$ - 2].operand1.label == retLabel
            && cur[$ - 1].op == Op.NOP)
        {
            cur = cur[0 .. $ - 2];
            foreach (ref l; curLbls)
            {
                if (l.idx > cur.length)
                    l.idx = cur.length;
            }
        }

        AsmInstr[] bodyInstrs = cur;
        Lbl[] bodyLbls = curLbls;
        cur = null;
        curLbls = null;

        int savedBase = (localsTop + 3) & ~3;
        int raOff = savedBase + 4 * maxS;
        int frame = (raOff + 4 + 7) & ~7;
        if (frame > 32000)
            throw err(f.line, "stack frame too large");

        // Prologue
        placeLabel("f_" ~ f.name);
        rri(Op.ADDIU, SP, SP, -frame);
        if (hasCall)
            mem(Op.SW, RA, raOff, SP);
        foreach (i; 0 .. maxS)
            mem(Op.SW, sRegs[i], savedBase + 4 * i, SP);
        foreach (pm; pmoves)
        {
            if (pm.v.st == Storage.InReg)
            {
                move(pm.v.reg, pm.src);
                narrowReg(pm.v.reg, pm.v.ty);
            }
            else
            {
                emitStore(pm.v.ty, pm.src, pm.v.offset, SP);
            }
        }

        // Body
        size_t bodyBase = cur.length;
        foreach (l; bodyLbls)
            curLbls ~= Lbl(l.name, l.idx + bodyBase);
        cur ~= bodyInstrs;

        // Epilogue ($ra is reloaded first so the load delay is covered)
        if (hasCall)
            mem(Op.LW, RA, raOff, SP);
        foreach (i; 0 .. maxS)
            mem(Op.LW, sRegs[i], savedBase + 4 * i, SP);
        rri(Op.ADDIU, SP, SP, frame);
        emit(Op.JR, makeReg(RA), makeNone(), makeNone());
        nop();

        flush();
    }

    // Append the current buffer to the program and register its labels.
    void flush()
    {
        foreach (l; curLbls)
            ass.sections[l.name] = program.length + l.idx;
        program ~= cur;
        cur = null;
        curLbls = null;
    }

    // Entry stub: set up $sp, call main, spin forever if it returns.
    void genStartup()
    {
        cur = null;
        curLbls = null;
        curLine = 0;
        placeLabel("_start");
        li(SP, STACK_ADDR);
        emit(Op.JAL, makeLabel("f_main"), makeNone(), makeNone());
        nop();
        placeLabel("_halt");
        jump("_halt");
        flush();
    }

    void declareGlobal(GlobalDecl g)
    {
        if (g.name in globals)
            throw err(g.line, "redefinition of global '" ~ g.name ~ "'");
        if (g.ty.ptr == 0 && g.ty.base == Base.Void)
            throw err(g.line, "variable '" ~ g.name ~ "' cannot have type void");

        if (isStructVal(g.ty) && g.hasInit)
            throw err(g.line, "struct initializers are not supported");

        auto v = new Var();
        v.name = g.name;
        v.ty = g.ty;
        v.st = Storage.InGlobal;
        v.label = "g_" ~ g.name;

        int esz = g.ty.size();
        ubyte[] data;
        
        if (g.attrFilename.length > 0)
        {
            if (g.ty.ptr == 0)
                throw err(g.line, "file attribute requires an array");
            
            // TODO: build path for searching external files
            string externalFile = g.attrFilename;
            if (exists(externalFile))
                data = cast(ubyte[])read(externalFile);
            else
                throw err(g.line, "can't find file \"" ~ externalFile ~ "\"");
            v.isArray = true;
            v.arrLen = cast(int)data.length;
        }
        else if (g.isArray)
        {
            int n = g.arrLen;
            if (g.strInit)
            {
                if (g.ty.ptr != 0 || g.ty.base != Base.Char)
                    throw err(g.line, "a string initializer requires a char array");
                if (n < 0)
                    n = cast(int) g.strBytes.length;
                if (cast(int) g.strBytes.length > n)
                    throw err(g.line, "string initializer is too long for the array");
                data = g.strBytes.dup;
                data.length = n;
            }
            else
            {
                if (n < 0)
                {
                    if (!g.hasInit)
                        throw err(g.line, "array needs a size or an initializer");
                    n = cast(int) g.inits.length;
                }
                if (cast(int) g.inits.length > n)
                    throw err(g.line, "too many initializers");
                foreach (x; g.inits)
                    data ~= toBytes(x, esz);
                data.length = n * esz;
            }
            v.isArray = true;
            v.arrLen = n;
        }
        else
        {
            if (g.strInit)
                throw err(g.line, "string initializers are only supported for char arrays");
            if (isStructVal(g.ty))
            {
                data = new ubyte[esz]; // zero-initialized
            }
            else
            {
                long iv = (g.inits.length > 0) ? g.inits[0] : 0;
                data = toBytes(iv, esz);
            }
        }

        ass.dataEntries ~= AsmDataEntry(v.label, data);
        globals[g.name] = v;
    }

    void registerFunc(Func f)
    {
        CType[] ps;
        foreach (prm; f.params)
            ps ~= prm.ty;

        bool alreadyDefined = false;
        if (auto q = f.name in funcs)
            alreadyDefined = q.defined;
        if (alreadyDefined && f.body_ !is null)
            throw err(f.line, "redefinition of function '" ~ f.name ~ "'");

        FuncInfo fi;
        fi.ret = f.ret;
        fi.params = ps;
        fi.defined = alreadyDefined || f.body_ !is null || f.isExternal;
        funcs[f.name] = fi;
    }

    Assembly generate(Program p)
    {
        prog = p;
        ass = new Assembly();

        foreach (g; p.globals)
            declareGlobal(g);
        foreach (f; p.funcs)
            registerFunc(f);

        auto pm = "main" in funcs;
        if (pm is null || !pm.defined)
            throw new Exception("program has no main() function");

        genStartup();
        foreach (f; p.funcs)
        {
            if (f.body_ !is null)
                genFunc(f);
            else if (f.attrFilename != "")
                genAsmFunc(f);
        }

        ass.instructions = program;
        return ass;
    }
}
