/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Simple C-like language compiler targeting the MIPS R3000 (PlayStation 1).
 *
 * The compiler does not encode machine code itself. It builds an `Assembly`
 * (the same structure the assembler front end produces) so the regular back end
 * in main.d does encoding, label resolution, data layout and PS-X EXE output.
 *
 *   - Code labels live in Assembly.sections (label -> instruction index).
 *   - Globals and string literals live in Assembly.dataEntries.
 *   - Branch / jump / li operands that refer to labels use AsmOperandType.Label.
 *
 * Language summary
 * ----------------
 *   Types      : int/short/char, uint/ushort/uchar (also unsigned [int|short|char]),
 *                void, and pointers to them. Pointers compare as unsigned.
 *                Literals above 0x7FFFFFFF, or with a 'u' suffix, are unsigned.
 *                Like C, uchar/ushort promote to (signed) int in arithmetic; only uint
 *                makes / % >> and comparisons unsigned.
 *   Structs    : top-level definitions  struct Name { int a; uchar c[3]; struct Other o; };
 *                Used as  struct Name x;  struct Name* p;  p->a  x.a  x.o.b  arr[i].a
 *                Fields may be scalars, pointers, arrays or nested structs. Structs can be
 *                copied with '=' (inline, up to 32 words), have their address taken, and be
 *                measured with sizeof(struct Name) / sizeof(type).
 *                Not supported: struct initializers, passing/returning structs by value,
 *                unions, bit-fields, typedef, sizeof(expression).
 *   Globals    : scalars and arrays with constant initializers, e.g.
 *                    int x = 5;   int t[4] = {1,2,3,4};   char s[] = "hi";
 *   Locals     : scalars and (uninitialized) arrays.
 *   Statements : if/else, while, do-while, for, break, continue, return, blocks.
 *   Operators  : C precedence, minus the ternary and comma operators.
 *                + - * / % & | ^ << >> ~ ! && || == != < <= > >= = op= ++ -- * & [] () casts.
 *   Calls      : up to 4 arguments / parameters (passed in $a0-$a3), result in $v0.
 *   Builtins   : bios_a(n, ...), bios_b(n, ...), bios_c(n, ...) call BIOS function n
 *                through the A0h / B0h / C0h vectors (up to 3 further arguments).
 *                e.g. bios_a(0x3F, "x=%d\n", x)  ->  printf
 *   Entry      : main(), started from a small stub that sets $sp.
 *
 * Code generation notes
 * ---------------------
 *   - Scalar locals live in $s0-$s7 (callee-saved) unless their address is taken,
 *     in which case (or when registers run out) they live in the stack frame.
 *   - Expression temporaries use $t0-$t9 as a register stack. Live temporaries
 *     are saved around calls.
 *   - Every branch / jump is followed by a nop, every load by a nop (R3000 delay slots).
 */
module compiler;

import types;
import lexer;
import ast;
import parser;
import codegen;
import ir;

/// Compiles source text to Assembly object.
Assembly compile(string source)
{
    structDefs = null;
    Token[] toks = lex(source);
    Program p = (new Parser(toks)).parseProgram();
    return (new CodeGen()).generate(p);
}
