/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module ir;

import std.algorithm;
import std.string;
import std.conv: to;
import mips;
import utils;

enum AsmOperandType
{
    None,
    Reg,
    Imm,
    Label
}

string regToString(Reg r)
{
    static immutable string[32] regNames = [
        0: "R0",  1: "AT",  2: "V0",  3: "V1",
        4: "A0",  5: "A1",  6: "A2",  7: "A3",
        8: "T0",  9: "T1", 10: "T2", 11: "T3", 12: "T4", 13: "T5", 14: "T6", 15: "T7",
        16: "S0", 17: "S1", 18: "S2", 19: "S3", 20: "S4", 21: "S5", 22: "S6", 23: "S7",
        24: "T8", 25: "T9", 26: "K0", 27: "K1",
        28: "GP", 29: "SP", 30: "FP", 31: "RA"
    ];

    if (r < regNames.length)
        return regNames[r];
        
    return "unk(" ~ r.to!string ~ ")";
}

struct AsmOperand
{
    Reg reg;
    long imm;
    string label;
    AsmOperandType type;
    long offset;
    
    string toString()
    {
        if (type == AsmOperandType.Reg)
            return regToString(reg);
        else if (type == AsmOperandType.Imm)
            return "0x" ~ to!string(imm, 16);
        else if (type == AsmOperandType.Label)
            return label;
        else
            return "none";
    }
}

AsmOperand makeNone()
{
    AsmOperand operand;
    operand.type = AsmOperandType.None;
    return operand;
}

AsmOperand makeReg(ubyte reg)
{
    AsmOperand operand;
    operand.reg = reg;
    operand.type = AsmOperandType.Reg;
    return operand;
}

AsmOperand makeReg(string s)
{
    AsmOperand operand;
    operand.reg = parseReg(s);
    operand.type = AsmOperandType.Reg;
    return operand;
}

AsmOperand makeImm(string s)
{
    AsmOperand operand;
    operand.imm = parseInt(s);
    operand.type = AsmOperandType.Imm;
    return operand;
}

AsmOperand makeImm(long imm)
{
    AsmOperand operand;
    operand.imm = imm;
    operand.type = AsmOperandType.Imm;
    return operand;
}

AsmOperand makeLabel(string s)
{
    AsmOperand operand;
    operand.imm = 0xffffffff;
    operand.label = s;
    operand.type = AsmOperandType.Label;
    return operand;
}

struct AsmInstr
{
    Op op;
    AsmOperand operand1;
    AsmOperand operand2;
    AsmOperand operand3;
    size_t line;
    Word[] code; // generated 32-bit words
    size_t offset; // physical offset from the start of the code
}

struct AsmDataEntry
{
    string label;
    ubyte[] data;
}

class Assembly
{
    AsmInstr[] instructions;
    AsmDataEntry[] dataEntries;
    size_t[string] sections;
    size_t[string] dataLabels;
    
    this()
    {
    }
}

Reg parseReg(string s)
{
    s = s.strip.toLower;
    if (s.startsWith("$"))
        s = s[1..$];

    switch (s)
    {
        case "zero", "r0":  return R0;
        case "at": return AT;
        case "v0": return V0;
        case "v1": return V1;
        case "a0": return A0;
        case "a1": return A1;
        case "a2": return A2;
        case "a3": return A3;
        case "t0": return T0;
        case "t1": return T1;
        case "t2": return T2;
        case "t3": return T3;
        case "t4": return T4;
        case "t5": return T5;
        case "t6": return T6;
        case "t7": return T7;
        case "s0": return S0;
        case "s1": return S1;
        case "s2": return S2;
        case "s3": return S3;
        case "s4": return S4;
        case "s5": return S5;
        case "s6": return S6;
        case "s7": return S7;
        case "t8": return T8;
        case "t9": return T9;
        case "gp": return GP;
        case "sp": return SP;
        case "fp", "s8": return FP;
        case "ra": return RA;
        default: throw new Exception("Unsupported register");
    }
}
