/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Retrolang Intermediate Representation for MIPS-I code.
 *
 * Provided functionality allows to store the program in an abstract form,
 * without encoding to machine code early, which is convenient for a compiler.
 * `Assembly` struct separately stores program code and data, plus labels
 * that reference the data (for variables) and sections with global indices
 * (for functions).
 * Indices in the `Assembly` are not machine word offsets! Exact machine code size
 * and real offsets should be determined at the post-processing step
 * after the program is fully assembled, because some pseudoinstructions
 * are resolved to more than one word (see linker.d)
 */
module ir;

import std.format;
import std.algorithm;
import std.string;
import std.conv: to;
import mips;
import utils;

enum AsmOperandType
{
    None,
    Reg,
    RegCop0,
    RegGteData,
    RegGteControl,
    Imm,
    Label
}

string regToString(Reg r)
{
    static immutable string[32] regNames = [
        0: "R0",  1: "AT",  2: "V0",  3: "V1",
        4: "A0",  5: "A1",  6: "A2",  7: "A3",
        8: "T0",  9: "T1", 10: "T2", 11: "T3", 12: "T4", 13: "T5", 14: "T6", 15: "T7",
        16: "S0", 17: "S1", 18: "S2", 19: "S3", 20: "S4", 21: "S5", 22: "S6", 23: "S7",
        24: "T8", 25: "T9", 26: "K0", 27: "K1",
        28: "GP", 29: "SP", 30: "FP", 31: "RA"
    ];

    if (r < regNames.length)
        return regNames[r];
    
    return format("$%s", r);
}

string regCop0ToString(Reg r)
{
    // TODO: symbolic names
    return format("$%s", r);
}

string gteDataRegToString(Reg r)
{
    static immutable string[32] regNames = [
        0: "VXY0",  1: "VZ0",   2: "VXY1",  3: "VZ1",   4: "VXY2",  5: "VZ2",
        6: "RGBC",  7: "OTZ",   8: "IR0",   9: "IR1",  10: "IR2",  11: "IR3",
       12: "SXY0", 13: "SXY1", 14: "SXY2", 15: "SXYP", 16: "SZ0",  17: "SZ1",
       18: "SZ2",  19: "SZ3",  20: "RGB0", 21: "RGB1", 22: "RGB2", 24: "MAC0",
       25: "MAC1", 26: "MAC2", 27: "MAC3", 28: "IRGB", 29: "ORGB", 30: "LZCS",
       31: "LZCR"
    ];

    if (r < regNames.length)
        return regNames[r];
    
    return format("$%s", r);
}

string gteControlRegToString(Reg r)
{
    static immutable string[32] regNames = [
        0: "R11R12",  1: "R13R21",   2: "R22R23",  3: "R31R32",   4: "R33",
        5: "TRX",     6: "TRY",      7: "TRZ",
        8: "L11L12",  9: "L13L21",  10: "L22L23", 11: "L31L32",  12: "L33",
       13: "RBK",    14: "GBK",     15: "BBK",
       16: "LR1LR2", 17: "LR3LG1",  18: "LG2LG3", 19: "LB1LB2",
       20: "LB3",    21: "RFC",     22: "GFC",    23: "BFC",
       24: "OFX",    25: "OFY",     26: "H",      27: "DQA",     28: "DQB",
       29: "ZSF3",   30: "ZSF4",    31: "FLAG"
    ];

    if (r < regNames.length)
        return regNames[r];
    
    return format("$%s", r);
}

struct AsmOperand
{
    Reg reg;
    long imm;
    string label;
    AsmOperandType type;
    long offset;
    
    string toString()
    {
        if (type == AsmOperandType.Reg)
            return regToString(reg);
        else if (type == AsmOperandType.RegCop0)
            return regCop0ToString(reg);
        else if (type == AsmOperandType.RegGteData)
            return gteDataRegToString(reg);
        else if (type == AsmOperandType.RegGteControl)
            return gteControlRegToString(reg);
        else if (type == AsmOperandType.Imm)
            return "0x" ~ to!string(imm, 16);
        else if (type == AsmOperandType.Label)
            return label;
        else
            return "none";
    }
}

AsmOperand makeNone()
{
    AsmOperand operand;
    operand.type = AsmOperandType.None;
    return operand;
}

AsmOperand makeReg(ubyte reg)
{
    AsmOperand operand;
    operand.reg = reg;
    operand.type = AsmOperandType.Reg;
    return operand;
}

AsmOperand makeReg(string s)
{
    AsmOperand operand;
    operand.reg = parseReg(s);
    operand.type = AsmOperandType.Reg;
    return operand;
}

AsmOperand makeRegCop0(ubyte reg)
{
    AsmOperand operand;
    operand.reg = reg;
    operand.type = AsmOperandType.RegCop0;
    return operand;
}

AsmOperand makeRegCop0(string s)
{
    AsmOperand operand;
    operand.reg = parseReg(s);
    operand.type = AsmOperandType.RegCop0;
    return operand;
}

AsmOperand makeRegGteData(ubyte reg)
{
    AsmOperand operand;
    operand.reg = reg;
    operand.type = AsmOperandType.RegGteData;
    return operand;
}

AsmOperand makeRegGteData(string s)
{
    AsmOperand operand;
    operand.reg = parseRegGteData(s);
    operand.type = AsmOperandType.RegGteData;
    return operand;
}

AsmOperand makeRegGteControl(ubyte reg)
{
    AsmOperand operand;
    operand.reg = reg;
    operand.type = AsmOperandType.RegGteControl;
    return operand;
}

AsmOperand makeRegGteControl(string s)
{
    AsmOperand operand;
    operand.reg = parseRegGteControl(s);
    operand.type = AsmOperandType.RegGteControl;
    return operand;
}

AsmOperand makeImm(string s)
{
    AsmOperand operand;
    operand.imm = parseInt(s);
    operand.type = AsmOperandType.Imm;
    return operand;
}

AsmOperand makeImm(long imm)
{
    AsmOperand operand;
    operand.imm = imm;
    operand.type = AsmOperandType.Imm;
    return operand;
}

AsmOperand makeLabel(string s)
{
    AsmOperand operand;
    operand.imm = 0xffffffff;
    operand.label = s;
    operand.type = AsmOperandType.Label;
    return operand;
}

struct AsmInstr
{
    Op op;
    AsmOperand operand1;
    AsmOperand operand2;
    AsmOperand operand3;
    size_t line;
    Word[] code; // generated 32-bit words
    size_t offset; // physical offset from the start of the code
}

struct AsmDataEntry
{
    string label;
    ubyte[] data;
}

class Assembly
{
    AsmInstr[] instructions;
    AsmDataEntry[] dataEntries;
    size_t[string] sections;
    size_t[string] dataLabels;
    
    this()
    {
    }
}

Reg parseReg(string s)
{
    s = s.strip.toLower;
    if (s.startsWith("$"))
        s = s[1..$];

    if (s.isNumeric)
        return s.to!ubyte;

    switch (s)
    {
        case "zero", "r0": return R0;
        case "at": return AT;
        case "v0": return V0;
        case "v1": return V1;
        case "a0": return A0;
        case "a1": return A1;
        case "a2": return A2;
        case "a3": return A3;
        case "t0": return T0;
        case "t1": return T1;
        case "t2": return T2;
        case "t3": return T3;
        case "t4": return T4;
        case "t5": return T5;
        case "t6": return T6;
        case "t7": return T7;
        case "s0": return S0;
        case "s1": return S1;
        case "s2": return S2;
        case "s3": return S3;
        case "s4": return S4;
        case "s5": return S5;
        case "s6": return S6;
        case "s7": return S7;
        case "t8": return T8;
        case "t9": return T9;
        case "gp": return GP;
        case "sp": return SP;
        case "fp", "s8": return FP;
        case "ra": return RA;
        
        default: throw new Exception("Unsupported register: " ~ s);
    }
}

Reg parseRegGteData(string s)
{
    s = s.strip.toLower;
    if (s.startsWith("$"))
        s = s[1..$];

    if (s.isNumeric)
        return s.to!ubyte;

    switch (s)
    {
        case "vxy0": return VXY0;
        case "vz0": return VZ0;
        case "vxy1": return VXY1;
        case "vz1": return VZ1;
        case "vxy2": return VXY2;
        case "vz2": return VZ2;
        case "rgbc": return RGBC;
        case "otz": return OTZ;
        case "ir0": return IR0;
        case "ir1": return IR1;
        case "ir2": return IR2;
        case "ir3": return IR3;
        case "sxy0": return SXY0;
        case "sxy1": return SXY1;
        case "sxy2": return SXY2;
        case "sxyp": return SXYP;
        case "sz0": return SZ0;
        case "sz1": return SZ1;
        case "sz2": return SZ2;
        case "sz3": return SZ3;
        case "rgb0": return RGB0;
        case "rgb1": return RGB1;
        case "rgb2": return RGB2;
        case "mac0": return MAC0;
        case "mac1": return MAC1;
        case "mac2": return MAC2;
        case "mac3": return MAC3;
        case "irgb": return IRGB;
        case "orgb": return ORGB;
        case "lzcs": return LZCS;
        case "lzcr": return LZCR;
        
        default: throw new Exception("Unsupported GTE data register: " ~ s);
    }
}

Reg parseRegGteControl(string s)
{
    s = s.strip.toLower;
    if (s.startsWith("$"))
        s = s[1..$];

    if (s.isNumeric)
        return s.to!ubyte;

    switch (s)
    {
        case "r11r12": return R11R12;
        case "r13r21": return R13R21;
        case "r22r23": return R22R23;
        case "r31r32": return R31R32;
        case "r33":    return R33;
        case "trx":    return TRX;
        case "try":    return TRY;
        case "trz":    return TRZ;
        case "l11l12": return L11L12;
        case "l13l21": return L13L21;
        case "l22l23": return L22L23;
        case "l31l32": return L31L32;
        case "l33":    return L33;
        case "rbk":    return RBK;
        case "gbk":    return GBK;
        case "bbk":    return BBK;
        case "lr1lr2": return LR1LR2;
        case "lr3lg1": return LR3LG1;
        case "lg2lg3": return LG2LG3;
        case "lb1lb2": return LB1LB2;
        case "lb3":    return LB3;
        case "rfc":    return RFC;
        case "gfc":    return GFC;
        case "bfc":    return BFC;
        case "ofx":    return OFX;
        case "ofy":    return OFY;
        case "h":      return H;
        case "dqa":    return DQA;
        case "dqb":    return DQB;
        case "zsf3":   return ZSF3;
        case "zsf4":   return ZSF4;
        case "flag":   return FLAG;
        
        default: throw new Exception("Unsupported GTE control register: " ~ s);
    }
}
