/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module lexer;

import std.format: format;
import std.ascii: isAlpha, isAlphaNum, isDigit, isWhite;
import error;
import utils;

enum TK
{
    Eof,
    Ident,
    Num,
    Str,
    Sym
}

struct Token
{
    TK kind;
    string text;
    long num;
    int line;
}

immutable string[] syms2 = [
    "==", "!=", "<=", ">=", "&&", "||", "++", "--",
    "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=", "<<", ">>"
];

immutable string singleSyms = "+-*/%&|^~!<>=(){}[];,";

bool inList(string s, const(string)[] list)
{
    foreach (x; list)
    {
        if (x == s)
            return true;
    }
    return false;
}

bool isReserved(string s)
{
    return inList(s, ["int", "short", "char", "void", "if", "else", "while",
                      "do", "for", "return", "break", "continue"]);
}

Token[] lex(string src)
{
    Token[] toks;
    size_t i = 0;
    int line = 1;

    while (i < src.length)
    {
        char c = src[i];

        if (c == '\n') { line++; i++; continue; }
        if (isWhite(c)) { i++; continue; }

        // Comments
        if (c == '/' && i + 1 < src.length && src[i + 1] == '/')
        {
            while (i < src.length && src[i] != '\n')
                i++;
            continue;
        }
        if (c == '/' && i + 1 < src.length && src[i + 1] == '*')
        {
            int startLine = line;
            i += 2;
            while (i + 1 < src.length && !(src[i] == '*' && src[i + 1] == '/'))
            {
                if (src[i] == '\n')
                    line++;
                i++;
            }
            if (i + 1 >= src.length)
                throw err(startLine, "unterminated comment");
            i += 2;
            continue;
        }

        // Identifiers / keywords
        if (isAlpha(c) || c == '_')
        {
            size_t s = i;
            while (i < src.length && (isAlphaNum(src[i]) || src[i] == '_'))
                i++;
            toks ~= Token(TK.Ident, src[s .. i], 0, line);
            continue;
        }

        // Numbers (decimal, 0x.., 0b..)
        if (isDigit(c))
        {
            size_t s = i;
            while (i < src.length && isAlphaNum(src[i]))
                i++;
            string t = src[s .. i];
            long v = 0;
            try
                v = parseInt(t);
            catch (Exception ex)
                throw err(line, "bad number '" ~ t ~ "'");
            toks ~= Token(TK.Num, t, cast(int) v, line);
            continue;
        }

        // Character literal
        if (c == '\'')
        {
            i++;
            size_t s = i;
            while (i < src.length && src[i] != '\'')
            {
                if (src[i] == '\\')
                    i++;
                i++;
            }
            if (i >= src.length)
                throw err(line, "unterminated character literal");
            string body_ = src[s .. i];
            i++;
            ubyte[] b = parseEscapes(body_);
            if (b.length != 1)
                throw err(line, "bad character literal");
            toks ~= Token(TK.Num, body_, b[0], line);
            continue;
        }

        // String literal (text kept raw; escapes are decoded when emitted)
        if (c == '"')
        {
            i++;
            size_t s = i;
            while (i < src.length && src[i] != '"')
            {
                if (src[i] == '\n')
                    throw err(line, "newline in string literal");
                if (src[i] == '\\')
                    i++;
                i++;
            }
            if (i >= src.length)
                throw err(line, "unterminated string literal");
            toks ~= Token(TK.Str, src[s .. i], 0, line);
            i++;
            continue;
        }

        // Operators / punctuation
        string sym;
        if (i + 3 <= src.length && (src[i .. i + 3] == "<<=" || src[i .. i + 3] == ">>="))
            sym = src[i .. i + 3];
        else if (i + 2 <= src.length && inList(src[i .. i + 2], syms2))
            sym = src[i .. i + 2];
        else
        {
            foreach (ch; singleSyms)
            {
                if (ch == c)
                {
                    sym = src[i .. i + 1];
                    break;
                }
            }
        }
        if (sym.length == 0)
            throw err(line, format("unexpected character '%s'", c));
        toks ~= Token(TK.Sym, sym, 0, line);
        i += sym.length;
    }

    toks ~= Token(TK.Eof, "<end of file>", 0, line);
    return toks;
}
