/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module lexer;

import std.format: format;
import std.ascii: isAlpha, isAlphaNum, isDigit, isWhite;
import std.file: readText, exists;
import std.path: dirName, buildPath, buildNormalizedPath, absolutePath;
import error;
import utils;

enum TK
{
    Eof,
    Ident,
    Num,
    Str,
    Sym
}

struct Token
{
    TK kind;
    string text;
    long num;
    int line;
    
    /// Num: unsigned literal
    bool uns;
    
    /// Source file (for error messages)
    string file;
}

immutable string[] syms2 = [
    "==", "!=", "<=", ">=", "&&", "||", "++", "--",
    "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=", "<<", ">>", "->"
];

immutable string singleSyms = "+-*/%&|^~!<>=(){}[];,.@#";

bool inList(string s, const(string)[] list)
{
    foreach (x; list)
    {
        if (x == s)
            return true;
    }
    return false;
}

bool isReserved(string s)
{
    return inList(s, [
        "int", "short", "char", "void", "uint", "ushort", "uchar", "unsigned",
        "struct", "sizeof", "macro",
        "if", "else", "while", "do", "for", "return", "break", "continue"
    ]);
}

/// Lexes a file and runs the preprocessing pass.
Token[] lex(string src, string path = "")
{
    Token[][string] macros;
    bool[string] including;
    if (path.length)
        including[buildNormalizedPath(absolutePath(path))] = true;

    Token[] toks = lexRaw(src, path);
    int lastLine = toks[$ - 1].line;

    Token[] res = preprocess(toks, path, macros, including);
    res ~= Token(TK.Eof, "<end of file>", 0, lastLine, false, path);
    return res;
}

private Token[] lexRaw(string src, string file)
{
    Token[] toks;
    size_t i = 0;
    int line = 1;

    while (i < src.length)
    {
        char c = src[i];

        if (c == '\n') { line++; i++; continue; }
        if (isWhite(c)) { i++; continue; }

        // Comments
        if (c == '/' && i + 1 < src.length && src[i + 1] == '/')
        {
            while (i < src.length && src[i] != '\n')
                i++;
            continue;
        }
        if (c == '/' && i + 1 < src.length && src[i + 1] == '*')
        {
            int startLine = line;
            i += 2;
            while (i + 1 < src.length && !(src[i] == '*' && src[i + 1] == '/'))
            {
                if (src[i] == '\n')
                    line++;
                i++;
            }
            if (i + 1 >= src.length)
                throw err(file, startLine, "unterminated comment");
            i += 2;
            continue;
        }

        // Identifiers / keywords
        if (isAlpha(c) || c == '_')
        {
            size_t s = i;
            while (i < src.length && (isAlphaNum(src[i]) || src[i] == '_'))
                i++;
            toks ~= Token(TK.Ident, src[s .. i], 0, line);
            continue;
        }

        // Numbers (decimal, 0x.., 0b..)
        if (isDigit(c))
        {
            size_t s = i;
            while (i < src.length && isAlphaNum(src[i]))
                i++;
            string t = src[s .. i];
            bool uns = false;
            if (t.length > 1 && (t[$ - 1] == 'u' || t[$ - 1] == 'U'))
            {
                uns = true;
                t = t[0 .. $ - 1];
            }
            long v = 0;
            try
                v = parseInt(t);
            catch (Exception ex)
                throw err(file, line, "bad number '" ~ t ~ "'");
            if (v > 0xFFFFFFFFL)
                throw err(file, line, "number too large for 32 bits: " ~ t);
            if (v > 0x7FFFFFFFL)
                uns = true;
            toks ~= Token(TK.Num, t, cast(int) v, line, uns);
            continue;
        }

        // Character literal
        if (c == '\'')
        {
            i++;
            size_t s = i;
            while (i < src.length && src[i] != '\'')
            {
                if (src[i] == '\\')
                    i++;
                i++;
            }
            if (i >= src.length)
                throw err(file, line, "unterminated character literal");
            string body_ = src[s .. i];
            i++;
            ubyte[] b = parseEscapes(body_);
            if (b.length != 1)
                throw err(file, line, "bad character literal");
            toks ~= Token(TK.Num, body_, b[0], line);
            continue;
        }

        // String literal (text kept raw; escapes are decoded when emitted)
        if (c == '"')
        {
            i++;
            size_t s = i;
            while (i < src.length && src[i] != '"')
            {
                if (src[i] == '\n')
                    throw err(file, line, "newline in string literal");
                if (src[i] == '\\')
                    i++;
                i++;
            }
            if (i >= src.length)
                throw err(file, line, "unterminated string literal");
            toks ~= Token(TK.Str, src[s .. i], 0, line);
            i++;
            continue;
        }

        // Operators / punctuation
        string sym;
        if (i + 3 <= src.length && (src[i .. i + 3] == "<<=" || src[i .. i + 3] == ">>="))
            sym = src[i .. i + 3];
        else if (i + 2 <= src.length && inList(src[i .. i + 2], syms2))
            sym = src[i .. i + 2];
        else
        {
            foreach (ch; singleSyms)
            {
                if (ch == c)
                {
                    sym = src[i .. i + 1];
                    break;
                }
            }
        }
        if (sym.length == 0)
            throw err(file, line, format("unexpected character '%s'", c));
        toks ~= Token(TK.Sym, sym, 0, line);
        i += sym.length;
    }
    
    toks ~= Token(TK.Eof, "<end of file>", 0, line);
    foreach (ref t; toks)
        t.file = file;
    return toks;
}

private Token[] preprocess(
    Token[] toks,
    string path,
    ref Token[][string] macros,
    ref bool[string] including)
{
    Token[] res;
    size_t i = 0;

    while (i < toks.length)
    {
        Token t = toks[i];
        if (t.kind == TK.Eof)
            break;

        // A token is first on its line if the previous token is on a different line
        bool bol = (i == 0) || toks[i - 1].line != t.line;

        if (bol && t.kind == TK.Sym && t.text == "#")
        {
            // A directive occupies the rest of the line
            size_t end = i + 1;
            while (end < toks.length && toks[end].kind != TK.Eof && toks[end].line == t.line)
                end++;
            Token[] d = toks[i + 1 .. end];

            if (d.length == 0 || d[0].kind != TK.Ident)
                throw err(path, t.line, "expected directive name after '#'");

            switch (d[0].text)
            {
                case "define":
                    if (d.length < 2 || d[1].kind != TK.Ident)
                        throw err(path, t.line, "#define needs a name");
                    macros[d[1].text] = d[2 .. $].dup;   // body is already tokenized
                    break;

                case "undef":
                    if (d.length != 2 || d[1].kind != TK.Ident)
                        throw err(path, t.line, "#undef needs a name");
                    macros.remove(d[1].text);
                    break;

                case "include":
                    if (d.length != 2 || d[1].kind != TK.Str)
                        throw err(path, t.line, "#include needs a quoted file name");

                    string name = d[1].text;
                    string full = path.length ? buildPath(dirName(path), name) : name;
                    if (!exists(full))
                        throw err(path, t.line, "can't find file \"" ~ name ~ "\"");

                    string norm = buildNormalizedPath(absolutePath(full));
                    if (norm in including)
                        throw err(path, t.line, "circular include of \"" ~ name ~ "\"");

                    including[norm] = true;
                    res ~= preprocess(lexRaw(readText(full), full), full, macros, including);
                    including.remove(norm);
                    break;

                default:
                    throw err(path, t.line, "unknown directive '#" ~ d[0].text ~ "'");
            }

            i = end;
            continue;
        }

        if (t.kind == TK.Ident && t.text in macros)
        {
            bool[string] active;
            active[t.text] = true;
            res ~= expand(t, macros, active);
        }
        else
            res ~= t;

        i++;
    }

    return res;
}

/// Expands a macro use into tokens. `active` stops recursion like `#define X X + 1`.
private Token[] expand(Token use, Token[][string] macros, ref bool[string] active)
{
    Token[] res;
    foreach (bt; macros[use.text])
    {
        Token t = bt;
        t.line = use.line;    // errors point at the use site
        t.file = use.file;

        if (t.kind == TK.Ident && t.text in macros && t.text !in active)
        {
            active[t.text] = true;
            res ~= expand(t, macros, active);
            active.remove(t.text);
        }
        else
            res ~= t;
    }
    return res;
}
