/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module linker;

import std.stdio;

import mips;
import ir;
import psxexe;
import utils;

bool link(Assembly ass, bool verbose, ref ubyte[] executableCode)
{
    // Generate machine words for each instruction
    size_t codeSize = 0;
    foreach(pos, ref ins; ass.instructions)
    {
        switch(ins.op)
        {
            case Op.NOP: ins.code = [opNop]; break;
            
            case Op.ADD: ins.code = [opAdd(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.ADDU: ins.code = [opAddu(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.ADDI: ins.code = [opAddi(ins.operand1.reg, ins.operand2.reg, cast(short)ins.operand3.imm)]; break;
            case Op.ADDIU: ins.code = [opAddiu(ins.operand1.reg, ins.operand2.reg, cast(short)ins.operand3.imm)]; break;
            case Op.SUB: ins.code = [opSub(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.SUBU: ins.code = [opSubu(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.MULT: ins.code = [opMult(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.MULTU: ins.code = [opMultu(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.DIV: ins.code = [opDiv(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.DIVU: ins.code = [opDivu(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.MFLO: ins.code = [opMflo(ins.operand1.reg)]; break;
            case Op.MFHI: ins.code = [opMfhi(ins.operand1.reg)]; break;
            case Op.MTLO: ins.code = [opMtlo(ins.operand1.reg)]; break;
            case Op.MTHI: ins.code = [opMthi(ins.operand1.reg)]; break;
            
            case Op.LI: ins.code = opLi(ins.operand1.reg, ins.operand2.imm); break;
            case Op.MOVE: ins.code = [opMove(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.CLEAR: ins.code = [opClear(ins.operand1.reg)]; break;
            case Op.NEG: ins.code = [opNeg(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.NOT: ins.code = [opNot(ins.operand1.reg, ins.operand2.reg)]; break;
            
            case Op.J: ins.code = [opJ(cast(uint)ins.operand1.imm)]; break;
            case Op.JR: ins.code = [opJr(ins.operand1.reg)]; break;
            case Op.JAL: ins.code = [opJal(cast(uint)ins.operand1.imm)]; break;
            case Op.JALR: ins.code = [opJalr(ins.operand1.reg, ins.operand2.reg)]; break;
            
            case Op.SLT: ins.code = [opSlt(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.SLTI: ins.code = [opSlti(ins.operand1.reg, ins.operand2.reg, cast(short)ins.operand3.imm)]; break;
            case Op.SLTU: ins.code = [opSltu(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.SLTIU: ins.code = [opSltiu(ins.operand1.reg, ins.operand2.reg, cast(short)ins.operand3.imm)]; break;
            
            case Op.AND: ins.code = [opAnd(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.ANDI: ins.code = [opAndi(ins.operand1.reg, ins.operand2.reg, cast(short)ins.operand3.imm)]; break;
            case Op.OR: ins.code = [opOr(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.ORI: ins.code = [opOri(ins.operand1.reg, ins.operand2.reg, cast(short)ins.operand3.imm)]; break;
            case Op.XOR: ins.code = [opXor(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.XORI: ins.code = [opXori(ins.operand1.reg, ins.operand2.reg, cast(short)ins.operand3.imm)]; break;
            case Op.NOR: ins.code = [opNor(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.SLL: ins.code = [opSll(ins.operand1.reg, ins.operand2.reg, cast(ubyte)ins.operand3.imm)]; break;
            case Op.SLLV: ins.code = [opSllv(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.SRL: ins.code = [opSrl(ins.operand1.reg, ins.operand2.reg, cast(ubyte)ins.operand3.imm)]; break;
            case Op.SRLV: ins.code = [opSrlv(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            case Op.SRA: ins.code = [opSra(ins.operand1.reg, ins.operand2.reg, cast(ubyte)ins.operand3.imm)]; break;
            case Op.SRAV: ins.code = [opSrav(ins.operand1.reg, ins.operand2.reg, ins.operand3.reg)]; break;
            
            case Op.LUI: ins.code = [opLui(ins.operand1.reg, cast(short)ins.operand2.imm)]; break;
            
            case Op.LW: ins.code = [opLw(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            case Op.LH: ins.code = [opLh(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            case Op.LHU: ins.code = [opLhu(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            case Op.LB: ins.code = [opLb(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            case Op.LBU: ins.code = [opLbu(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            case Op.LWL: ins.code = [opLwl(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            case Op.LWR: ins.code = [opLwr(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            case Op.SW: ins.code = [opSw(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            case Op.SH: ins.code = [opSh(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            case Op.SB: ins.code = [opSb(ins.operand1.reg, cast(short)ins.operand2.imm, ins.operand3.reg)]; break;
            
            case Op.BEQ: ins.code = [opBeq(ins.operand1.reg, ins.operand2.reg, cast(short)ins.operand3.imm)]; break;
            case Op.BNE: ins.code = [opBne(ins.operand1.reg, ins.operand2.reg, cast(short)ins.operand3.imm)]; break;
            case Op.BLEZ: ins.code = [opBlez(ins.operand1.reg, cast(short)ins.operand2.imm)]; break;
            case Op.BGTZ: ins.code = [opBgtz(ins.operand1.reg, cast(short)ins.operand2.imm)]; break;
            case Op.BGEZ: ins.code = [opBgez(ins.operand1.reg, cast(short)ins.operand2.imm)]; break;
            case Op.BLTZ: ins.code = [opBltz(ins.operand1.reg, cast(short)ins.operand2.imm)]; break;
            case Op.BGEZAL: ins.code = [opBgezal(ins.operand1.reg, cast(short)ins.operand2.imm)]; break;
            case Op.BLTZAL: ins.code = [opBltzal(ins.operand1.reg, cast(short)ins.operand2.imm)]; break;
            
            case Op.SYSCALL: ins.code = [opSyscall(cast(uint)ins.operand1.imm)]; break;
            case Op.BREAK: ins.code = [opBreak(cast(uint)ins.operand1.imm)]; break;
            
            case Op.MTC0: ins.code = [opMtc0(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.MFC0: ins.code = [opMfc0(ins.operand1.reg, ins.operand2.reg)]; break;
            
            case Op.MTC2: ins.code = [opMtc2(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.MFC2: ins.code = [opMfc2(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.CTC2: ins.code = [opCtc2(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.CFC2: ins.code = [opCfc2(ins.operand1.reg, ins.operand2.reg)]; break;
            case Op.COP2: ins.code = [opCop2(cast(uint)ins.operand1.imm)]; break;
            
            case Op.RTPS: ins.code = [opRtps()]; break;
            case Op.RTPT: ins.code = [opRtpt()]; break;
            
            // TODO: other GTE instructions
            
            default: break;
        }
        
        ins.offset = codeSize;
        
        codeSize += ins.code.length * Word.sizeof;
    }
    
    if (verbose)
        writefln("Code size: %s byte(s)", codeSize);
    
    if (verbose)
        writeln("\nData entries:");
    
    // Generate absolute addresses for data labels
    uint[string] dataLabelAddrs;
    ubyte[] data;
    uint dataStartAddr = relocate(codeSize);
    uint offset = dataStartAddr;
    
    foreach(i, entry; ass.dataEntries)
    {
        dataLabelAddrs[entry.label] = offset;
        uint size = cast(uint)entry.data.length;
        uint alignedSize = size.aligned(4);
        if (verbose)
            writefln("%s: 0x%08X %s byte(s) (%s bytes aligned) %s", entry.label, offset, size, alignedSize, entry.data);
        
        offset += alignedSize;
        data ~= entry.data;
        size_t paddingSize = alignedSize - size;
        if (paddingSize > 0)
        {
            data ~= new ubyte[paddingSize];
        }
    }
    
    if (verbose)
        writeln("\nSections:");
    
    foreach(name, instrIndex; ass.sections)
    {
        auto relativeOffset = ass.instructions[instrIndex].offset;
        auto globalOffset = relocate(relativeOffset);
        if (verbose)
            writefln("%s: 0x%08X", name, globalOffset);
        dataLabelAddrs[name] = globalOffset;
    }

    // Generate machine code
    if (verbose)
        writeln("\nProgram code:");
    
    ubyte[] code;
    
    foreach(pos, ref ins; ass.instructions)
    {
        if (ins.op == Op.LI)
        {
            if (ins.operand2.type == AsmOperandType.Label)
            {
                if (ins.operand2.label in dataLabelAddrs)
                {
                    ins.operand2.imm = dataLabelAddrs[ins.operand2.label];
                    ins.operand2.type = AsmOperandType.Imm;
                }
                else
                {
                    writefln("Error: undefined label \"%s\"", ins.operand2.label);
                    return false;
                }
            }
            code ~= enc(opLi(ins.operand1.reg, ins.operand2.imm));
        }
        else if (ins.op == Op.J)
        {
            if (ins.operand1.type == AsmOperandType.Label)
            {
                if (ins.operand1.label in dataLabelAddrs)
                {
                    ins.operand1.imm = dataLabelAddrs[ins.operand1.label];
                    ins.operand1.type = AsmOperandType.Imm;
                }
                else
                {
                    writefln("Error: undefined label \"%s\"", ins.operand1.label);
                    return false;
                }
            }
            code ~= enc(opJ(cast(uint)ins.operand1.imm));
        }
        else if (ins.op == Op.JAL)
        {
            if (ins.operand1.type == AsmOperandType.Label)
            {
                if (ins.operand1.label in dataLabelAddrs)
                {
                    ins.operand1.imm = dataLabelAddrs[ins.operand1.label];
                    ins.operand1.type = AsmOperandType.Imm;
                }
                else
                {
                    writefln("Error: undefined label \"%s\"", ins.operand1.label);
                    return false;
                }
            }
            code ~= enc(opJal(cast(uint)ins.operand1.imm));
        }
        /*
        else if (ins.op == Op.BEQ || ins.op == Op.BNE)
        {
            if (ins.operand3.type == AsmOperandType.Label)
            {
                if (ins.operand3.label in dataLabelAddrs)
                {
                    uint targetAddr = dataLabelAddrs[ins.operand3.label];
                    uint currentPC = relocate(ins.offset);
                    int offsetInWords = (cast(int)targetAddr - (cast(int)currentPC + 4)) / 4;
                    ins.operand3.imm = cast(short)offsetInWords;
                    ins.operand3.type = AsmOperandType.Imm;
                    if (ins.op == Op.BEQ)
                        ins.code = [opBeq(ins.operand1.reg, ins.operand2.reg, cast(short)offsetInWords)];
                    else
                        ins.code = [opBne(ins.operand1.reg, ins.operand2.reg, cast(short)offsetInWords)];
                }
                else
                {
                    writefln("Error: undefined label \"%s\"", ins.operand3.label);
                    return false;
                }
            }
            code ~= enc(ins.code);
        }
        // TODO: linking for other opcodes
        else
        {
            code ~= enc(ins.code);
        }
        */
        else if (ins.op == Op.BEQ || ins.op == Op.BNE)
        {
            if (ins.operand3.type == AsmOperandType.Label)
            {
                short off;
                if (!resolveBranch(dataLabelAddrs, ins, ins.operand3, off))
                    return false;
                ins.code = [ins.op == Op.BEQ
                    ? opBeq(ins.operand1.reg, ins.operand2.reg, off)
                    : opBne(ins.operand1.reg, ins.operand2.reg, off)];
            }
            code ~= enc(ins.code);
        }
        else if (ins.op == Op.BLEZ || ins.op == Op.BGTZ || ins.op == Op.BGEZ ||
                 ins.op == Op.BLTZ || ins.op == Op.BGEZAL || ins.op == Op.BLTZAL)
        {
            // one-register branches: the label is in operand2
            if (ins.operand2.type == AsmOperandType.Label)
            {
                short off;
                if (!resolveBranch(dataLabelAddrs, ins, ins.operand2, off))
                    return false;
                Reg rs = ins.operand1.reg;
                switch (ins.op)
                {
                    case Op.BLEZ:   ins.code = [opBlez(rs, off)]; break;
                    case Op.BGTZ:   ins.code = [opBgtz(rs, off)]; break;
                    case Op.BGEZ:   ins.code = [opBgez(rs, off)]; break;
                    case Op.BLTZ:   ins.code = [opBltz(rs, off)]; break;
                    case Op.BGEZAL: ins.code = [opBgezal(rs, off)]; break;
                    case Op.BLTZAL: ins.code = [opBltzal(rs, off)]; break;
                    default: assert(0);
                }
            }
            code ~= enc(ins.code);
        }
        else
        {
            if (ins.code.length == 0)
            {
                writefln("Error: instruction %s is not implemented in the linker (line %s)", ins.op, ins.line);
                return false;
            }
            code ~= enc(ins.code);
        }
        
        if (verbose)
            writefln("[0x%08X] %s %s, %s, %s", relocate(ins.offset), ins.op, ins.operand1, ins.operand2, ins.operand3);
    }
    
    if (verbose)
        writefln("[0x%08X] DATA\n", dataStartAddr);
    
    if (verbose)
        writefln("Stack: 0x%08X", STACK_ADDR);
    
    code ~= data;
    
    executableCode = code;
    
    return true;
}

// Resolves a branch label to a word offset relative to the delay slot.
// On success the operand is rewritten as an immediate.
bool resolveBranch(uint[string] dataLabelAddrs, ref AsmInstr ins, ref AsmOperand target, out short off)
{
    auto p = target.label in dataLabelAddrs;
    if (p is null)
    {
        writefln("Error: undefined label \"%s\"", target.label);
        return false;
    }

    int words = (cast(int)*p - (cast(int)relocate(ins.offset) + 4)) / 4;
    if (words < short.min || words > short.max)
    {
        writefln("Error: branch to \"%s\" is out of range (%s instructions)", target.label, words);
        return false;
    }

    off = cast(short)words;
    target.imm = off;
    target.type = AsmOperandType.Imm;
    return true;
}
