/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * AST macro expansion.
 *
 * A macro body is parsed once, at definition time, into ordinary AST nodes in which
 * the macro parameters appear as plain variable references. Expanding a macro
 * deep-copies its body, replacing every reference to a parameter with a copy of the
 * argument expression. An argument is re-evaluated at every place where it is used.
 * Variables declared inside a macro body get a unique name per expansion,
 * so they can never capture or shadow variables used by the arguments.
 * When inlining performance-critical code, pass plain variables or constants into
 * macros, never expressions like *p or a[i++]. If a macro needs an argument more than
 * once, copy it into a macro-local first.
 */
module macroexp;

import std.format: format;

import ast;
import error;

private int macroCounter;

/// State of one expansion (or of a plain copy when no substitution is needed).
class MacroSubst
{
    Expr[string] args;        // parameter name -> argument (null: not provided)
    string[string] renames;   // body-local variable -> unique name
    string macroName;
    string file;              // use site: copied nodes report errors here
    int line;
}

/// Context that only moves copied nodes to a use site (no substitution).
MacroSubst useSiteCtx(string file, int line)
{
    auto ctx = new MacroSubst();
    ctx.file = file;
    ctx.line = line;
    return ctx;
}

/// Collects the names of all variables declared in a statement tree.
void collectDecls(Stmt s, ref string[] names)
{
    if (s is null)
        return;
    if (s.kind == SK.Decl)
        names ~= s.name;
    foreach (c; s.stmts)
        collectDecls(c, names);
    collectDecls(s.forInit, names);
    collectDecls(s.thenS, names);
    collectDecls(s.elseS, names);
}

/**
 * Deep copy of an expression. With ctx == null the copy is exact (this is used for
 * arguments, which must not be substituted again). Otherwise parameters are replaced,
 * body locals are renamed and node positions are set to the use site.
 */
Expr cloneExpr(Expr e, MacroSubst ctx)
{
    if (e is null)
        return null;

    if (ctx !is null)
    {
        if (e.kind == EK.Var)
        {
            if (auto pa = e.name in ctx.args)
            {
                if (*pa is null)
                    throw err(ctx.file, ctx.line,
                        format("macro \"%s\": no argument was given for parameter \"%s\"",
                               ctx.macroName, e.name));
                return cloneExpr(*pa, null);
            }
        }
        else if (e.kind == EK.Call && (e.name in ctx.args) !is null)
        {
            throw err(ctx.file, ctx.line,
                format("macro \"%s\": parameter \"%s\" is an expression and cannot be called",
                       ctx.macroName, e.name));
        }
    }

    auto n = new Expr(e.kind,
                      ctx !is null ? ctx.file : e.file,
                      ctx !is null ? ctx.line : e.line);
    n.op = e.op;
    n.name = e.name;
    if (ctx !is null && e.kind == EK.Var)
    {
        if (auto pr = e.name in ctx.renames)
            n.name = *pr;
    }
    n.num = e.num;
    n.a = cloneExpr(e.a, ctx);
    n.b = cloneExpr(e.b, ctx);
    foreach (x; e.args)
        n.args ~= cloneExpr(x, ctx);
    n.ty = e.ty;
    n.post = e.post;
    n.uns = e.uns;
    n.arrow = e.arrow;
    return n;
}

/// Deep copy of a statement, see cloneExpr.
Stmt cloneStmt(Stmt s, MacroSubst ctx)
{
    if (s is null)
        return null;

    auto n = new Stmt(s.kind,
                      ctx !is null ? ctx.file : s.file,
                      ctx !is null ? ctx.line : s.line);
    foreach (c; s.stmts)
        n.stmts ~= cloneStmt(c, ctx);
    n.scoped = s.scoped;
    n.e = cloneExpr(s.e, ctx);
    n.step = cloneExpr(s.step, ctx);
    n.forInit = cloneStmt(s.forInit, ctx);
    n.thenS = cloneStmt(s.thenS, ctx);
    n.elseS = cloneStmt(s.elseS, ctx);
    n.ty = s.ty;
    n.name = s.name;
    if (ctx !is null && s.kind == SK.Decl)
    {
        if (auto pr = s.name in ctx.renames)
            n.name = *pr;
    }
    n.arrLen = s.arrLen;
    return n;
}

private MacroSubst makeCtx(Macro m, Expr[] args, string file, int line)
{
    if (args.length > m.params.length)
        throw err(file, line,
            format("macro \"%s\" takes at most %s argument(s) but %s given",
                   m.name, m.params.length, args.length));

    auto ctx = new MacroSubst();
    ctx.macroName = m.name;
    ctx.file = file;
    ctx.line = line;

    // Missing trailing arguments are allowed; it is an error only if the body uses them.
    foreach (i, pn; m.params)
        ctx.args[pn] = (i < args.length) ? args[i] : null;

    int id = ++macroCounter;
    foreach (ln; m.locals)
        ctx.renames[ln] = format("%s.%s", ln, id);

    return ctx;
}

/// Expands a statement macro into a (scoped) block.
Stmt expandStmtMacro(Macro m, Expr[] args, string file, int line)
{
    return cloneStmt(m.body_, makeCtx(m, args, file, line));
}

/// Expands an expression macro (constant, or one with parameters).
Expr expandExprMacro(Macro m, Expr[] args, string file, int line)
{
    return cloneExpr(m.expr, makeCtx(m, args, file, line));
}
