/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module main;

import std.stdio;
import std.file: write, readText;
import std.bitmanip;
import std.path;
import std.getopt;

import mips;
import ir;
import psxexe;
import utils;
import assembler;
import preprocessor;
import compiler;
import linker;

int main(string[] args)
{
    string outputFile = "PSX.EXE";

    try
    {
        auto helpInformation = getopt(
            args,
            "output|o", "Output file name (default is PSX.EXE)", &outputFile
        );

        if (helpInformation.helpWanted) {
            defaultGetoptPrinter("Usage: rlc [options] <input_file>", helpInformation.options);
            return 0;
        }
    } 
    catch (GetOptException e)
    {
        stderr.writefln("Arguments error: %s", e.msg);
        return 1;
    }

    if (args.length < 2)
    {
        stderr.writeln("Ошибка: Не указан входной файл.");
        stderr.writeln("Использование: rlc [options] <input_file>");
        return 1;
    }

    string filename = args[1];
    string sourceCode;

    try
    {
        sourceCode = readText(filename);
    } 
    catch (Exception e)
    {
        stderr.writefln("Error reading file %s: %s", filename, e.msg);
        return 1;
    }

    Assembly ass;
    string ext = extension(filename);

    if (ext == ".s")
    {
        writefln("Assembling %s...", filename);
        ass = parseAsm(sourceCode);
    } 
    else if (ext == ".r")
    {
        writefln("Compiling %s...", filename);
        string processedCode = preprocess(sourceCode, filename);
        if (processedCode.length > 0)
            ass = compile(processedCode);
        else
            return 1;
    } 
    else
    {
        stderr.writefln("Unknown extension of %s", filename);
        return 1;
    }

    writeln("Linking...");
    ubyte[] exeCode;
    if (!link(ass, false, exeCode)) return 1;

    // Generate PS-X EXE and save to file
    writefln("Generating executable (%s)...", outputFile);
    PsxExe exe = new PsxExe(exeCode, 0);
    
    write(outputFile, exe.binary); 
    
    writeln("Success!");
    return 0;
}
