/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * MIPS R3000 instruction set.
 */
module mips;

import utils;

alias Word = uint;
alias Reg = ubyte;

enum Op
{
    // CPU opcode enums
    NOP, WORD,
    SLL, SRL, SRA, SLLV, SRLV, SRAV,
    J, JAL, JR, JALR,
    SYSCALL, BREAK,
    MFHI, MTHI, MFLO, MTLO,
    MULT, MULTU, DIV, DIVU,
    ADD, ADDU, SUB, SUBU,
    ADDI, ADDIU,
    AND, OR, XOR, NOR,
    ANDI, ORI, XORI,
    SLT, SLTU,
    SLTI, SLTIU,
    LUI, LB, LH, LWL, LW, LBU, LHU, LWR,
    SB, SH, SWL, SW, SWR,
    LI, MOVE, CLEAR, NEG, NOT,
    BEQ, BNE, BLEZ, BGTZ, BGEZ, BLTZ, BGEZAL, BLTZAL,
    LWC0, LWC1, LWC2, LWC3,
    SWC0, SWC1, SWC2, SWC3,
    MTC0, MFC0, RFE,
    MTC2, MFC2, CTC2, CFC2,
    COP2,
    
    // GTE opcode enums
    RTPS, RTPT, MVMVA, DCPL, DPCS, DPCT,
    INTPL, SQR, NCS, NCT, NCDS, NCDT,
    NCCS, NCCT, CDP, CC, NCLIP,
    AVSZ3, AVSZ4, OP, GPF, GPL
}

// CPU registers
enum: Reg
{
    R0   = 0,
    AT   = 1,
    
    V0   = 2,
    V1   = 3,
    
    A0   = 4,
    A1   = 5,
    A2   = 6,
    A3   = 7,
    
    T0   = 8,
    T1   = 9,
    T2   = 10,
    T3   = 11,
    T4   = 12,
    T5   = 13,
    T6   = 14,
    T7   = 15,
    
    S0   = 16,
    S1   = 17,
    S2   = 18,
    S3   = 19,
    S4   = 20,
    S5   = 21,
    S6   = 22,
    S7   = 23,
    
    T8   = 24,
    T9   = 25,
    
    K0   = 26,
    K1   = 27,
    
    GP   = 28,
    SP   = 29,
    FP   = 30,
    
    RA   = 31
}

// GTE data registers
enum: Reg
{
    VXY0 = 0,  // Vector0 X and Y, 2 packed signed 16-bit integers
    VZ0  = 1,  // Vector0 Z, signed 16-bit integer
    VXY1 = 2,  // Vector1 X and Y, 2 packed signed 16-bit integers
    VZ1  = 3,  // Vector1 Z, signed 16-bit integer
    VXY2 = 4,  // Vector2 X and Y, 2 packed signed 16-bit integers
    VZ2  = 5,  // Vector2 Z, signed 16-bit integer
    RGBC = 6,  // Color/code value, 4 packed unsigned bytes
    OTZ  = 7,  // Average Z value (for Ordering Table), unsigned 16-bit integer
    IR0  = 8,  // 16-bit Accumulator (Interpolate), signed 16-bit integer
    IR1  = 9,  // 16-bit Accumulator (Vector X), signed 16-bit integer
    IR2  = 10, // 16-bit Accumulator (Vector Y), signed 16-bit integer
    IR3  = 11, // 16-bit Accumulator (Vector Z), signed 16-bit integer
    SXY0 = 12, // Screen XY-coordinate FIFO stage1, 2 packed signed 16-bit integers
    SXY1 = 13, // Screen XY-coordinate FIFO stage2, 2 packed signed 16-bit integers
    SXY2 = 14, // Screen XY-coordinate FIFO stage3, 2 packed signed 16-bit integers
    SXYP = 15, // Screen XY-coordinate FIFO stage4, 2 packed signed 16-bit integers
    SZ0  = 16, // Screen Z-coordinate FIFO stage1, unsigned 16-bit integer
    SZ1  = 17, // Screen Z-coordinate FIFO stage2, unsigned 16-bit integer
    SZ2  = 18, // Screen Z-coordinate FIFO stage3, unsigned 16-bit integer
    SZ3  = 19, // Screen Z-coordinate FIFO stage4, unsigned 16-bit integer
    RGB0 = 20, // Color CRGB-code/color FIFO stage1, 4 packed unsigned bytes
    RGB1 = 21, // Color CRGB-code/color FIFO stage2, 4 packed unsigned bytes
    RGB2 = 22, // Color CRGB-code/color FIFO stage3, 4 packed unsigned bytes
    // $23 is undefined/prohibited
    MAC0 = 24, // 32bit Maths Accumulators (Value), signed 32-bit integer
    MAC1 = 25, // 32bit Maths Accumulators (Vector X), signed 32-bit integer
    MAC2 = 26, // 32bit Maths Accumulators (Vector Y), signed 32-bit integer
    MAC3 = 27, // 32bit Maths Accumulators (Vector Z), signed 32-bit integer
    IRGB = 28, // Convert RGB Color (48bit vs 15bit), unsigned 16-bit integer
    ORGB = 29, // 
    LZCS = 30, // Count Leading-Zeroes/Ones (sign bits), 2 packed signed 32-bit integers
    LZCR = 31  // Count Leading-Zeroes/Ones (sign bits), 2 packed signed 32-bit integers
}

// GTE control registers
enum: Reg
{
    R11R12 = 0,  // Rotation matrix 3x3 (r11, r12), 2 signed 16-bit integers
    R13R21 = 1,  // Rotation matrix 3x3 (r13, r21), 2 signed 16-bit integers
    R22R23 = 2,  // Rotation matrix 3x3 (r22, r23), 2 signed 16-bit integers
    R31R32 = 3,  // Rotation matrix 3x3 (r31, r32), 2 signed 16-bit integers
    R33    = 4,  // Rotation matrix 3x3 (r33), signed 16-bit integer
    TRX    = 5,  // Translation vector X, signed 32-bit integer
    TRY    = 6,  // Translation vector Y, signed 32-bit integer
    TRZ    = 7,  // Translation vector Z, signed 32-bit integer
    L11L12 = 8,  // Light source matrix 3x3 (l11, l12), 2 signed 16-bit integers
    L13L21 = 9,  // Light source matrix 3x3 (l13, l21), 2 signed 16-bit integers
    L22L23 = 10, // Light source matrix 3x3 (l22, l23), 2 signed 16-bit integers
    L31L32 = 11, // Light source matrix 3x3 (l31, l32), 2 signed 16-bit integers
    L33    = 12, // Light source matrix 3x3 (l33), signed 16-bit integer
    RBK    = 13, // Background color R, unsigned 32-bit integer
    GBK    = 14, // Background color G, unsigned 32-bit integer
    BBK    = 15, // Background color B, unsigned 32-bit integer
    LR1LR2 = 16, // Light color matrix source (lr1, lr2), 2 signed 16-bit integers
    LR3LG1 = 17, // Light color matrix source (lr3, lg1), 2 signed 16-bit integers
    LG2LG3 = 18, // Light color matrix source (lg2, lg3), 2 signed 16-bit integers
    LB1LB2 = 19, // Light color matrix source (lb1, lb2), 2 signed 16-bit integers
    LB3    = 20, // Light color matrix source (lb3), signed 16-bit integer
    RFC    = 21, // Far color R, unsigned 32-bit integer
    GFC    = 22, // Far color G, unsigned 32-bit integer
    BFC    = 23, // Far color B, unsigned 32-bit integer
    OFX    = 24, // Screen offset X, signed 32-bit integer
    OFY    = 25, // Screen offset Y, signed 32-bit integer
    H      = 26, // Projection plane distance, unsigned 16-bit integer
    DQA    = 27, // Depth queing parameter A (coefficient), signed 16-bit integer
    DQB    = 28, // Depth queing parameter B (offset), unsigned 32-bit integer
    ZSF3   = 29, // Z-averaging scale factor, signed 16-bit integer
    ZSF4   = 30, // Z-averaging scale factor, signed 16-bit integer
    FLAG   = 31  // Flag (read-only), returns any calculation errors, 20 bits
}

uint opR(ubyte op, ubyte rs, ubyte rt, ubyte rd, ubyte sh, ubyte fn)
{
    return (op << 26) | (rs << 21) | (rt << 16) | (rd << 11) | (sh << 6) | fn;
}

uint opI(ubyte op, ubyte rs, ubyte rt, short imm)
{
    return (op << 26) | (rs << 21) | (rt << 16) | (cast(uint)imm & 0xffff);
}

uint opJ(ubyte op, uint addr)
{
    return (op << 26) | ((addr >> 2) & 0x03ffffff);
}

enum opNop = 0x00000000;

// R-type
Word opAdd(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x20); }
Word opAddu(Reg rd, Reg rs, Reg rt)     { return opR(0, rs, rt, rd, 0, 0x21); }
Word opSub(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x22); }
Word opSubu(Reg rd, Reg rs, Reg rt)     { return opR(0, rs, rt, rd, 0, 0x23); }
Word opAnd(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x24); }
Word opOr(Reg rd, Reg rs, Reg rt)       { return opR(0, rs, rt, rd, 0, 0x25); }
Word opXor(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x26); }
Word opNor(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x27); }
Word opSlt(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x2A); }
Word opSll(Reg rd, Reg rt, ubyte sh)    { return opR(0, 0, rt, rd, sh, 0x00); }
Word opSrl(Reg rd, Reg rt, ubyte sh)    { return opR(0, 0, rt, rd, sh, 0x02); }
Word opJr(Reg rs)                       { return opR(0, rs, 0, 0, 0, 0x08); }
Word opJalr(Reg rd, Reg rs)             { return opR(0, rs, 0, rd, 0, 0x09); }
Word opSltu(Reg rd, Reg rs, Reg rt)     { return opR(0, rs, rt, rd, 0, 0x2B); }
Word opSra(Reg rd, Reg rt, ubyte sh)    { return opR(0, 0, rt, rd, sh, 0x03); }
Word opSllv(Reg rd, Reg rt, Reg rs)     { return opR(0, rs, rt, rd, 0, 0x04); }
Word opSrlv(Reg rd, Reg rt, Reg rs)     { return opR(0, rs, rt, rd, 0, 0x06); }
Word opSrav(Reg rd, Reg rt, Reg rs)     { return opR(0, rs, rt, rd, 0, 0x07); }
Word opMult(Reg rs, Reg rt)             { return opR(0, rs, rt, 0, 0, 0x18); }
Word opMultu(Reg rs, Reg rt)            { return opR(0, rs, rt, 0, 0, 0x19); }
Word opDiv(Reg rs, Reg rt)              { return opR(0, rs, rt, 0, 0, 0x1A); }
Word opDivu(Reg rs, Reg rt)             { return opR(0, rs, rt, 0, 0, 0x1B); }
Word opMfhi(Reg rd)                     { return opR(0, 0, 0, rd, 0, 0x10); }
Word opMflo(Reg rd)                     { return opR(0, 0, 0, rd, 0, 0x12); }
Word opMthi(Reg rs)                     { return opR(0, rs, 0, 0, 0, 0x11); }
Word opMtlo(Reg rs)                     { return opR(0, rs, 0, 0, 0, 0x13); }

// I-type
Word opAddi(Reg rt, Reg rs, short imm)  { return opI(0x08, rs, rt, imm); }
Word opAddiu(Reg rt, Reg rs, short imm) { return opI(0x09, rs, rt, imm); }
Word opAndi(Reg rt, Reg rs, ushort imm) { return opI(0x0C, rs, rt, imm); }
Word opOri(Reg rt, Reg rs, ushort imm)  { return opI(0x0D, rs, rt, imm); }
Word opXori(Reg rt, Reg rs, ushort imm) { return opI(0x0E, rs, rt, imm); }
Word opLui(Reg rt, ushort imm)          { return opI(0x0F, 0, rt, imm); }
Word opBeq(Reg rs, Reg rt, short off)   { return opI(0x04, rs, rt, off); }
Word opBne(Reg rs, Reg rt, short off)   { return opI(0x05, rs, rt, off); }
Word opSlti(Reg rt, Reg rs, short imm)  { return opI(0x0A, rs, rt, imm); }
Word opSltiu(Reg rt, Reg rs, short imm) { return opI(0x0B, rs, rt, imm); }
Word opLb(Reg rt, short off, Reg base)  { return opI(0x20, base, rt, off); }
Word opLh(Reg rt, short off, Reg base)  { return opI(0x21, base, rt, off); }
Word opLwl(Reg rt, short off, Reg base) { return opI(0x22, base, rt, off); }
Word opLw(Reg rt, short off, Reg base)  { return opI(0x23, base, rt, off); }
Word opLbu(Reg rt, short off, Reg base) { return opI(0x24, base, rt, off); }
Word opLhu(Reg rt, short off, Reg base) { return opI(0x25, base, rt, off); }
Word opLwr(Reg rt, short off, Reg base) { return opI(0x26, base, rt, off); }
Word opSb(Reg rt, short off, Reg base)  { return opI(0x28, base, rt, off); }
Word opSh(Reg rt, short off, Reg base)  { return opI(0x29, base, rt, off); }
Word opSw(Reg rt, short off, Reg base)  { return opI(0x2B, base, rt, off); }
Word opBlez(Reg rs, short off)          { return opI(0x06, rs, 0, off); }
Word opBgtz(Reg rs, short off)          { return opI(0x07, rs, 0, off); }
Word opBltz(Reg rs, short off)          { return opI(0x01, rs, 0x00, off); }
Word opBgez(Reg rs, short off)          { return opI(0x01, rs, 0x01, off); }
Word opBltzal(Reg rs, short off)        { return opI(0x01, rs, 0x10, off); }
Word opBgezal(Reg rs, short off)        { return opI(0x01, rs, 0x11, off); }

// J-type
Word opJ(uint addr)                     { return opJ(0x02, addr); }
Word opJal(uint addr)                   { return opJ(0x03, addr); }

// Misc
Word opSyscall(uint code = 0)
{
    // Mask to 20 bits and place into bits [6..25], funct = 0x0C
    return ((0u << 26) | ((code & 0xFFFFFu) << 6) | 0x0Cu);
}

Word opBreak(uint code = 0)
{
    // Mask to 20 bits and place into bits [6..25], funct = 0x0D
    return ((0u << 26) | ((code & 0xFFFFFu) << 6) | 0x0Du);
}

// Pseudoinstructions
Word opMove(Reg rd, Reg rs)             { return opAddu(rd, rs, R0); }        // Move from one register to another
Word opClear(Reg rd)                    { return opAddu(rd, R0, R0); }        // Clear rd
Word opNeg(Reg rd, Reg rs)              { return opSub(rd, R0, rs); }         // Neg rd, rs
Word opNot(Reg rd, Reg rs)              { return opNor(rd, rs, R0); }         // Not rd, rs
Word opB(Reg rs, short off)             { return opBeq(rs, rs, off); }        // Unconditional branch
Word opBal(short off)                   { return opBgezal(R0, off); }         // Branch and link

Word[] opLi(T)(Reg rt, T imm)
{
    Word[] code;
    
    // If 16-bit
    if (imm >= -32768 && imm <= 32767)
    {
        code ~= opAddi(rt, R0, cast(short)imm);
    }
    else if (imm >= 0 && imm <= 0xffff)
    {
        code ~= opOri(rt, R0, cast(ushort)imm);
    }
    else
    {
        ushort hi = cast(ushort)((imm >> 16) & 0xffff);
        ushort lo = cast(ushort)(imm & 0xffff);
        
        code ~= opLui(rt, hi);
        code ~= opOri(rt, rt, lo);
    }
    
    return code;
}

Word opMfc0(Reg rt, Reg rd) { return opR(0x10, 0x00, rt, rd, 0, 0); }
Word opMtc0(Reg rt, Reg rd) { return opR(0x10, 0x04, rt, rd, 0, 0); }

Word opMfc2(Reg rt, Reg rd) { return opR(0x12, 0x00, rt, rd, 0, 0); }
Word opCfc2(Reg rt, Reg rd) { return opR(0x12, 0x02, rt, rd, 0, 0); }
Word opMtc2(Reg rt, Reg rd) { return opR(0x12, 0x04, rt, rd, 0, 0); }
Word opCtc2(Reg rt, Reg rd) { return opR(0x12, 0x06, rt, rd, 0, 0); }

Word opLwc2(Reg gteRt, short off, Reg base) { return opI(0x32, base, gteRt, off); }
Word opSwc2(Reg gteRt, short off, Reg base) { return opI(0x3A, base, gteRt, off); }

Word opCop2(uint command) { return 0x4A000000 | (command & 0x01ffffff); }

Word opRtps()  { return opCop2(0x00180001); } // Rotate, Translate, Perpective Transformation of 1 point
Word opRtpt()  { return opCop2(0x00280030); } // Rotate, Translate, Perpective Transformation of 3 points
Word opMvmva() { return opCop2(0x00400012); } // Matrix-Vector Multiplication and Addition
Word opDcpl()  { return opCop2(0x00680029); } // Depth Cue Light Color
Word opDpcs()  { return opCop2(0x00780010); } // Depth Cue Single
Word opDpct()  { return opCop2(0x00f8002a); } // Depth Cue Triple
Word opIntpl() { return opCop2(0x00980011); } // Interpolation
Word opSqr()   { return opCop2(0x00a00428); } // Square
Word opNcs()   { return opCop2(0x00c8041e); } // Normal Color
Word opNct()   { return opCop2(0x00d80420); } // 
Word opNcds()  { return opCop2(0x00e80413); } // Normal Color Depth Cue
Word opNcdt()  { return opCop2(0x00f80416); } // Normal Color Depth Cue
Word opNccs()  { return opCop2(0x0108041b); } // Same as NCS, but the base color of the plane or point is taken into account
Word opNcct()  { return opCop2(0x0118043f); } // Same as NCT, but the base color of the plane or point is taken into account
Word opCdp()   { return opCop2(0x01280414); } // A color is calculated from a light vector (base color is assumed to be white) and depth cueing is performed (like DPCS)
Word opCc()    { return opCop2(0x0138041c); } // A color is calculated from a light vector and a base color
Word opNclip() { return opCop2(0x01400006); } // Normal Clipping
Word opAvsz3() { return opCop2(0x0158002d); } // Z-Averaging. Adds 3 Z values together and multplies them by a fixed point value
Word opAvsz4() { return opCop2(0x0168002e); } // Z-Averaging. Adds 4 Z values together and multplies them by a fixed point value
Word opOp()    { return opCop2(0x0170000c); } // The outer product of two vectors
Word opGpf()   { return opCop2(0x0190003d); } // Multiplies two vectors
Word opGpl()   { return opCop2(0x01a0003e); } // Multiplies a vector with a scalar and adds the result to another vector
