/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * MIPS R3000 instruction set.
 */
module mips;

import utils;

alias Word = uint;
alias Reg = ubyte;

enum Op
{
    NOP, SLL, SRL, SRA, SLLV, SRLV, SRAV,
    J, JAL, JR, JALR,
    SYSCALL, BREAK,
    MFHI, MTHI, MFLO, MTLO,
    MULT, MULTU, DIV, DIVU,
    ADD, ADDU, SUB, SUBU,
    ADDI, ADDIU,
    AND, OR, XOR, NOR,
    ANDI, ORI, XORI,
    SLT, SLTU,
    SLTI, SLTIU,
    LUI, LB, LH, LWL, LW, LBU, LHU, LWR,
    SB, SH, SWL, SW, SWR,
    LI, MOVE, CLEAR, NEG, NOT,
    LWC0, LWC1, LWC2, LWC3,
    SWC0, SWC1, SWC2, SWC3,
    BEQ, BNE, BLEZ, BGTZ, BGEZ, BLTZ, BGEZAL, BLTZAL,
    MTC0, MFC0, RFE,
    MTC2, MFC2, CTC2, CFC2
}

enum: Reg
{
    R0   = 0,
    AT   = 1,
    
    V0   = 2,
    V1   = 3,
    
    A0   = 4,
    A1   = 5,
    A2   = 6,
    A3   = 7,
    
    T0   = 8,
    T1   = 9,
    T2   = 10,
    T3   = 11,
    T4   = 12,
    T5   = 13,
    T6   = 14,
    T7   = 15,
    
    S0   = 16,
    S1   = 17,
    S2   = 18,
    S3   = 19,
    S4   = 20,
    S5   = 21,
    S6   = 22,
    S7   = 23,
    
    T8   = 24,
    T9   = 25,
    
    K0   = 26,
    K1   = 27,
    
    GP   = 28,
    SP   = 29,
    FP   = 30,
    //S8   = 30,
    
    RA   = 31
}

uint opR(ubyte op, ubyte rs, ubyte rt, ubyte rd, ubyte sh, ubyte fn)
{
    return (op << 26) | (rs << 21) | (rt << 16) | (rd << 11) | (sh << 6) | fn;
}

uint opI(ubyte op, ubyte rs, ubyte rt, short imm)
{
    return (op << 26) | (rs << 21) | (rt << 16) | (cast(uint)imm & 0xffff);
}

uint opJ(ubyte op, uint addr)
{
    return (op << 26) | ((addr >> 2) & 0x03ffffff);
}

enum opNop = 0x00000000;

// R-type
Word opAdd(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x20); }
Word opAddu(Reg rd, Reg rs, Reg rt)     { return opR(0, rs, rt, rd, 0, 0x21); }
Word opSub(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x22); }
Word opSubu(Reg rd, Reg rs, Reg rt)     { return opR(0, rs, rt, rd, 0, 0x23); }
Word opAnd(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x24); }
Word opOr(Reg rd, Reg rs, Reg rt)       { return opR(0, rs, rt, rd, 0, 0x25); }
Word opXor(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x26); }
Word opNor(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x27); }
Word opSlt(Reg rd, Reg rs, Reg rt)      { return opR(0, rs, rt, rd, 0, 0x2A); }
Word opSll(Reg rd, Reg rt, ubyte sh)    { return opR(0, 0, rt, rd, sh, 0x00); }
Word opSrl(Reg rd, Reg rt, ubyte sh)    { return opR(0, 0, rt, rd, sh, 0x02); }
Word opJr(Reg rs)                       { return opR(0, rs, 0, 0, 0, 0x08); }
Word opJalr(Reg rd, Reg rs)             { return opR(0, rs, 0, rd, 0, 0x09); }
Word opSltu(Reg rd, Reg rs, Reg rt)     { return opR(0, rs, rt, rd, 0, 0x2B); }
Word opSra(Reg rd, Reg rt, ubyte sh)    { return opR(0, 0, rt, rd, sh, 0x03); }
Word opSllv(Reg rd, Reg rt, Reg rs)     { return opR(0, rs, rt, rd, 0, 0x04); }
Word opSrlv(Reg rd, Reg rt, Reg rs)     { return opR(0, rs, rt, rd, 0, 0x06); }
Word opSrav(Reg rd, Reg rt, Reg rs)     { return opR(0, rs, rt, rd, 0, 0x07); }
Word opMult(Reg rs, Reg rt)             { return opR(0, rs, rt, 0, 0, 0x18); }
Word opMultu(Reg rs, Reg rt)            { return opR(0, rs, rt, 0, 0, 0x19); }
Word opDiv(Reg rs, Reg rt)              { return opR(0, rs, rt, 0, 0, 0x1A); }
Word opDivu(Reg rs, Reg rt)             { return opR(0, rs, rt, 0, 0, 0x1B); }
Word opMfhi(Reg rd)                     { return opR(0, 0, 0, rd, 0, 0x10); }
Word opMflo(Reg rd)                     { return opR(0, 0, 0, rd, 0, 0x12); }
Word opMthi(Reg rs)                     { return opR(0, rs, 0, 0, 0, 0x11); }
Word opMtlo(Reg rs)                     { return opR(0, rs, 0, 0, 0, 0x13); }

// I-type
Word opAddi(Reg rt, Reg rs, short imm)  { return opI(0x08, rs, rt, imm); }
Word opAddiu(Reg rt, Reg rs, short imm) { return opI(0x09, rs, rt, imm); }
Word opAndi(Reg rt, Reg rs, ushort imm) { return opI(0x0C, rs, rt, imm); }
Word opOri(Reg rt, Reg rs, ushort imm)  { return opI(0x0D, rs, rt, imm); }
Word opXori(Reg rt, Reg rs, ushort imm) { return opI(0x0E, rs, rt, imm); }
Word opLui(Reg rt, ushort imm)          { return opI(0x0F, 0, rt, imm); }
Word opBeq(Reg rs, Reg rt, short off)   { return opI(0x04, rs, rt, off); }
Word opBne(Reg rs, Reg rt, short off)   { return opI(0x05, rs, rt, off); }
Word opSlti(Reg rt, Reg rs, short imm)  { return opI(0x0A, rs, rt, imm); }
Word opSltiu(Reg rt, Reg rs, short imm) { return opI(0x0B, rs, rt, imm); }
Word opLb(Reg rt, short off, Reg base)  { return opI(0x20, base, rt, off); }
Word opLh(Reg rt, short off, Reg base)  { return opI(0x21, base, rt, off); }
Word opLwl(Reg rt, short off, Reg base) { return opI(0x22, base, rt, off); }
Word opLw(Reg rt, short off, Reg base)  { return opI(0x23, base, rt, off); }
Word opLbu(Reg rt, short off, Reg base) { return opI(0x24, base, rt, off); }
Word opLhu(Reg rt, short off, Reg base) { return opI(0x25, base, rt, off); }
Word opLwr(Reg rt, short off, Reg base) { return opI(0x26, base, rt, off); }
Word opSb(Reg rt, short off, Reg base)  { return opI(0x28, base, rt, off); }
Word opSh(Reg rt, short off, Reg base)  { return opI(0x29, base, rt, off); }
Word opSw(Reg rt, short off, Reg base)  { return opI(0x2B, base, rt, off); }
Word opBlez(Reg rs, short off)          { return opI(0x06, rs, 0, off); }
Word opBgtz(Reg rs, short off)          { return opI(0x07, rs, 0, off); }
Word opBltz(Reg rs, short off)          { return opI(0x01, rs, 0x00, off); }
Word opBgez(Reg rs, short off)          { return opI(0x01, rs, 0x01, off); }
Word opBltzal(Reg rs, short off)        { return opI(0x01, rs, 0x10, off); }
Word opBgezal(Reg rs, short off)        { return opI(0x01, rs, 0x11, off); }

// J-type
Word opJ(uint addr)                     { return opJ(0x02, addr); }
Word opJal(uint addr)                   { return opJ(0x03, addr); }

// Misc
Word opSyscall(uint code = 0)
{
    // mask to 20 bits and place into bits [6..25], funct = 0x0C
    return ((0u << 26) | ((code & 0xFFFFFu) << 6) | 0x0Cu);
}

Word opBreak(uint code = 0)
{
    // mask to 20 bits and place into bits [6..25], funct = 0x0D
    return ((0u << 26) | ((code & 0xFFFFFu) << 6) | 0x0Du);
}

// Pseudoinstructions
Word opMove(Reg rd, Reg rs)             { return opAddu(rd, rs, R0); }        // Move from one register to another
Word opClear(Reg rd)                    { return opAddu(rd, R0, R0); }        // Clear rd
Word opNeg(Reg rd, Reg rs)              { return opSub(rd, R0, rs); }         // Neg rd, rs
Word opNot(Reg rd, Reg rs)              { return opNor(rd, rs, R0); }         // Not rd, rs
Word opB(Reg rs, short off)             { return opBeq(rs, rs, off); }        // Unconditional branch
Word opBal(short off)                   { return opBgezal(R0, off); }         // Branch and link

Word[] opLi(T)(Reg rt, T imm)
{
    Word[] code;
    
    // If 16-bit
    if (imm >= -32768 && imm <= 32767)
    {
        code ~= opAddi(rt, R0, cast(short)imm); // addi rt, r0, imm
    }
    else if (imm >= 0 && imm <= 0xffff)
    {
        code ~= opOri(rt, R0, cast(ushort)imm); // ori rt, r0, imm
    }
    else
    {
        ushort hi = cast(ushort)((imm >> 16) & 0xffff);
        ushort lo = cast(ushort)(imm & 0xffff);
        
        // sign-extend
        if (lo & 0x8000)
            hi++;
        
        code ~= opLui(rt, hi);
        code ~= opOri(rt, rt, lo);
    }
    
    return code;
}
