/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module parser;

import std.format: format;

import lexer;
import types;
import ast;
import error;
import utils;

long wrap32(long v)
{
    return cast(int) v;
}

bool constEval(Expr e, out long v)
{
    v = 0;
    if (e is null)
        return false;

    if (e.kind == EK.Num)
    {
        v = e.num;
        return true;
    }

    if (e.kind == EK.Unary && (e.op == "-" || e.op == "~" || e.op == "!"))
    {
        long a;
        if (!constEval(e.a, a))
            return false;
        if (e.op == "-")
            v = wrap32(-a);
        else if (e.op == "~")
            v = wrap32(~a);
        else
            v = (a == 0) ? 1 : 0;
        return true;
    }

    if (e.kind == EK.Binary)
    {
        long a, b;
        if (!constEval(e.a, a) || !constEval(e.b, b))
            return false;
        switch (e.op)
        {
            case "+":  v = wrap32(a + b); return true;
            case "-":  v = wrap32(a - b); return true;
            case "*":  v = wrap32(a * b); return true;
            case "/":  if (b == 0) return false; v = wrap32(a / b); return true;
            case "%":  if (b == 0) return false; v = wrap32(a % b); return true;
            case "&":  v = wrap32(a & b); return true;
            case "|":  v = wrap32(a | b); return true;
            case "^":  v = wrap32(a ^ b); return true;
            case "<<": if (b < 0 || b > 31) return false; v = wrap32(a << b); return true;
            case ">>": if (b < 0 || b > 31) return false; v = a >> b; return true;
            case "==": v = (a == b) ? 1 : 0; return true;
            case "!=": v = (a != b) ? 1 : 0; return true;
            case "<":  v = (a < b) ? 1 : 0; return true;
            case "<=": v = (a <= b) ? 1 : 0; return true;
            case ">":  v = (a > b) ? 1 : 0; return true;
            case ">=": v = (a >= b) ? 1 : 0; return true;
            case "&&": v = (a != 0 && b != 0) ? 1 : 0; return true;
            case "||": v = (a != 0 || b != 0) ? 1 : 0; return true;
            default:   return false;
        }
    }

    return false;
}

immutable string[][] binLevels = [
    ["||"], ["&&"], ["|"], ["^"], ["&"],
    ["==", "!="], ["<", "<=", ">", ">="],
    ["<<", ">>"], ["+", "-"], ["*", "/", "%"]
];

immutable string[] assignOps = ["=", "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=", "<<=", ">>="];

class Parser
{
    Token[] toks;
    size_t p;

    this(Token[] t)
    {
        toks = t;
    }

    Token peek(size_t k = 0)
    {
        size_t i = p + k;
        if (i >= toks.length)
            i = toks.length - 1;
        return toks[i];
    }

    Token next()
    {
        Token t = peek();
        if (p + 1 < toks.length)
            p++;
        return t;
    }

    bool isSym(string s, size_t k = 0)
    {
        Token t = peek(k);
        return t.kind == TK.Sym && t.text == s;
    }

    bool isKw(string s, size_t k = 0)
    {
        Token t = peek(k);
        return t.kind == TK.Ident && t.text == s;
    }

    bool acceptSym(string s)
    {
        if (isSym(s))
        {
            next();
            return true;
        }
        return false;
    }

    void expectSym(string s)
    {
        if (!acceptSym(s))
            throw err(peek().line, format("expected '%s' but found '%s'", s, peek().text));
    }

    string expectIdent()
    {
        Token t = next();
        if (t.kind != TK.Ident || isReserved(t.text))
            throw err(t.line, format("expected an identifier but found '%s'", t.text));
        return t.text;
    }

    bool isTypeStart(size_t k = 0)
    {
        Token t = peek(k);
        return t.kind == TK.Ident &&
               (t.text == "int" || t.text == "short" || t.text == "char" || t.text == "void");
    }

    CType parseBaseType()
    {
        Token t = next();
        CType ty;
        switch (t.text)
        {
            case "int":   ty.base = Base.Int; break;
            case "short": ty.base = Base.Short; break;
            case "char":  ty.base = Base.Char; break;
            case "void":  ty.base = Base.Void; break;
            default: throw err(t.line, format("expected a type but found '%s'", t.text));
        }
        return ty;
    }

    CType parseType()
    {
        CType ty = parseBaseType();
        while (acceptSym("*"))
            ty.ptr++;
        return ty;
    }

    long parseConstExpr()
    {
        int line = peek().line;
        Expr e = parseAssign();
        long v;
        if (!constEval(e, v))
            throw err(line, "constant expression expected");
        return v;
    }

    // ---- Declarations ----

    Program parseProgram()
    {
        auto prog = new Program();
        while (peek().kind != TK.Eof)
        {
            int line = peek().line;
            CType ty = parseType();
            string name = expectIdent();

            if (isSym("("))
            {
                auto f = new Func();
                f.ret = ty;
                f.name = name;
                f.line = line;
                next();
                if (isKw("void") && isSym(")", 1))
                {
                    next();
                }
                else if (!isSym(")"))
                {
                    do
                    {
                        CType pt = parseType();
                        string pn = expectIdent();
                        f.params ~= Param(pt, pn);
                    } while (acceptSym(","));
                }
                expectSym(")");
                if (acceptSym(";"))
                    f.body_ = null;
                else
                    f.body_ = parseBlock();
                prog.funcs ~= f;
            }
            else
            {
                parseGlobals(prog, ty, name, line);
            }
        }
        return prog;
    }

    void parseGlobals(Program prog, CType firstTy, string firstName, int firstLine)
    {
        CType baseT = firstTy;
        baseT.ptr = 0;
        CType ty = firstTy;
        string name = firstName;
        int line = firstLine;

        while (true)
        {
            auto g = new GlobalDecl();
            g.ty = ty;
            g.name = name;
            g.line = line;

            if (acceptSym("["))
            {
                g.isArray = true;
                if (!isSym("]"))
                {
                    long n = parseConstExpr();
                    if (n <= 0 || n > 4000000)
                        throw err(line, "invalid array size");
                    g.arrLen = cast(int) n;
                }
                expectSym("]");
            }

            if (acceptSym("="))
            {
                g.hasInit = true;
                if (peek().kind == TK.Str)
                {
                    Token s = next();
                    g.strInit = true;
                    g.strBytes = parseEscapes(s.text) ~ cast(ubyte) 0;
                }
                else if (g.isArray)
                {
                    expectSym("{");
                    if (!isSym("}"))
                    {
                        do
                        {
                            if (isSym("}"))
                                break;
                            g.inits ~= parseConstExpr();
                        } while (acceptSym(","));
                    }
                    expectSym("}");
                }
                else
                {
                    g.inits ~= parseConstExpr();
                }
            }

            prog.globals ~= g;

            if (acceptSym(","))
            {
                line = peek().line;
                ty = baseT;
                while (acceptSym("*"))
                    ty.ptr++;
                name = expectIdent();
                continue;
            }
            break;
        }
        expectSym(";");
    }

    // Local declaration list. Consumes the trailing ';'.
    Stmt parseDecl()
    {
        int line = peek().line;
        CType baseT = parseBaseType();
        auto blk = new Stmt(SK.Block, line);
        blk.scoped = false;

        do
        {
            CType ty = baseT;
            while (acceptSym("*"))
                ty.ptr++;
            auto d = new Stmt(SK.Decl, peek().line);
            d.ty = ty;
            d.name = expectIdent();
            if (acceptSym("["))
            {
                long n = parseConstExpr();
                if (n <= 0 || n > 1000000)
                    throw err(d.line, "invalid array size");
                d.arrLen = cast(int) n;
                expectSym("]");
            }
            if (acceptSym("="))
                d.e = parseAssign();
            blk.stmts ~= d;
        } while (acceptSym(","));

        expectSym(";");
        return blk;
    }

    // ---- Statements ----

    Stmt parseBlock()
    {
        auto blk = new Stmt(SK.Block, peek().line);
        expectSym("{");
        while (!isSym("}"))
        {
            if (peek().kind == TK.Eof)
                throw err(peek().line, "unexpected end of file, missing '}'");
            blk.stmts ~= parseStmt();
        }
        expectSym("}");
        return blk;
    }

    Stmt parseStmt()
    {
        Token t = peek();

        if (isSym("{"))
            return parseBlock();

        if (acceptSym(";"))
            return new Stmt(SK.Empty, t.line);

        if (isKw("if"))
        {
            next();
            auto s = new Stmt(SK.If, t.line);
            expectSym("(");
            s.e = parseExpr();
            expectSym(")");
            s.thenS = parseStmt();
            if (isKw("else"))
            {
                next();
                s.elseS = parseStmt();
            }
            return s;
        }

        if (isKw("while"))
        {
            next();
            auto s = new Stmt(SK.While, t.line);
            expectSym("(");
            s.e = parseExpr();
            expectSym(")");
            s.thenS = parseStmt();
            return s;
        }

        if (isKw("do"))
        {
            next();
            auto s = new Stmt(SK.DoWhile, t.line);
            s.thenS = parseStmt();
            if (!isKw("while"))
                throw err(peek().line, "expected 'while' after do-body");
            next();
            expectSym("(");
            s.e = parseExpr();
            expectSym(")");
            expectSym(";");
            return s;
        }

        if (isKw("for"))
        {
            next();
            auto s = new Stmt(SK.For, t.line);
            expectSym("(");
            if (acceptSym(";"))
            {
                // no init
            }
            else if (isTypeStart())
            {
                s.forInit = parseDecl();
            }
            else
            {
                auto init = new Stmt(SK.ExprS, peek().line);
                init.e = parseExpr();
                expectSym(";");
                s.forInit = init;
            }
            if (!isSym(";"))
                s.e = parseExpr();
            expectSym(";");
            if (!isSym(")"))
                s.step = parseExpr();
            expectSym(")");
            s.thenS = parseStmt();
            return s;
        }

        if (isKw("return"))
        {
            next();
            auto s = new Stmt(SK.Return, t.line);
            if (!isSym(";"))
                s.e = parseExpr();
            expectSym(";");
            return s;
        }

        if (isKw("break"))
        {
            next();
            expectSym(";");
            return new Stmt(SK.Break, t.line);
        }

        if (isKw("continue"))
        {
            next();
            expectSym(";");
            return new Stmt(SK.Continue, t.line);
        }

        if (isTypeStart())
            return parseDecl();

        auto es = new Stmt(SK.ExprS, t.line);
        es.e = parseExpr();
        expectSym(";");
        return es;
    }

    // ---- Expressions ----

    Expr parseExpr()
    {
        return parseAssign();
    }

    Expr parseAssign()
    {
        Expr l = parseBin(0);
        Token t = peek();
        if (t.kind == TK.Sym && inList(t.text, assignOps))
        {
            next();
            auto e = new Expr(EK.Assign, t.line);
            e.op = t.text;
            e.a = l;
            e.b = parseAssign();
            return e;
        }
        return l;
    }

    Expr parseBin(size_t lvl)
    {
        if (lvl >= binLevels.length)
            return parseUnary();

        Expr l = parseBin(lvl + 1);
        while (true)
        {
            Token t = peek();
            if (t.kind != TK.Sym || !inList(t.text, binLevels[lvl]))
                break;
            next();
            auto e = new Expr(EK.Binary, t.line);
            e.op = t.text;
            e.a = l;
            e.b = parseBin(lvl + 1);
            l = e;
        }
        return l;
    }

    Expr parseUnary()
    {
        Token t = peek();
        if (t.kind == TK.Sym)
        {
            if (t.text == "-" || t.text == "!" || t.text == "~" || t.text == "*" || t.text == "&")
            {
                next();
                auto e = new Expr(EK.Unary, t.line);
                e.op = t.text;
                e.a = parseUnary();
                return e;
            }
            if (t.text == "+")
            {
                next();
                return parseUnary();
            }
            if (t.text == "++" || t.text == "--")
            {
                next();
                auto e = new Expr(EK.IncDec, t.line);
                e.op = t.text;
                e.a = parseUnary();
                e.post = false;
                return e;
            }
            if (t.text == "(" && isTypeStart(1))
            {
                next();
                CType ty = parseType();
                expectSym(")");
                auto e = new Expr(EK.Cast, t.line);
                e.ty = ty;
                e.a = parseUnary();
                return e;
            }
        }
        return parsePostfix();
    }

    Expr parsePostfix()
    {
        Expr e = parsePrimary();
        while (true)
        {
            Token t = peek();
            if (isSym("["))
            {
                next();
                auto n = new Expr(EK.Index, t.line);
                n.a = e;
                n.b = parseExpr();
                expectSym("]");
                e = n;
            }
            else if (isSym("("))
            {
                if (e.kind != EK.Var)
                    throw err(t.line, "only named functions can be called");
                next();
                auto c = new Expr(EK.Call, t.line);
                c.name = e.name;
                if (!isSym(")"))
                {
                    do
                    {
                        c.args ~= parseAssign();
                    } while (acceptSym(","));
                }
                expectSym(")");
                e = c;
            }
            else if (isSym("++") || isSym("--"))
            {
                next();
                auto n = new Expr(EK.IncDec, t.line);
                n.op = t.text;
                n.a = e;
                n.post = true;
                e = n;
            }
            else
                break;
        }
        return e;
    }

    Expr parsePrimary()
    {
        Token t = next();
        if (t.kind == TK.Num)
            return numExpr(t.num, t.line);
        if (t.kind == TK.Str)
        {
            auto e = new Expr(EK.Str, t.line);
            e.name = t.text;
            return e;
        }
        if (t.kind == TK.Ident && !isReserved(t.text))
        {
            auto e = new Expr(EK.Var, t.line);
            e.name = t.text;
            return e;
        }
        if (t.kind == TK.Sym && t.text == "(")
        {
            Expr e = parseExpr();
            expectSym(")");
            return e;
        }
        throw err(t.line, format("unexpected '%s'", t.text));
    }
}
