/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module parser;

import std.format: format;

import lexer;
import types;
import ast;
import error;
import utils;

long wrap32(long v)
{
    return cast(int) v;
}

// Is a constant expression unsigned (C rules, 32-bit)?
bool constUns(Expr e)
{
    if (e.kind == EK.Num)
        return e.uns;
    if (e.kind == EK.Unary && (e.op == "-" || e.op == "~"))
        return constUns(e.a);
    if (e.kind == EK.Binary)
    {
        switch (e.op)
        {
            case "+": case "-": case "*": case "/": case "%":
            case "&": case "|": case "^":
                return constUns(e.a) || constUns(e.b);
            case "<<": case ">>":
                return constUns(e.a);
            default:
                return false;
        }
    }
    return false;
}

bool constEval(Expr e, out long v)
{
    v = 0;
    if (e is null)
        return false;

    if (e.kind == EK.Num)
    {
        v = e.num;
        return true;
    }

    if (e.kind == EK.Unary && (e.op == "-" || e.op == "~" || e.op == "!"))
    {
        long a;
        if (!constEval(e.a, a))
            return false;
        if (e.op == "-")
            v = wrap32(-a);
        else if (e.op == "~")
            v = wrap32(~a);
        else
            v = (a == 0) ? 1 : 0;
        return true;
    }

    if (e.kind == EK.Binary)
    {
        long a, b;
        if (!constEval(e.a, a) || !constEval(e.b, b))
            return false;
        bool ua = constUns(e.a);
        bool ub = constUns(e.b);
        uint x = cast(uint) a;
        uint y = cast(uint) b;
        switch (e.op)
        {
            case "+":  v = wrap32(a + b); return true;
            case "-":  v = wrap32(a - b); return true;
            case "*":  v = wrap32(a * b); return true;
            case "/":  if (b == 0) return false; v = (ua || ub) ? wrap32(x / y) : wrap32(a / b); return true;
            case "%":  if (b == 0) return false; v = (ua || ub) ? wrap32(x % y) : wrap32(a % b); return true;
            case "&":  v = wrap32(a & b); return true;
            case "|":  v = wrap32(a | b); return true;
            case "^":  v = wrap32(a ^ b); return true;
            case "<<": if (b < 0 || b > 31) return false; v = wrap32(a << b); return true;
            case ">>": if (b < 0 || b > 31) return false; v = ua ? wrap32(x >> b) : (a >> b); return true;
            case "==": v = (a == b) ? 1 : 0; return true;
            case "!=": v = (a != b) ? 1 : 0; return true;
            case "<":  v = ((ua || ub) ? (x < y) : (a < b)) ? 1 : 0; return true;
            case "<=": v = ((ua || ub) ? (x <= y) : (a <= b)) ? 1 : 0; return true;
            case ">":  v = ((ua || ub) ? (x > y) : (a > b)) ? 1 : 0; return true;
            case ">=": v = ((ua || ub) ? (x >= y) : (a >= b)) ? 1 : 0; return true;
            case "&&": v = (a != 0 && b != 0) ? 1 : 0; return true;
            case "||": v = (a != 0 || b != 0) ? 1 : 0; return true;
            default:   return false;
        }
    }

    return false;
}

// ---------------------------------------------------------------------------
// Parser
// ---------------------------------------------------------------------------

immutable string[][] binLevels = [
    ["||"], ["&&"], ["|"], ["^"], ["&"],
    ["==", "!="], ["<", "<=", ">", ">="],
    ["<<", ">>"], ["+", "-"], ["*", "/", "%"]
];

immutable string[] assignOps = ["=", "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=", "<<=", ">>="];

immutable string[] _types = ["int", "short", "char", "void", "uint", "ushort", "uchar", "unsigned", "struct"];

class Parser
{
    Token[] toks;
    size_t p;

    this(Token[] t)
    {
        toks = t;
    }

    Token peek(size_t k = 0)
    {
        size_t i = p + k;
        if (i >= toks.length)
            i = toks.length - 1;
        return toks[i];
    }

    Token next()
    {
        Token t = peek();
        if (p + 1 < toks.length)
            p++;
        return t;
    }

    bool isSym(string s, size_t k = 0)
    {
        Token t = peek(k);
        return t.kind == TK.Sym && t.text == s;
    }

    bool isKw(string s, size_t k = 0)
    {
        Token t = peek(k);
        return t.kind == TK.Ident && t.text == s;
    }

    bool acceptSym(string s)
    {
        if (isSym(s))
        {
            next();
            return true;
        }
        return false;
    }

    void expectSym(string s)
    {
        if (!acceptSym(s))
            throw err(peek().line, format("expected '%s' but found '%s'", s, peek().text));
    }

    string expectIdent()
    {
        Token t = next();
        if (t.kind != TK.Ident || isReserved(t.text))
            throw err(t.line, format("expected an identifier but found '%s'", t.text));
        return t.text;
    }

    bool isTypeStart(size_t k = 0)
    {
        Token t = peek(k);
        return t.kind == TK.Ident && inList(t.text, _types);
    }

    CType parseBaseType()
    {
        Token t = next();
        CType ty;
        switch (t.text)
        {
            case "int":   ty.base = Base.Int; break;
            case "short": ty.base = Base.Short; break;
            case "char":  ty.base = Base.Char; break;
            case "void":  ty.base = Base.Void; break;
            case "struct":
                string sn = expectIdent();
                ty.base = Base.Struct;
                ty.sname = sn;
                if (sn !in structDefs)
                {
                    auto sd = new StructDef();
                    sd.name = sn;
                    structDefs[sn] = sd;
                }
                break;
            case "uint":   ty.base = Base.Int;   ty.uns = true; break;
            case "ushort": ty.base = Base.Short; ty.uns = true; break;
            case "uchar":  ty.base = Base.Char;  ty.uns = true; break;
            case "unsigned":
                ty.base = Base.Int;
                ty.uns = true;
                if (isKw("int"))
                    next();
                else if (isKw("short"))
                {
                    next();
                    ty.base = Base.Short;
                }
                else if (isKw("char"))
                {
                    next();
                    ty.base = Base.Char;
                }
                break;
            default: throw err(t.line, format("expected a type but found '%s'", t.text));
        }
        return ty;
    }

    CType parseType()
    {
        CType ty = parseBaseType();
        while (acceptSym("*"))
            ty.ptr++;
        checkComplete(ty, peek().line);
        return ty;
    }

    // A struct may only be used by value once it is fully defined
    // (pointers to incomplete structs are fine).
    void checkComplete(CType ty, int line)
    {
        if (isStructVal(ty) && !structDefs[ty.sname].complete)
            throw err(line, format("incomplete type 'struct %s'", ty.sname));
    }

    long parseConstExpr()
    {
        int line = peek().line;
        Expr e = parseAssign();
        long v;
        if (!constEval(e, v))
            throw err(line, "constant expression expected");
        return v;
    }

    // ---- Declarations ----

    Program parseProgram()
    {
        auto prog = new Program();
        while (peek().kind != TK.Eof)
        {
            if (isKw("struct") && peek(1).kind == TK.Ident && isSym("{", 2))
            {
                parseStructDef();
                continue;
            }

            int line = peek().line;
            CType ty = parseType();
            string name = expectIdent();

            if (isSym("("))
            {
                if (isStructVal(ty))
                    throw err(line, "functions cannot return structs by value (return a pointer)");
                auto f = new Func();
                f.ret = ty;
                f.name = name;
                f.line = line;
                next();
                if (isKw("void") && isSym(")", 1))
                {
                    next();
                }
                else if (!isSym(")"))
                {
                    do
                    {
                        CType pt = parseType();
                        if (isStructVal(pt))
                            throw err(peek().line, "structs cannot be passed by value (pass a pointer)");
                        string pn = expectIdent();
                        f.params ~= Param(pt, pn);
                    } while (acceptSym(","));
                }
                expectSym(")");
                if (acceptSym(";"))
                    f.body_ = null;
                else
                    f.body_ = parseBlock();
                prog.funcs ~= f;
            }
            else
            {
                parseGlobals(prog, ty, name, line);
            }
        }
        return prog;
    }

    void parseGlobals(Program prog, CType firstTy, string firstName, int firstLine)
    {
        CType baseT = firstTy;
        baseT.ptr = 0;
        CType ty = firstTy;
        string name = firstName;
        int line = firstLine;

        while (true)
        {
            auto g = new GlobalDecl();
            g.ty = ty;
            g.name = name;
            g.line = line;

            if (acceptSym("["))
            {
                g.isArray = true;
                if (!isSym("]"))
                {
                    long n = parseConstExpr();
                    if (n <= 0 || n > 4000000)
                        throw err(line, "invalid array size");
                    g.arrLen = cast(int) n;
                }
                expectSym("]");
            }

            if (isStructVal(g.ty) && isSym("="))
                throw err(line, "struct initializers are not supported (assign the members in code)");

            if (acceptSym("="))
            {
                g.hasInit = true;
                if (peek().kind == TK.Str)
                {
                    Token s = next();
                    g.strInit = true;
                    g.strBytes = parseEscapes(s.text) ~ cast(ubyte)0;
                }
                else if (g.isArray)
                {
                    expectSym("{");
                    if (!isSym("}"))
                    {
                        do
                        {
                            if (isSym("}"))
                                break;
                            g.inits ~= parseConstExpr();
                        } while (acceptSym(","));
                    }
                    expectSym("}");
                }
                else
                {
                    g.inits ~= parseConstExpr();
                }
            }
            
            if (acceptSym("@"))
            {
                expectSym("(");
                if (!isSym(")"))
                {
                    auto attrType = peek().kind;
                    if (attrType == TK.Str)
                    {
                        Token s = next();
                        g.attrFilename = s.text;
                    }
                    else
                        throw err(line, "attribute requires a string");
                    
                    expectSym(")");
                }
            }

            prog.globals ~= g;

            if (acceptSym(","))
            {
                line = peek().line;
                ty = baseT;
                while (acceptSym("*"))
                    ty.ptr++;
                checkComplete(ty, line);
                name = expectIdent();
                continue;
            }
            break;
        }
        expectSym(";");
    }

    // struct Name { fields }; (top level only).
    // Layout follows C: each field is aligned to its own alignment,
    // the struct size is rounded up to its alignment.
    void parseStructDef()
    {
        next(); // 'struct'
        string name = expectIdent();
        int line = peek().line;

        StructDef sd;
        if (auto p0 = name in structDefs)
            sd = *p0;
        else
        {
            sd = new StructDef();
            sd.name = name;
            structDefs[name] = sd;
        }
        if (sd.complete)
            throw err(line, "redefinition of struct '" ~ name ~ "'");

        expectSym("{");
        int off = 0;
        int al = 1;
        while (!isSym("}"))
        {
            if (peek().kind == TK.Eof)
                throw err(peek().line, "unexpected end of file in struct definition");
            CType bt = parseBaseType();
            do
            {
                CType ty = bt;
                while (acceptSym("*"))
                    ty.ptr++;
                int fline = peek().line;
                if (ty.ptr == 0 && ty.base == Base.Void)
                    throw err(fline, "struct member cannot have type void");
                checkComplete(ty, fline);

                Field fd;
                fd.ty = ty;
                fd.name = expectIdent();
                foreach (other; sd.fields)
                {
                    if (other.name == fd.name)
                        throw err(fline, "duplicate member '" ~ fd.name ~ "'");
                }
                if (acceptSym("["))
                {
                    long n = parseConstExpr();
                    if (n <= 0 || n > 1000000)
                        throw err(fline, "invalid array size");
                    fd.isArray = true;
                    fd.arrLen = cast(int) n;
                    expectSym("]");
                }

                int fa = alignOf(ty);
                int fsz = fd.isArray ? fd.arrLen * ty.size() : ty.size();
                off = (off + fa - 1) & ~(fa - 1);
                fd.offset = off;
                off += fsz;
                if (fa > al)
                    al = fa;
                sd.fields ~= fd;
            } while (acceptSym(","));
            expectSym(";");
        }
        expectSym("}");
        expectSym(";");

        if (sd.fields.length == 0)
            throw err(line, "empty struct");
        sd.align_ = al;
        sd.size = (off + al - 1) & ~(al - 1);
        sd.complete = true;
    }

    // Local declaration list. Consumes the trailing ';'.
    Stmt parseDecl()
    {
        int line = peek().line;
        CType baseT = parseBaseType();
        auto blk = new Stmt(SK.Block, line);
        blk.scoped = false;

        do
        {
            CType ty = baseT;
            while (acceptSym("*"))
                ty.ptr++;
            checkComplete(ty, peek().line);
            auto d = new Stmt(SK.Decl, peek().line);
            d.ty = ty;
            d.name = expectIdent();
            if (acceptSym("["))
            {
                long n = parseConstExpr();
                if (n <= 0 || n > 1000000)
                    throw err(d.line, "invalid array size");
                d.arrLen = cast(int) n;
                expectSym("]");
            }
            if (acceptSym("="))
                d.e = parseAssign();
            blk.stmts ~= d;
        } while (acceptSym(","));

        expectSym(";");
        return blk;
    }

    // ---- Statements ----

    Stmt parseBlock()
    {
        auto blk = new Stmt(SK.Block, peek().line);
        expectSym("{");
        while (!isSym("}"))
        {
            if (peek().kind == TK.Eof)
                throw err(peek().line, "unexpected end of file, missing '}'");
            blk.stmts ~= parseStmt();
        }
        expectSym("}");
        return blk;
    }

    Stmt parseStmt()
    {
        Token t = peek();

        if (isSym("{"))
            return parseBlock();

        if (acceptSym(";"))
            return new Stmt(SK.Empty, t.line);

        if (isKw("if"))
        {
            next();
            auto s = new Stmt(SK.If, t.line);
            expectSym("(");
            s.e = parseExpr();
            expectSym(")");
            s.thenS = parseStmt();
            if (isKw("else"))
            {
                next();
                s.elseS = parseStmt();
            }
            return s;
        }

        if (isKw("while"))
        {
            next();
            auto s = new Stmt(SK.While, t.line);
            expectSym("(");
            s.e = parseExpr();
            expectSym(")");
            s.thenS = parseStmt();
            return s;
        }

        if (isKw("do"))
        {
            next();
            auto s = new Stmt(SK.DoWhile, t.line);
            s.thenS = parseStmt();
            if (!isKw("while"))
                throw err(peek().line, "expected 'while' after do-body");
            next();
            expectSym("(");
            s.e = parseExpr();
            expectSym(")");
            expectSym(";");
            return s;
        }

        if (isKw("for"))
        {
            next();
            auto s = new Stmt(SK.For, t.line);
            expectSym("(");
            if (acceptSym(";"))
            {
                // no init
            }
            else if (isTypeStart())
            {
                s.forInit = parseDecl();
            }
            else
            {
                auto init = new Stmt(SK.ExprS, peek().line);
                init.e = parseExpr();
                expectSym(";");
                s.forInit = init;
            }
            if (!isSym(";"))
                s.e = parseExpr();
            expectSym(";");
            if (!isSym(")"))
                s.step = parseExpr();
            expectSym(")");
            s.thenS = parseStmt();
            return s;
        }

        if (isKw("return"))
        {
            next();
            auto s = new Stmt(SK.Return, t.line);
            if (!isSym(";"))
                s.e = parseExpr();
            expectSym(";");
            return s;
        }

        if (isKw("break"))
        {
            next();
            expectSym(";");
            return new Stmt(SK.Break, t.line);
        }

        if (isKw("continue"))
        {
            next();
            expectSym(";");
            return new Stmt(SK.Continue, t.line);
        }

        if (isTypeStart())
            return parseDecl();

        auto es = new Stmt(SK.ExprS, t.line);
        es.e = parseExpr();
        expectSym(";");
        return es;
    }

    // ---- Expressions ----

    Expr parseExpr()
    {
        return parseAssign();
    }

    Expr parseAssign()
    {
        Expr l = parseBin(0);
        Token t = peek();
        if (t.kind == TK.Sym && inList(t.text, assignOps))
        {
            next();
            auto e = new Expr(EK.Assign, t.line);
            e.op = t.text;
            e.a = l;
            e.b = parseAssign();
            return e;
        }
        return l;
    }

    Expr parseBin(size_t lvl)
    {
        if (lvl >= binLevels.length)
            return parseUnary();

        Expr l = parseBin(lvl + 1);
        while (true)
        {
            Token t = peek();
            if (t.kind != TK.Sym || !inList(t.text, binLevels[lvl]))
                break;
            next();
            auto e = new Expr(EK.Binary, t.line);
            e.op = t.text;
            e.a = l;
            e.b = parseBin(lvl + 1);
            l = e;
        }
        return l;
    }

    Expr parseUnary()
    {
        Token t = peek();
        if (t.kind == TK.Ident && t.text == "sizeof")
        {
            next();
            expectSym("(");
            if (!isTypeStart())
                throw err(t.line, "sizeof needs a type, e.g. sizeof(struct Foo)");
            CType sty = parseType();
            expectSym(")");
            return numExpr(sty.size(), t.line);
        }
        if (t.kind == TK.Sym)
        {
            if (t.text == "-" || t.text == "!" || t.text == "~" || t.text == "*" || t.text == "&")
            {
                next();
                auto e = new Expr(EK.Unary, t.line);
                e.op = t.text;
                e.a = parseUnary();
                return e;
            }
            if (t.text == "+")
            {
                next();
                return parseUnary();
            }
            if (t.text == "++" || t.text == "--")
            {
                next();
                auto e = new Expr(EK.IncDec, t.line);
                e.op = t.text;
                e.a = parseUnary();
                e.post = false;
                return e;
            }
            if (t.text == "(" && isTypeStart(1))
            {
                next();
                CType ty = parseType();
                expectSym(")");
                auto e = new Expr(EK.Cast, t.line);
                e.ty = ty;
                e.a = parseUnary();
                return e;
            }
        }
        return parsePostfix();
    }

    Expr parsePostfix()
    {
        Expr e = parsePrimary();
        while (true)
        {
            Token t = peek();
            if (isSym("["))
            {
                next();
                auto n = new Expr(EK.Index, t.line);
                n.a = e;
                n.b = parseExpr();
                expectSym("]");
                e = n;
            }
            else if (isSym("("))
            {
                if (e.kind != EK.Var)
                    throw err(t.line, "only named functions can be called");
                next();
                auto c = new Expr(EK.Call, t.line);
                c.name = e.name;
                if (!isSym(")"))
                {
                    do
                    {
                        c.args ~= parseAssign();
                    } while (acceptSym(","));
                }
                expectSym(")");
                e = c;
            }
            else if (isSym(".") || isSym("->"))
            {
                next();
                auto m = new Expr(EK.Member, t.line);
                m.a = e;
                m.arrow = (t.text == "->");
                m.name = expectIdent();
                e = m;
            }
            else if (isSym("++") || isSym("--"))
            {
                next();
                auto n = new Expr(EK.IncDec, t.line);
                n.op = t.text;
                n.a = e;
                n.post = true;
                e = n;
            }
            else
                break;
        }
        return e;
    }

    Expr parsePrimary()
    {
        Token t = next();
        if (t.kind == TK.Num)
        {
            auto ne = numExpr(t.num, t.line);
            ne.uns = t.uns;
            return ne;
        }
        if (t.kind == TK.Str)
        {
            auto e = new Expr(EK.Str, t.line);
            e.name = t.text;
            return e;
        }
        if (t.kind == TK.Ident && !isReserved(t.text))
        {
            auto e = new Expr(EK.Var, t.line);
            e.name = t.text;
            return e;
        }
        if (t.kind == TK.Sym && t.text == "(")
        {
            Expr e = parseExpr();
            expectSym(")");
            return e;
        }
        throw err(t.line, format("unexpected '%s'", t.text));
    }
}
