/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module preprocessor;

import std.stdio;
import std.string: splitLines, strip, indexOf, lastIndexOf, replace;
import std.array: join, split;
import std.file: readText, exists;
import std.path: dirName, buildPath;

string preprocess(string src, string currentFilePath)
{
    string[string] globalMacros;
    return preprocessImpl(src, currentFilePath, globalMacros);
}

private string preprocessImpl(string src, string currentFilePath, ref string[string] macros)
{
    string[] lines = src.splitLines();
    string[] cleanLines;
    
    foreach(line; lines)
    {
        auto trimmed = line.strip();
        
        if (trimmed.indexOf("#define") == 0)
        {
            auto parts = trimmed.split();
            if (parts.length >= 3)
                macros[parts[1]] = parts[2];
            continue;
        }
        
        if (trimmed.indexOf("#include") == 0)
        {
            auto firstQuote = trimmed.indexOf('"');
            auto lastQuote = trimmed.lastIndexOf('"');
            
            if (firstQuote != -1 && lastQuote != -1 && firstQuote < lastQuote)
            {
                string includeFile = trimmed[firstQuote + 1 .. lastQuote];
                string fullPath = includeFile;
                
                if (currentFilePath.length > 0)
                {
                    fullPath = buildPath(dirName(currentFilePath), includeFile);
                }
                
                if (exists(fullPath))
                {
                    string includeSrc = readText(fullPath);
                    cleanLines ~= preprocessImpl(includeSrc, fullPath, macros);
                }
                else
                {
                    writeln("Error: can't find file \"" ~ includeFile ~ "\"");
                    return "";
                }
            }
            continue;
        }
        
        cleanLines ~= line;
    }
    
    string result = cleanLines.join("\n");
    
    foreach(name, value; macros)
        result = result.replace(name, value);
        
    return result;
}
