/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module preprocessor;

import std.stdio;
import std.string: splitLines, strip, indexOf, lastIndexOf, replace;
import std.array: join, split;
import std.file: readText, exists;
import std.path: dirName, buildPath;
import std.ascii: isAlpha, isAlphaNum, isDigit;
import std.array: appender;

private bool isIdentStart(char c) { return c == '_' || isAlpha(c); }
private bool isIdentChar(char c)  { return c == '_' || isAlphaNum(c); }

// Expands macros in one line, skipping strings, char literals and // comments.
// `active` holds the macros currently being expanded, to stop infinite recursion.
private string expandMacros(string line, string[string] macros, ref bool[string] active)
{
    auto res = appender!string;
    size_t i = 0;

    while (i < line.length)
    {
        char c = line[i];

        if (c == '"' || c == '\'')                    // string / char literal
        {
            size_t start = i++;
            while (i < line.length && line[i] != c)
            {
                if (line[i] == '\\' && i + 1 < line.length)
                    i++;                              // skip escaped char
                i++;
            }
            if (i < line.length)
                i++;                                  // closing quote
            res ~= line[start .. i];
        }
        else if (c == '/' && i + 1 < line.length && line[i + 1] == '/')
        {
            res ~= line[i .. $];                      // rest is a comment
            break;
        }
        else if (isIdentStart(c))                     // whole identifier
        {
            size_t start = i;
            while (i < line.length && isIdentChar(line[i]))
                i++;
            string word = line[start .. i];

            auto value = word in macros;
            if (value !is null && word !in active)
            {
                active[word] = true;
                res ~= expandMacros(*value, macros, active);  // nested macros
                active.remove(word);
            }
            else
                res ~= word;
        }
        else if (isDigit(c))                          // number: 123, 0xFF, 1e5, 10u
        {
            size_t start = i;
            while (i < line.length && isIdentChar(line[i]))
                i++;
            res ~= line[start .. i];
        }
        else
        {
            res ~= c;
            i++;
        }
    }
    return res.data;
}

string preprocess(string src, string currentFilePath)
{
    string[string] globalMacros;
    return preprocessImpl(src, currentFilePath, globalMacros);
}

private string preprocessImpl(string src, string currentFilePath, ref string[string] macros)
{
    string[] lines = src.splitLines();
    string[] cleanLines;

    foreach (line; lines)
    {
        auto trimmed = line.strip();

        if (trimmed.indexOf("#define") == 0)
        {
            auto rest = trimmed["#define".length .. $].strip();
            size_t n = 0;
            while (n < rest.length && isIdentChar(rest[n]))
                n++;
            if (n > 0)
                macros[rest[0 .. n]] = rest[n .. $].strip();   // value may be empty or multi-word
            continue;
        }

        if (trimmed.indexOf("#undef") == 0)
        {
            macros.remove(trimmed["#undef".length .. $].strip());
            continue;
        }

        if (trimmed.indexOf("#include") == 0)
        {
            // ... unchanged; the included text is already expanded,
            // so don't expand it again ...
            continue;
        }

        bool[string] active;
        cleanLines ~= expandMacros(line, macros, active);
    }

    return cleanLines.join("\n");   // no global replace loop at the end
}
