/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Generate PSX.EXE from machine code.
 */
module psxexe;

import utils;

enum uint RAM_BASE = 0x80000000;
enum uint RAM_SIZE = 2 * 1024 * 1024;
enum uint BIOS_SIZE = 64 * 1024;
enum uint HEADER_SIZE = 2 * 1024;
enum uint LOAD_ADDR = RAM_BASE + BIOS_SIZE;
enum uint HEADER_ADDR = LOAD_ADDR - HEADER_SIZE;
enum uint RAM = LOAD_ADDR;
enum uint RAM_LENGTH  = RAM_SIZE - BIOS_SIZE;
enum uint STACK_ADDR = RAM_BASE + 0x001FFF00;

uint relocate(T)(T adr)
{
    return LOAD_ADDR + cast(uint)adr;
}

class PsxExe
{
    ubyte[] binary;
    
    this(ubyte[] code, uint relEntryPoint)
    {
        uint absEntryPoint = relocate(relEntryPoint);
        
        uint gp = 0x00000000; // $28 = 0
        uint codeSize = cast(uint)code.length;
        uint alignedCodeSize = aligned(codeSize, 2048);
        uint codePadding = alignedCodeSize - codeSize;
        uint stackOffset = 0;
        
        // Header
        binary ~= [0x50, 0x53, 0x2d, 0x58, 0x20, 0x45, 0x58, 0x45]; // "PS-X EXE"
        binary ~= new ubyte[8];
        binary ~= enc(absEntryPoint);
        binary ~= enc(gp);
        binary ~= enc(LOAD_ADDR);
        binary ~= enc(alignedCodeSize);
        binary ~= new ubyte[16];
        binary ~= enc(STACK_ADDR);
        binary ~= enc(stackOffset);
        binary ~= new ubyte[24];
        binary ~= new ubyte[HEADER_SIZE - binary.length];
        
        // Append code + padding to align to 2048 bytes
        binary ~= code;
        if (codePadding > 0)
            binary ~= new ubyte[codePadding];
    }
}
