/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module types;

enum Base { Void, Char, Short, Int, Struct }

struct CType
{
    Base base = Base.Int;
    int ptr = 0;
    bool uns = false; // Unsigned (describes the base type; for pointers: the pointee)
    string sname; // Base.Struct: struct tag name

    bool isPtr() const { return ptr > 0; }

    int size() const
    {
        if (ptr > 0)
            return 4;
        switch (base)
        {
            case Base.Short:
                return 2;
            case Base.Int:
                return 4;
            case Base.Struct:
                return structDefs[sname].size;
            default:
                return 1; // char, void (for void* arithmetic)
        }
    }

    CType deref() const
    {
        CType t = this;
        t.ptr--;
        return t;
    }

    CType addr() const
    {
        CType t = this;
        t.ptr++;
        return t;
    }
}

int elemSize(CType t)
{
    return t.deref().size();
}

struct Field
{
    string name;
    CType ty; // element type for array fields
    int offset;
    bool isArray;
    int arrLen;
}

class StructDef
{
    string name;
    Field[] fields;
    int size;
    int align_ = 1;
    bool complete; // false while being defined / when only forward-referenced
}

StructDef[string] structDefs;

bool isStructVal(CType t)
{
    return t.ptr == 0 && t.base == Base.Struct;
}

int alignOf(CType t)
{
    if (t.ptr > 0)
        return 4;
    if (t.base == Base.Struct)
        return structDefs[t.sname].align_;
    return t.size();
}

/// 32-bit unsigned integer (the only integer type that is unsigned after promotion).
bool isUint(CType t)
{
    return t.ptr == 0 && t.base == Base.Int && t.uns;
}

/// Values compared as unsigned: uint and pointers.
bool isUnsCmp(CType t)
{
    return t.ptr > 0 || isUint(t);
}

/// Is operator `op` applied to operands of these types an unsigned operation?
bool opUnsigned(string op, CType lt, CType rt)
{
    switch (op)
    {
        case "<<":
        case ">>":
            return isUint(lt);
        case "/":
        case "%":
            return isUint(lt) || isUint(rt);
        case "<":
        case "<=":
        case ">":
        case ">=":
            return isUnsCmp(lt) || isUnsCmp(rt);
        default:
            return false;
    }
}
