/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module utils;

import std.bitmanip;
import std.string;
import std.conv: parse;

ushort hi16(uint w)
{
    return cast(ushort)(w >> 16);
}

ushort lo16(uint w)
{
    return cast(ushort)(w & 0x0000ffff);
}

uint aligned(uint value, uint alignment)
{
    return (value + (alignment - 1)) & ~(alignment - 1);
}

ubyte[] enc(uint w)
{
    return nativeToLittleEndian!uint(w).dup;
}

ubyte[] enc(uint[] ws)
{
    ubyte[] res;
    foreach(w; ws)
    {
        res ~= nativeToLittleEndian!uint(w);
    }
    return res;
}

long parseInt(string s)
{
    s = s.strip.toLower;
    if (s.length == 0)
        throw new Exception("Empty numeric literal");

    int base = 10;
    size_t start = 0;

    if (s.length > 2 && s[0] == '0')
    {
        if (s[1] == 'x') { base = 16; start = 2; }
        else if (s[1] == 'b') { base = 2; start = 2; }
        else if (s[1] == 'o') { base = 8; start = 2; }
    }

    string digits = s[start..$];

    bool negative = false;
    if (digits.length > 0 && (digits[0] == '-' || digits[0] == '+'))
    {
        negative = digits[0] == '-';
        digits = digits[1..$];
    }

    long value = parse!long(digits, base);
    return negative ? -value : value;
}

ubyte[] parseEscapes(string s)
{
    ubyte[] result;
    size_t i = 0;

    while (i < s.length)
    {
        if (s[i] == '\\' && i + 1 < s.length)
        {
            i++;
            switch(s[i])
            {
                case 'n': result ~= cast(ubyte)'\n'; break;
                case 'r': result ~= cast(ubyte)'\r'; break;
                case 't': result ~= cast(ubyte)'\t'; break;
                case '\\': result ~= cast(ubyte)'\\'; break;
                case '"': result ~= cast(ubyte)'"'; break;
                case '0': result ~= cast(ubyte)0; break;
                default:
                    result ~= cast(ubyte)s[i];
            }
        }
        else
        {
            result ~= cast(ubyte)s[i];
        }
        i++;
    }

    return result;
}
