/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module exec;

import std.process: spawnProcess, wait, escapeShellCommand, Config, ProcessException;
import std.stdio: stdin, stdout, stderr;
import std.conv: to;

import errors;
import log;

/// Runs an external program directly (no shell) with the console streams
/// inherited, and returns its exit code. Throws only if it cannot be started.
int run(const(string)[] argv, string workDir = null)
{
    verbose("$ " ~ escapeShellCommand(argv));
    try
    {
        auto pid = spawnProcess(argv, stdin, stdout, stderr, null, Config.none, workDir);
        return wait(pid);
    }
    catch (ProcessException e)
    {
        throw new RetrobuildException("Cannot execute \"" ~ argv[0] ~ "\": " ~ e.msg);
    }
}

/// Like run(), but a non-zero exit code becomes a RetrobuildException
/// with ExitCode.toolFailed. `label` names the program in the message.
void runChecked(const(string)[] argv, string workDir, string label)
{
    int code = run(argv, workDir);
    if (code != 0)
        throw new RetrobuildException(
            label ~ " failed with exit code " ~ code.to!string, ExitCode.toolFailed);
}
