/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module main;

import std.algorithm: canFind;
import std.file: FileException, chdir;
import std.getopt: GetOptException, GetoptResult, config, getopt;
import std.path: setExtension;
import std.stdio: writeln;

import errors;
import log;
import manifest;
import pipeline;

enum versionString = "0.1.0";

private immutable string[] plannedCommands = ["init", "clean", "doctor"];
private immutable string[] knownCommands   = ["build", "compile", "iso", "cu2"];

private void printUsage()
{
    writeln(
`Retrobuild ` ~ versionString ~ ` - build automation system for the Retrolang SDK

Usage: retrobuild [options] [command]

Commands:
  build (default)   Run the full pipeline: compile, ISO, CU2
  compile           Compile the source into the executable only
  iso               Build the CD-ROM image from an existing executable
  cu2 <file.cue>    Convert a CUE sheet to CU2 (no project needed)

Options:
  -C <dir>          Run as if started in <dir>
  -m <file>         Use a specific manifest file
  -o <file>         Output file for the cu2 command (default: <cue>.cu2)
  -v, --verbose     Print every external command line
  -q, --quiet       Print errors only
      --no-iso      Skip the CD-ROM image and CU2 stages
      --no-cu2      Skip the CU2 stage
      --version     Print version and exit
  -h, --help        Show this help`);
}

int main(string[] args)
{
    try
        return run(args);
    catch (RetrobuildException e)
    {
        error(e.msg);
        return e.exitCode;
    }
    catch (Exception e)
    {
        error(e.msg);
        return ExitCode.failure;
    }
}

private int run(string[] args)
{
    string dir, manifestPath, outputPath;
    bool beVerbose, beQuiet, showVersion, noIso, noCu2;
    GetoptResult parsed;

    try
    {
        parsed = getopt(args, config.caseSensitive,
            "C",         "Run as if started in <dir>",    &dir,
            "m",         "Use a specific manifest file",  &manifestPath,
            "o",         "Output file for cu2",           &outputPath,
            "verbose|v", "Print every external command",  &beVerbose,
            "quiet|q",   "Print errors only",             &beQuiet,
            "no-iso",    "Skip the CD-ROM image stage",   &noIso,
            "no-cu2",    "Skip the CU2 stage",            &noCu2,
            "version",   "Print version and exit",        &showVersion);
    }
    catch (GetOptException e)
        throw new RetrobuildException(e.msg ~ " (see --help)", ExitCode.usage);

    if (parsed.helpWanted)
    {
        printUsage();
        return ExitCode.ok;
    }
    if (showVersion)
    {
        writeln("retrobuild ", versionString);
        return ExitCode.ok;
    }
    if (beVerbose && beQuiet)
        throw new RetrobuildException("--verbose and --quiet are mutually exclusive", ExitCode.usage);

    verbosity = beVerbose ? Verbosity.verbose : beQuiet ? Verbosity.quiet : Verbosity.normal;

    // args[0] is the program name; the rest are positional arguments.
    string command = args.length > 1 ? args[1] : "build";

    if (plannedCommands.canFind(command))
        throw new RetrobuildException("Command \"" ~ command ~ "\" is not implemented yet", ExitCode.usage);
    if (!knownCommands.canFind(command))
        throw new RetrobuildException("Unknown command \"" ~ command ~ "\" (see --help)", ExitCode.usage);

    if (command == "cu2")
    {
        if (args.length != 3)
            throw new RetrobuildException(
                "Usage: retrobuild cu2 <file.cue> [-o <file.cu2>]", ExitCode.usage);
    }
    else
    {
        if (args.length > 2)
            throw new RetrobuildException("Unexpected argument \"" ~ args[2] ~ "\" (see --help)", ExitCode.usage);
        if (outputPath.length)
            throw new RetrobuildException("-o is only valid with the cu2 command", ExitCode.usage);
    }

    if (dir.length)
    {
        try
            chdir(dir);
        catch (FileException e)
            throw new RetrobuildException("Cannot change directory to \"" ~ dir ~ "\": " ~ e.msg);
    }

    // Standalone: needs no project and no manifest.
    if (command == "cu2")
    {
        auto cue = args[2];
        auto output = outputPath.length ? outputPath : setExtension(cue, ".cu2");
        generateCu2(cue, output);
        info("Generated " ~ output);
        return ExitCode.ok;
    }

    auto m = loadManifest(manifestPath);

    switch (command)
    {
        case "compile":
            compileStage(m);
            break;
        case "iso":
            isoStage(m, true);
            break;
        case "build":
            buildPipeline(m, noIso, noCu2);
            break;
        default:
            assert(0);
    }
    return ExitCode.ok;
}
