/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module pipeline;

import std.algorithm: any;
import std.file: FileException, exists, isDir, mkdirRecurse, write;
import std.path: absolutePath, buildNormalizedPath, dirName, isDirSeparator, relativePath;

import cu2;
import errors;
import exec;
import log;
import manifest;
import tools;

/// Path shown to the user, relative to the project directory.
private string display(ref const Manifest m, string path)
{
    return relativePath(path, m.baseDir);
}

/// Runs the commands configured for a hook (e.g. "pre_compile"), if any.
/// Each command runs in its own working directory (default: the project directory).
void runHooks(Manifest m, string hookName)
{
    auto commands = hookName in m.hooks;
    if (commands is null)
        return;

    foreach (hook; *commands)
    {
        if (!isDir(hook.cwd))
            throw new RetrobuildException(
                "Hook \"" ~ hookName ~ "\": working directory not found: " ~ display(m, hook.cwd));

        verbose("Running hook " ~ hookName ~ " (in " ~ display(m, hook.cwd) ~ ")");

        // A program path with a directory part is relative to the hook's
        // directory on every platform. Bare names are looked up the usual way
        // (PATH; on Windows also use "cmd /c" for .bat files).
        auto argv = hook.argv.dup;
        if (argv[0].any!isDirSeparator)
            argv[0] = buildNormalizedPath(absolutePath(argv[0], hook.cwd));

        runChecked(argv, hook.cwd, "Hook \"" ~ hookName ~ "\" (" ~ hook.argv[0] ~ ")");
    }
}

/// Stage 1: compile the entry source into the PS1 executable.
void compileStage(Manifest m)
{
    // Fail fast on a missing compiler, before any hook runs.
    auto rlc = requireTool(rlcTool, m.toolPaths);

    runHooks(m, "pre_compile");

    // Checked after pre_compile on purpose: a hook may generate the source.
    if (!exists(m.source))
        throw new RetrobuildException("Source file not found: " ~ display(m, m.source));

    info("Compiling " ~ display(m, m.executable) ~ "...");
    mkdirRecurse(dirName(m.executable));

    string[] argv = [rlc.path] ~ m.rlcArgs ~ ["-o", m.executable, m.source];
    runChecked(argv, m.baseDir, "rlc");

    runHooks(m, "post_compile");
}

/// Stage 2: pack the executable into a CD-ROM image with mkpsxiso.
///
/// If `required` is false (full pipeline) a missing mkpsxiso is only a
/// warning and the function returns false, meaning "image not built".
/// If `required` is true (explicit `iso` command) it is an error.
bool isoStage(Manifest m, bool required)
{
    auto mk = required
        ? requireTool(mkpsxisoTool, m.toolPaths)
        : optionalTool(mkpsxisoTool, m.toolPaths);

    if (!mk.found)
    {
        warning("mkpsxiso not found, omitting CD-ROM image generation");
        return false;
    }

    runHooks(m, "pre_iso");

    if (!exists(m.executable))
        throw new RetrobuildException(
            "Executable not found: " ~ display(m, m.executable) ~ " (run \"retrobuild compile\" first)");
    if (!exists(m.isoXml))
        throw new RetrobuildException("ISO description not found: " ~ display(m, m.isoXml));

    info("Building CD-ROM image...");
    runChecked([mk.path, "-y", m.isoXml], m.baseDir, "mkpsxiso");

    if (!exists(m.cue))
        warning("mkpsxiso did not produce " ~ display(m, m.cue)
            ~ "; check that \"cue\" in the manifest matches iso.xml");

    runHooks(m, "post_iso");
    return true;
}

/// Converts a CUE sheet to CU2. Shared by the cu2 stage and the `cu2` command.
void generateCu2(string cuePath, string cu2Path)
{
    Cu2Result result;
    try
        result = convertCueFile(cuePath);
    catch (Cu2Exception e)
        throw new RetrobuildException("Cannot generate CU2 from " ~ cuePath ~ ": " ~ e.msg);

    foreach (w; result.warnings)
        warning(w);

    try
        write(cu2Path, result.text);
    catch (FileException e)
        throw new RetrobuildException("Could not write " ~ cu2Path ~ ": " ~ e.msg);
}

/// Stage 3: generate the CU2 sector index for PSIO from the CUE sheet.
void cu2Stage(Manifest m)
{
    runHooks(m, "pre_cu2");

    if (!exists(m.cue))
        throw new RetrobuildException(
            "CUE sheet not found: " ~ display(m, m.cue) ~ " (run \"retrobuild iso\" first)");

    info("Generating CU2 for PSIO...");
    generateCu2(m.cue, m.cu2);
    info("Generated " ~ display(m, m.cu2));

    runHooks(m, "post_cu2");
}

/// The full pipeline: compile, ISO, CU2.
void buildPipeline(Manifest m, bool noIso, bool noCu2)
{
    compileStage(m);
    if (noIso)
        return;
    if (!isoStage(m, false))
        return; // mkpsxiso missing: warning already printed, compiled exe only
    if (noCu2 || !exists(m.cue))
        return; // no CUE sheet: isoStage already warned
    cu2Stage(m);
}
