/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module disasm;

import std.stdio;
import std.format : format;
import mips;
import bios;

class MipsDisassembler
{
    public:
    
    /// text:     words to disassemble
    /// baseAddr: address of text[0]
    /// entry:    if given, only code reachable from this address is disassembled
    ///           as code, everything else is printed as data. If uint.max,
    ///           everything is disassembled linearly.
    this(uint[] text, uint baseAddr = 0, uint entry = uint.max)
    {
        this.text = text;
        this.baseAddr = baseAddr;
        
        if (entry == uint.max)
        {
            disassembleLinear();
        }
        else
        {
            traceCode(entry);
            disassembleTraced();
        }
    }
    
    protected:
    
    uint[] text;
    uint baseAddr;
    bool[] isCode;
    
    uint addrOf(size_t i)
    {
        return baseAddr + cast(uint)(i * 4);
    }
    
    // ---------------------------------------------------------------
    // Output drivers
    // ---------------------------------------------------------------
    
    void disassembleLinear()
    {
        foreach (i, instr; text)
            printInstruction(addrOf(i), instr);
    }
    
    void disassembleTraced()
    {
        size_t i = 0;
        while (i < text.length)
        {
            if (isCode[i])
            {
                printInstruction(addrOf(i), text[i]);
                i++;
            }
            else
            {
                size_t end = i;
                while (end < text.length && !isCode[end])
                    end++;
                printData(i, end);
                i = end;
            }
        }
    }
    
    void printInstruction(uint pc, uint instr)
    {
        size_t idx = (pc - baseAddr) / 4;
        writefln("  %08x: %08x  %s%s", pc, instr, disasmInstruction(pc, instr),
                 biosAnnotation(idx));
    }
    
    void printData(size_t start, size_t end)
    {
        size_t i = start;
        while (i < end)
        {
            size_t j = i;
            while (j < end && text[j] == 0)
                j++;
            
            if (j - i >= 4)
            {
                writefln("  %08x: ... %d words of zeros (0x%x bytes)",
                         addrOf(i), j - i, (j - i) * 4);
                i = j;
            }
            else
            {
                writefln("  %08x: %08x  .word 0x%08x%s",
                         addrOf(i), text[i], text[i], asciiHint(text[i]));
                i++;
            }
        }
    }
    
    string asciiHint(uint w)
    {
        string s;
        bool anyPrintable = false;
        foreach (k; 0 .. 4)
        {
            ubyte b = cast(ubyte)((w >> (8 * k)) & 0xff);
            if (b >= 0x20 && b < 0x7f)
            {
                s ~= cast(char)b;
                anyPrintable = true;
            }
            else if (b == '\n')
                s ~= "\\n";
            else if (b == 0)
                s ~= "\\0";
            else
                return "";
        }
        return anyPrintable ? "  ; \"" ~ s ~ "\"" : "";
    }
    
    // ---------------------------------------------------------------
    // Control flow tracing
    // ---------------------------------------------------------------
    
    static uint jumpTarget(uint pc, uint instr)
    {
        return ((pc + 4) & 0xf0000000) | ((instr & 0x03ffffff) << 2);
    }
    
    static uint branchTarget(uint pc, uint instr)
    {
        int offset = cast(int)cast(short)(instr & 0xffff);
        return pc + 4 + cast(uint)(offset * 4);
    }
    
    static bool isBranchOpcode(ubyte op)
    {
        // REGIMM (1), BEQ, BNE, BLEZ, BGTZ (4..7)
        return op == 1 || (op >= 4 && op <= 7);
    }
    
    void markCode(uint addr)
    {
        if (addr < baseAddr || ((addr - baseAddr) & 3) != 0)
            return;
        size_t i = (addr - baseAddr) / 4;
        if (i < text.length)
            isCode[i] = true;
    }
    
    void traceCode(uint entry)
    {
        isCode = new bool[text.length];
        uint[] work = [entry];
        
        while (work.length > 0)
        {
            uint addr = work[$ - 1];
            work = work[0 .. $ - 1];
            
            for (;;)
            {
                if (addr < baseAddr || ((addr - baseAddr) & 3) != 0)
                    break;
                size_t i = (addr - baseAddr) / 4;
                if (i >= text.length || isCode[i])
                    break;
                
                isCode[i] = true;
                uint instr = text[i];
                ubyte op = cast(ubyte)(instr >> 26);
                ubyte rs = cast(ubyte)((instr >> 21) & 0x1f);
                ubyte rt = cast(ubyte)((instr >> 16) & 0x1f);
                
                bool hasDelaySlot = false;
                bool stop = false;
                
                if (op == 0)
                {
                    ubyte funct = cast(ubyte)(instr & 0x3f);
                    if (funct == 0x08)       // JR: no fall-through
                    {
                        hasDelaySlot = true;
                        stop = true;
                    }
                    else if (funct == 0x09)  // JALR: returns here
                    {
                        hasDelaySlot = true;
                    }
                }
                else if (op == 2 || op == 3) // J / JAL
                {
                    work ~= jumpTarget(addr, instr);
                    hasDelaySlot = true;
                    stop = (op == 2);
                }
                else if (isBranchOpcode(op))
                {
                    work ~= branchTarget(addr, instr);
                    hasDelaySlot = true;
                    // BEQ $x, $x and BGEZ $0 are unconditional
                    stop = (op == 4 && rs == rt) || (op == 1 && rs == 0 && rt == 1);
                }
                
                if (hasDelaySlot)
                    markCode(addr + 4);
                if (stop)
                    break;
                
                addr += hasDelaySlot ? 8 : 4;
            }
        }
    }
    
    // ---------------------------------------------------------------
    // Instruction decoding (returns the text after the address)
    // ---------------------------------------------------------------
    
    string disasmInstruction(uint pc, uint instr)
    {
        ubyte opcode = cast(ubyte)(instr >> 26);
        
        if (opcode == 0) // R-type
            return disasmRType(instr);
        else if (opcode == MipsInstr.J || opcode == MipsInstr.JAL)
            return disasmJump(pc, instr);
        else if (opcode == MipsInstr.COP0)
            return disasmCOP0(instr);
        else if (opcode == MipsInstr.COP2)
            return disasmCOP2(instr);
        else // I-type
            return disasmIType(pc, instr);
    }
    
    // TODO: use separate disasm function for each r-type instruction
    string disasmRType(uint instr)
    {
        ubyte funct = cast(ubyte)(instr & 0x3f);
        ubyte rs    = cast(ubyte)((instr >> 21) & 0x1f);
        ubyte rt    = cast(ubyte)((instr >> 16) & 0x1f);
        ubyte rd    = cast(ubyte)((instr >> 11) & 0x1f);
        ubyte shift = cast(ubyte)((instr >> 6)  & 0x1f);
        
        if (funct == MipsRType.JR)
            return format("%s $%s", cast(MipsRType)funct, rs);
        
        if (funct == MipsRType.JALR)
            return format("%s $%s, $%s", cast(MipsRType)funct, rd, rs);
        
        if (funct == MipsRType.SLL && rs == 0 && rt == 0 && rd == 0 && shift == 0)
            return "NOP";
        
        return format("%s $%s, $%s, %d($%s)", cast(MipsRType)funct, rd, rs, shift, rt);
    }
    
    string disasmIType(uint pc, uint instr)
    {
        ubyte opcode = cast(ubyte)(instr >> 26);
        ubyte rs    = cast(ubyte)((instr >> 21) & 0x1f);
        ubyte rt    = cast(ubyte)((instr >> 16) & 0x1f);
        short imm   = cast(short)(instr & 0xffff);
        
        if (opcode == MipsInstr.LUI)
            return format("%s $%s, 0x%04x", cast(MipsInstr)opcode, rt, imm);
        
        if (opcode == MipsInstr.BXX)
            return disasmRegimm(pc, instr);
        
        if (opcode == MipsInstr.BEQ || opcode == MipsInstr.BNE)
            return format("%s $%s, $%s, 0x%08x", cast(MipsInstr)opcode, rs, rt,
                          branchTarget(pc, instr));
        
        if (opcode == MipsInstr.BLEZ || opcode == MipsInstr.BGTZ)
            return format("%s $%s, 0x%08x", cast(MipsInstr)opcode, rs,
                          branchTarget(pc, instr));
        
        return format("%s $%s, $%s, 0x%04x", cast(MipsInstr)opcode, rt, rs, imm);
    }
    
    // REGIMM (opcode 1): the rt field selects the branch type
    string disasmRegimm(uint pc, uint instr)
    {
        ubyte rs  = cast(ubyte)((instr >> 21) & 0x1f);
        ubyte sub = cast(ubyte)((instr >> 16) & 0x1f);
        uint target = branchTarget(pc, instr);
        
        if (sub == MipsRegimm.BLTZ   || sub == MipsRegimm.BGEZ ||
            sub == MipsRegimm.BLTZAL || sub == MipsRegimm.BGEZAL)
            return format("%s $%s, 0x%08x", cast(MipsRegimm)sub, rs, target);
        
        return format("BXX $%s, 0x%02x, 0x%08x", rs, sub, target);
    }
    
    // ---------------------------------------------------------------
    // BIOS call annotation: "li $t2, 0xA0 / li $t1, N / jalr $t2"
    // ---------------------------------------------------------------
    
    string biosAnnotation(size_t idx)
    {
        uint instr = text[idx];
        if ((instr >> 26) != 0)
            return "";
        
        ubyte funct = cast(ubyte)(instr & 0x3f);
        ubyte rs    = cast(ubyte)((instr >> 21) & 0x1f);
        
        // JR / JALR through $t2 ($10)
        if ((funct != 0x08 && funct != 0x09) || rs != 10)
            return "";
        
        uint table;
        if (!findConst(idx, 10, false, table))
            return "";
        if (table != 0xa0 && table != 0xb0 && table != 0xc0)
            return "";
        
        // $t1 ($9) may be set in the delay slot
        uint func;
        int f = findConst(idx, 9, true, func) ? cast(int)func : -1;
        return "  ; " ~ biosCall(table, f);
    }
    
    // Find the constant most recently loaded into `reg` before text[idx]
    // (or in its delay slot), within the same basic block.
    bool findConst(size_t idx, ubyte reg, bool checkDelaySlot, out uint value)
    {
        if (checkDelaySlot && idx + 1 < text.length)
        {
            int r = constWrite(text[idx + 1], reg, value);
            if (r == 1) return true;
            if (r == 2) return false;
        }
        
        for (size_t k = 1; k <= 16 && k <= idx; k++)
        {
            size_t j = idx - k;
            if (isCode.length > 0 && !isCode[j])
                return false;
            
            uint ins = text[j];
            if (isControlFlow(ins))
                return false;
            
            int r = constWrite(ins, reg, value);
            if (r == 1) return true;
            if (r == 2) return false;
        }
        return false;
    }
    
    // 0: doesn't touch reg, 1: loads a constant into reg, 2: overwrites reg otherwise
    static int constWrite(uint ins, ubyte reg, ref uint value)
    {
        ubyte op = cast(ubyte)(ins >> 26);
        ubyte rs = cast(ubyte)((ins >> 21) & 0x1f);
        ubyte rt = cast(ubyte)((ins >> 16) & 0x1f);
        
        if (op == 8 || op == 9 || op == 13) // ADDI, ADDIU, ORI
        {
            if (rt != reg)
                return 0;
            if (rs != 0)
                return 2;
            value = (op == 13) ? (ins & 0xffff)
                               : cast(uint)cast(int)cast(short)(ins & 0xffff);
            return 1;
        }
        
        return writesReg(ins, reg) ? 2 : 0;
    }
    
    static bool writesReg(uint ins, ubyte reg)
    {
        ubyte op    = cast(ubyte)(ins >> 26);
        ubyte rs    = cast(ubyte)((ins >> 21) & 0x1f);
        ubyte rt    = cast(ubyte)((ins >> 16) & 0x1f);
        ubyte rd    = cast(ubyte)((ins >> 11) & 0x1f);
        ubyte funct = cast(ubyte)(ins & 0x3f);
        
        if (op == 0)
        {
            switch (funct)
            {
                case 0x08: case 0x0c: case 0x0d:             // JR, SYSCALL, BREAK
                case 0x11: case 0x13:                        // MTHI, MTLO
                case 0x18: case 0x19: case 0x1a: case 0x1b:  // MULT/DIV
                    return false;
                default:
                    return rd == reg;
            }
        }
        if (op == 3)                        // JAL
            return reg == 31;
        if (op >= 8 && op <= 15)            // ALU immediate
            return rt == reg;
        if (op == 0x10 || op == 0x12)       // MFC0/CFC0-style moves into rt
            return (rs == 0 || rs == 2) && rt == reg;
        if (op >= 0x20 && op <= 0x26)       // loads
            return rt == reg;
        return false;
    }
    
    static bool isControlFlow(uint ins)
    {
        ubyte op = cast(ubyte)(ins >> 26);
        if (op == 0)
        {
            ubyte funct = cast(ubyte)(ins & 0x3f);
            return funct == 0x08 || funct == 0x09;
        }
        return op == 2 || op == 3 || isBranchOpcode(op);
    }
    
    string disasmJump(uint pc, uint instr)
    {
        ubyte opcode = cast(ubyte)(instr >> 26);
        return format("%s 0x%08x", cast(MipsInstr)opcode, jumpTarget(pc, instr));
    }
    
    string disasmCOP0(uint instr)
    {
        ubyte op = cast(ubyte)((instr >> 21) & 0x1f);
        
        if (op == MipsCop0.MTC0 || op == MipsCop0.MFC0)
        {
            ubyte rt = cast(ubyte)((instr >> 16) & 0x1f);
            ubyte rd = cast(ubyte)((instr >> 11) & 0x1f);
            return format("%s $%s, $%s", cast(MipsCop0)op, rt, rd);
        }
        
        return format("%s", MipsInstr.COP0);
    }
    
    string disasmCOP2(uint instr)
    {
        ubyte op = cast(ubyte)((instr >> 21) & 0x1f);
        
        if (op == MipsCop2.MTC2 || op == MipsCop2.MFC2 ||
            op == MipsCop2.CTC2 || op == MipsCop2.CFC2)
        {
            ubyte rt = cast(ubyte)((instr >> 16) & 0x1f);
            ubyte rd = cast(ubyte)((instr >> 11) & 0x1f);
            return format("%s $%s, $%s", cast(MipsCop2)op, rt, rd);
        }
        
        return format("%s", MipsInstr.COP2);
    }
}
