/*
Copyright (c) 2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
import std.stdio;
import std.file;

import psyqobj;
import section;
import psxexe;
import disasm;

int main(string[] args)
{
    if (args.length < 2)
    {
        writeln("No input file specified.");
        return 1;
    }
    
    string objFilename = args[1];
    
    writefln("File: %s", objFilename);
    
    ubyte[] binary = cast(ubyte[])std.file.read(objFilename);
    if (binary.length < 8)
    {
        writeln("Unknown file type!");
        return 1;
    }
    
    string fileStart = cast(string)binary[0..8];
    if (fileStart[0..3] == "LNK")
    {
        // PsyQ object file
        writefln("LNK format object file");
        
        PsyqObject obj = new PsyqObject(binary);
        
        foreach(name, section; obj.sectionsByName)
        {
            if (section.data.length > 0)
            {
                writefln("Section %s (%s):", name, section.index);
                if (section.name == ".text")
                {
                    if (section.data.length > 0)
                    {
                        auto disassembler = new MipsDisassembler(cast(uint[])section.data);
                    }
                }
                else
                {
                    writefln("  \"%s\"", cast(string)section.data);
                }
            }
        }
        
        if (obj.parsed)
            return 0;
        else
            return 1;
    }
    else if (fileStart == "PS-X EXE")
    {
        PsxExe exe;
        try
            exe = new PsxExe(binary);
        catch (Exception e)
        {
            writefln("Invalid PSX-EXE: %s", e.msg);
            return 1;
        }

        writefln("PSX-EXE (%s)", exe.region);
        writefln("  Entry PC:  0x%08X", exe.pc);
        writefln("  GP:        0x%08X", exe.gp);
        writefln("  Load addr: 0x%08X", exe.loadAddr);
        writefln("  Text size: 0x%X bytes", exe.code.length * 4);
        if (exe.spBase != 0)
            writefln("  SP:        0x%08X", exe.spBase + exe.spOffset);
        if (exe.bssSize != 0)
            writefln("  BSS:       0x%08X (0x%X bytes)", exe.bssAddr, exe.bssSize);

        //auto disassembler = new MipsDisassembler(exe.trimmedCode.dup);
        auto disassembler = new MipsDisassembler(exe.code, exe.loadAddr, exe.pc);
        return 0;
    }
    else
    {
        writeln("Unknown file type!");
        return 1;
    }
}
