/*
Copyright (c) 2011-2026 Timur Gafarov, Martin Cejp, Vadim Lopatin

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * PNG image decoder.
 *
 * Copyright: Timur Gafarov, Martin Cejp, Vadim Lopatin 2011-2026.
 * License: $(LINK2 boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov, Martin Cejp, Vadim Lopatin
 */
module png;

import dlib.core.memory;
import dlib.core.stream;
import dlib.core.compound;
import dlib.coding.zlib;
import dlib.math.base;
import dlib.math.utils;
import logger;
import rgba8;

alias TextureBuffer = RGBA8TextureBuffer;

// uncomment this to see debug messages:
//version = PNGDebug;

immutable(ubyte)[8] PNGSignature = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];

// Standard chunks
immutable(ubyte)[4] IHDR = ['I', 'H', 'D', 'R']; // Image header
immutable(ubyte)[4] IEND = ['I', 'E', 'N', 'D']; // Image end
immutable(ubyte)[4] IDAT = ['I', 'D', 'A', 'T']; // Image data
immutable(ubyte)[4] PLTE = ['P', 'L', 'T', 'E']; // Palette
immutable(ubyte)[4] tRNS = ['t', 'R', 'N', 'S']; // Transparency
immutable(ubyte)[4] bKGD = ['b', 'K', 'G', 'D']; // Background color
immutable(ubyte)[4] tEXt = ['t', 'E', 'X', 't']; // Textual data (uncompressed)
immutable(ubyte)[4] zTXt = ['z', 'T', 'X', 't']; // Textual data (zlib compressed)
immutable(ubyte)[4] iTXt = ['i', 'T', 'X', 't']; // International text

// Extension chunks
immutable(ubyte)[4] oFFs = ['o', 'F', 'F', 's']; // Image offset
immutable(ubyte)[4] pCAL = ['p', 'C', 'A', 'L']; // Calibration of pixel values
immutable(ubyte)[4] sCAL = ['s', 'C', 'A', 'L']; // Physical scale of image subject
immutable(ubyte)[4] gIFg = ['g', 'I', 'F', 'g']; // GIF graphic control
immutable(ubyte)[4] gIFx = ['g', 'I', 'F', 'x']; // GIF application
immutable(ubyte)[4] gIFt = ['g', 'I', 'F', 't']; // GIF plain text (deprecated)
immutable(ubyte)[4] fRAc = ['f', 'R', 'A', 'c']; // Fractal image parameters
immutable(ubyte)[4] sTER = ['s', 'T', 'E', 'R']; // Indicator of stereo image
immutable(ubyte)[4] dSIG = ['d', 'S', 'I', 'G']; // Digital signature

// ImageMagick chunks
immutable(ubyte)[4] vpAg = ['v', 'p', 'A', 'g']; // VirtualPage Tags

// APNG chunks
immutable(ubyte)[4] acTL = ['a', 'c', 'T', 'L']; // Animation control
immutable(ubyte)[4] fcTL = ['f', 'c', 'T', 'L']; // Frame control
immutable(ubyte)[4] fdAT = ['f', 'd', 'A', 'T']; // Frame data

enum ColorType: ubyte
{
    Grayscale = 0,      // allowed bit depths: 1, 2, 4, 8 and 16
    RGB = 2,            // allowed bit depths: 8 and 16
    Palette = 3,        // allowed bit depths: 1, 2, 4 and 8
    GrayscaleAlpha = 4, // allowed bit depths: 8 and 16
    RGBA = 6,           // allowed bit depths: 8 and 16
    Any = 7             // one of the above
}

enum FilterMethod: ubyte
{
    None = 0,
    Sub = 1,
    Up = 2,
    Average = 3,
    Paeth = 4
}

struct PNGChunk
{
    uint length;
    ubyte[4] type;
    ubyte[] data;
    uint crc;

    void free()
    {
        if (data.ptr)
            Delete(data);
    }
}

struct PNGHeader
{
    union
    {
        struct
        {
            uint width;
            uint height;
            ubyte bitDepth;
            ubyte colorType;
            ubyte compressionMethod;
            ubyte filterMethod;
            ubyte interlaceMethod;
        };
        ubyte[13] bytes;
    }
}

struct OffsetChunk
{
    int posX;
    int posY;
    ubyte unitSpecifier;

    void readFromBuffer(ubyte[] data)
    {
        *(&posX) = *(cast(int*)data.ptr);
        posX = bigEndian(posX);
        *(&posY) = *(cast(int*)(data.ptr+4));
        posY = bigEndian(posY);
        *(&unitSpecifier) = *(data.ptr+8);
    }
}

struct PNGImage
{
    // Common PNG data
    PNGHeader hdr;
    uint numChannels;
    uint bitDepth;
    uint bytesPerChannel;

    // Data for indexed PNG
    ubyte[] palette;
    ubyte[] transparency;
    uint paletteSize = 0;
    
    // Offset
    OffsetChunk offset;

    // 
    ZlibDecoder decoder;
    
    void initDecoder()
    {
        ubyte[] buffer;

        if (decoder.buffer.length)
        {
            buffer = decoder.buffer;
        }
        else
        {
            uint bufferLength = hdr.width * hdr.height * numChannels * bytesPerChannel + hdr.height;
            buffer = New!(ubyte[])(bufferLength);
        }

        decoder = ZlibDecoder(buffer);
    }
    
    void free()
    {
        if (decoder.buffer.length)
            Delete(decoder.buffer);

        if (palette.length)
            Delete(palette);

        if (transparency.length)
            Delete(transparency);
    }
}

/**
 * Decodes PNG image from the stream and fills a `TextureBuffer`.
 * The output is guaranteed to be RGBA8.
 */
bool loadPNG(InputStream istrm, TextureBuffer* buffer)
{
    PNGImage png;
    
    void finalize()
    {
        png.free();
    }
    
    bool error(string errorMsg)
    {
        finalize();
        logError(errorMsg);
        return false;
    }
    
    ubyte[8] signatureBuffer;

    if (!istrm.fillArray(signatureBuffer))
        return error("loadPNG error: signature check failed");

    version(PNGDebug)
    {
        logDebug("PNG Signature: ", signatureBuffer);
    }
    
    bool endChunk = false;
    while (!endChunk && istrm.readable)
    {
        PNGChunk chunk;
        auto res = readChunk(&png, istrm, &chunk);

        if (!res[0])
        {
            chunk.free();
            return error(res[1]);
        }
        else
        {
            if (chunk.type == IEND)
            {
                endChunk = true;
            }
            else if (chunk.type == IHDR)
            {
                res = readIHDR(&png, &chunk);
                if (!res[0])
                    return error(res[1]);
                
                png.initDecoder();
            }
            else if (chunk.type == IDAT)
            {
                png.decoder.decode(chunk.data);
            }
            else if (chunk.type == PLTE)
            {
                png.palette = New!(ubyte[])(chunk.data.length);
                png.palette[] = chunk.data[];
            }
            else if (chunk.type == tRNS)
            {
                png.transparency = New!(ubyte[])(chunk.data.length);
                png.transparency[] = chunk.data[];

                if (png.hdr.colorType == ColorType.Palette)
                {
                    if (png.transparency.length > 0)
                        png.numChannels = 4;
                    else
                        png.numChannels = 3;
                }

                version(PNGDebug)
                {
                    logDebug("transparency.length = ", png.transparency.length);
                }

                png.initDecoder();
            }
            else if (chunk.type == oFFs)
            {
                png.offset.readFromBuffer(chunk.data);

                version(PNGDebug)
                {
                    logDebug("posX = ", png.offset.posX);
                    logDebug("posY = ", png.offset.posY);
                    logDebug("unitSpecifier = ", png.offset.unitSpecifier);
                }
            }
            
            chunk.free();

            version(PNGDebug)
            {
                logDebug("----------------");
            }
        }

        if (png.decoder.hasEnded)
        {
            res = readImage(&png, buffer);
            if (!res[0])
                return error(res[1]);

            break;
        }
    }
    
    finalize();
    return true;
}

pragma(inline, true)
private Compound!(bool, string) err(string msg)
{
    return compound(false, msg);
}

pragma(inline, true)
private Compound!(bool, string) suc()
{
    return compound(true, "");
}

/// Reads chunk data from a PNG stream.
private Compound!(bool, string) readChunk(PNGImage* png, InputStream istrm, PNGChunk* chunk)
{
    bool readLen = istrm.readBE!uint(&chunk.length);
    bool readType = istrm.fillArray(chunk.type);
    
    if (!readLen || !readType)
    {
        return err("loadPNG error: failed to read chunk header, invalid PNG stream");
    }

    version(PNGDebug) logDebug("Chunk length = ", chunk.length);
    version(PNGDebug) logDebug("Chunk type = ", cast(char[])chunk.type);

    if (chunk.length > 0)
    {
        chunk.data = New!(ubyte[])(chunk.length);
        if (!istrm.fillArray(chunk.data))
        {
            return err("loadPNG error: failed to read chunk data, invalid PNG stream");
        }
    }

    version(PNGDebug) logDebug("Chunk data.length = ", chunk.data.length);

    if (!istrm.readBE!uint(&chunk.crc))
    {
        return err("loadPNG error: failed to read chunk CRC, invalid PNG stream");
    }

    return suc();
}

/// Parses IHDR chunk and fills PNGHeader struct.
Compound!(bool, string) readIHDR(PNGImage* png, PNGChunk* chunk)
{
    PNGHeader* hdr = &png.hdr;

    if (chunk.data.length < hdr.bytes.length)
        return err("loadPNG error: illegal header chunk");

    hdr.bytes[] = chunk.data[0..hdr.bytes.length];
    hdr.width = bigEndian(hdr.width);
    hdr.height = bigEndian(hdr.height);

    version(PNGDebug)
    {
        logDebug("width = ", hdr.width);
        logDebug("height = ", hdr.height);
        logDebug("bitDepth = ", hdr.bitDepth);
        logDebug("colorType = ", hdr.colorType);
        logDebug("compressionMethod = ", hdr.compressionMethod);
        logDebug("filterMethod = ", hdr.filterMethod);
        logDebug("interlaceMethod = ", hdr.interlaceMethod);
    }

    bool supportedIndexed =
        (hdr.colorType == ColorType.Palette) &&
        (hdr.bitDepth == 1 ||
         hdr.bitDepth == 2 ||
         hdr.bitDepth == 4 ||
         hdr.bitDepth == 8);

    if (hdr.bitDepth != 8 && hdr.bitDepth != 16 && !supportedIndexed)
        return err("loadPNG error: unsupported bit depth");

    if (hdr.compressionMethod != 0)
        return err("loadPNG error: unsupported compression method");

    if (hdr.filterMethod != 0)
        return err("loadPNG error: unsupported filter method");

    if (hdr.interlaceMethod != 0)
        return err("loadPNG error: interlacing is not supported");

    if (hdr.colorType == ColorType.Grayscale)
        png.numChannels = 1;
    else if (hdr.colorType == ColorType.GrayscaleAlpha)
        png.numChannels = 2;
    else if (hdr.colorType == ColorType.RGB)
        png.numChannels = 3;
    else if (hdr.colorType == ColorType.RGBA)
        png.numChannels = 4;
    else if (hdr.colorType == ColorType.Palette)
    {
        if (png.transparency.length > 0)
            png.numChannels = 4;
        else
            png.numChannels = 3;
    }
    else
        return err("loadPNG error: unsupported color type");

    if (hdr.colorType == ColorType.Palette)
        png.bitDepth = 8;
    else
        png.bitDepth = hdr.bitDepth;

    png.bytesPerChannel = png.bitDepth / 8;

    version(PNGDebug)
    {
        logDebug("bytesPerChannel = ", png.bytesPerChannel);
    }

    return suc();
}

/// Unfilters PNG image and reads the data to TextureBuffer, converting to RGBA8 if necessary.
private Compound!(bool, string) readImage(PNGImage* png, TextureBuffer* buffer)
{
    ubyte[] decodedBuffer = png.decoder.buffer;
    version(PNGDebug) logDebug("decodedBuffer.length = ", decodedBuffer.length);

    bool indexed = (png.hdr.colorType == ColorType.Palette);

    uint calculatedImageSize;
    if (indexed)
        calculatedImageSize = (png.hdr.width * png.hdr.height * png.hdr.bitDepth) / 8 + png.hdr.height;
    else
        calculatedImageSize = png.hdr.width * png.hdr.height * (png.hdr.bitDepth / 8) * png.numChannels + png.hdr.height;

    if (decodedBuffer.length != calculatedImageSize)
    {
        return err("loadPNG error: image size and data mismatch");
    }

    size_t filteredBufferSize = calculatedImageSize - png.hdr.height;
    ubyte[] filteredBuffer = New!(ubyte[])(filteredBufferSize);
    scope(exit)
    {
        if (filteredBuffer.length)
            Delete(filteredBuffer);
    }

    version(PNGDebug)
    {
        logDebug("calculatedImageSize = ", calculatedImageSize);
        logDebug("filteredBufferSize = ", filteredBufferSize);
    }

    // Apply filtering to the image data
    if (!filter(png, indexed, decodedBuffer, filteredBuffer))
        return err("loadPNG error: invalid scanline filter");

    // Prepare the texture buffer
    //buffer.format.type = SDL_GPU_TEXTURETYPE_2D;
    //buffer.format.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
    buffer.width = png.hdr.width;
    buffer.height = png.hdr.height;
    
    size_t bufferSize = buffer.width * buffer.height * 4;
    
    version(PNGDebug)
    {
        logDebug("bufferSize = ", bufferSize);
    }
    
    buffer.data = New!(ubyte[])(bufferSize);
    auto pdata = buffer.data;

    // If a palette is used, substitute target colors
    if (indexed)
    {
        if (png.palette.length == 0)
            return err("loadPNG error: palette chunk not found");
        
        if (png.hdr.bitDepth == 8)
        {
            for (int i = 0; i < filteredBuffer.length; ++i)
            {
                ubyte index = filteredBuffer[i];
                
                size_t pixelOffset = i * 4;
                pdata[pixelOffset + 0] = png.palette[index * 3 + 0];
                pdata[pixelOffset + 1] = png.palette[index * 3 + 1];
                pdata[pixelOffset + 2] = png.palette[index * 3 + 2];
                
                if (png.transparency.length > 0)
                    pdata[pixelOffset + 3] =
                        index < png.transparency.length ? png.transparency[index] : 255;
                else
                    pdata[pixelOffset + 3] = 255;
            }
        }
        else // bit depths 1, 2, 4
        {
            int srcindex = 0;
            int srcshift = 8 - png.hdr.bitDepth;
            ubyte mask = cast(ubyte)((1 << png.hdr.bitDepth) - 1);
            int sz = png.hdr.width * png.hdr.height;
            for (int dstindex = 0; dstindex < sz; dstindex++)
            {
                auto index = ((filteredBuffer[srcindex] >> srcshift) & mask);
                
                size_t pixelOffset = dstindex * 4;
                pdata[pixelOffset + 0] = png.palette[index * 3 + 0];
                pdata[pixelOffset + 1] = png.palette[index * 3 + 1];
                pdata[pixelOffset + 2] = png.palette[index * 3 + 2];

                if (png.transparency.length > 0)
                    pdata[pixelOffset + 3] =
                        index < png.transparency.length ? png.transparency[index] : 255;
                else
                    pdata[pixelOffset + 3] = 255;

                if (srcshift <= 0)
                {
                    srcshift = 8 - png.hdr.bitDepth;
                    srcindex++;
                }
                else
                {
                    srcshift -= png.hdr.bitDepth;
                }
            }
        }
    }
    else
    {
        // Convert from unusual formats to RGBA8
        
        const(size_t) width = png.hdr.width;
        const(size_t) height = png.hdr.height;
        const(uint) bitDepth = png.hdr.bitDepth;
        const size_t numPixels = width * height;
        
        if (png.numChannels != 4)
        {
            // Convert to RGBA
            logDebug("Converting from ", cast(ColorType)png.hdr.colorType, bitDepth, " to RGBA8");
            
            const(size_t) bytesPerSample = (bitDepth == 16) ? 2 : 1;
            const(size_t) srcPixelStride = png.numChannels * bytesPerSample;
            const(size_t) dstPixelStride = 4;
            
            if (bitDepth == 8)
            {
                switch (png.hdr.colorType)
                {
                    case ColorType.Grayscale:
                        for (size_t i = 0; i < numPixels; i++)
                        {
                            ubyte g = filteredBuffer[i * 1];
                            pdata[i * 4 + 0] = g;
                            pdata[i * 4 + 1] = g;
                            pdata[i * 4 + 2] = g;
                            pdata[i * 4 + 3] = 255;
                        }
                        break;

                    case ColorType.GrayscaleAlpha:
                        for (size_t i = 0; i < numPixels; i++)
                        {
                            ubyte g = filteredBuffer[i * 2 + 0];
                            ubyte a = filteredBuffer[i * 2 + 1];
                            pdata[i * 4 + 0] = g;
                            pdata[i * 4 + 1] = g;
                            pdata[i * 4 + 2] = g;
                            pdata[i * 4 + 3] = a;
                        }
                        break;

                    case ColorType.RGB:
                        for (size_t i = 0; i < numPixels; i++)
                        {
                            pdata[i * 4 + 0] = filteredBuffer[i * 3 + 0];
                            pdata[i * 4 + 1] = filteredBuffer[i * 3 + 1];
                            pdata[i * 4 + 2] = filteredBuffer[i * 3 + 2];
                            pdata[i * 4 + 3] = 255;
                        }
                        break;
                    
                    default:
                        break;
                }
            }
            else if (bitDepth == 16)
            {
                switch (png.hdr.colorType)
                {
                    case ColorType.Grayscale:
                        for (size_t i = 0; i < numPixels; i++)
                        {
                            ubyte g = filteredBuffer[i * 2 + 0]; 
                            pdata[i * 4 + 0] = g;
                            pdata[i * 4 + 1] = g;
                            pdata[i * 4 + 2] = g;
                            pdata[i * 4 + 3] = 255;
                        }
                        break;

                    case ColorType.GrayscaleAlpha:
                        for (size_t i = 0; i < numPixels; i++)
                        {
                            ubyte g = filteredBuffer[i * 4 + 0];
                            ubyte a = filteredBuffer[i * 4 + 2];
                            pdata[i * 4 + 0] = g;
                            pdata[i * 4 + 1] = g;
                            pdata[i * 4 + 2] = g;
                            pdata[i * 4 + 3] = a;
                        }
                        break;

                    case ColorType.RGB:
                        for (size_t i = 0; i < numPixels; i++)
                        {
                            size_t srcIdx = i * 6;
                            pdata[i * 4 + 0] = filteredBuffer[srcIdx + 0];
                            pdata[i * 4 + 1] = filteredBuffer[srcIdx + 2];
                            pdata[i * 4 + 2] = filteredBuffer[srcIdx + 4];
                            pdata[i * 4 + 3] = 255;
                        }
                        break;

                    default:
                        break;
                }
            }
            else if (png.hdr.bitDepth < 8)
            {
                if (png.hdr.colorType == ColorType.Grayscale)
                {
                    const(size_t) srcPitch = (width * bitDepth + 7) / 8;
                    const(size_t) dstPitch = width * 4;

                    // Scaling multiplier to map luminance to 0..255
                    // 1 bit: 255 / 1  = 255 (0 -> 0, 1 -> 255)
                    // 2 bits: 255 / 3 = 85  (3 -> 255)
                    // 4 bits: 255 / 15 = 17 (15 -> 255)
                    const(ubyte) scale = cast(ubyte)(255 / ((1 << bitDepth) - 1));

                    for (size_t y = 0; y < height; y++)
                    {
                        size_t srcRowOffset = y * srcPitch;
                        size_t dstRowOffset = y * dstPitch;

                        for (size_t x = 0; x < width; x++)
                        {
                            size_t pixelsPerByte = 8 / bitDepth;
                            
                            size_t byteIdx = x / pixelsPerByte;
                            size_t pixelIdxInByte = x % pixelsPerByte;

                            ubyte rawByte = filteredBuffer[srcRowOffset + byteIdx];

                            ubyte mask = cast(ubyte)((1 << bitDepth) - 1);
                            size_t shift = 8 - bitDepth - (pixelIdxInByte * bitDepth);
                            
                            ubyte grayValue = cast(ubyte)((rawByte >> shift) & mask);
                            
                            ubyte g = cast(ubyte)(grayValue * scale);

                            size_t dstIdx = dstRowOffset + x * 4;
                            pdata[dstIdx + 0] = g;
                            pdata[dstIdx + 1] = g;
                            pdata[dstIdx + 2] = g;
                            pdata[dstIdx + 3] = 255;
                        }
                    }
                }
            }
        }
        else
        {
            if (bitDepth == 16)
            {
                logDebug("Converting from RGBA16 to RGBA8");
                
                for (size_t i = 0; i < numPixels; i++)
                {
                    size_t srcIdx = i * 8;
                    pdata[i * 4 + 0] = filteredBuffer[srcIdx + 0];
                    pdata[i * 4 + 1] = filteredBuffer[srcIdx + 2];
                    pdata[i * 4 + 2] = filteredBuffer[srcIdx + 4];
                    pdata[i * 4 + 3] = filteredBuffer[srcIdx + 6];
                }
            }
            else
            {
                // Copy RGBA8 as-is
                pdata[] = filteredBuffer[];
            }
        }
    }
    
    return suc();
}

/*
 * Performs the Paeth filter from pixels values:
 *   a = back
 *   b = up
 *   c = up and back
 */
ubyte paeth(ubyte a, ubyte b, ubyte c) @nogc nothrow pure
{
    int p = a + b - c;
    int pa = abs(p - a);
    int pb = abs(p - b);
    int pc = abs(p - c);
    if (pa <= pb && pa <= pc) return a;
    else if (pb <= pc) return b;
    else return c;
}

/// Applies filtering to the image data
bool filter(PNGImage* png, bool indexed, ubyte[] ibuffer, ubyte[] obuffer) @nogc nothrow
{
    uint width = png.hdr.width;
    uint height = png.hdr.height;
    uint channels = png.numChannels;

    uint bytesPerPixel = png.hdr.bitDepth / 8; // 1 for 8-bit, 2 for 16-bit

    uint scanlineSize;
    if (indexed)
        scanlineSize = (width * png.hdr.bitDepth) / 8 + 1;
    else
        scanlineSize = width * bytesPerPixel * channels + 1;

    ubyte pback, pup, pupback, cbyte;

    for (int i = 0; i < height; ++i)
    {
        pback = 0;

        // Get the first byte of a scanline
        ubyte scanFilter = ibuffer[i * scanlineSize];

        if (indexed)
        {
            width = scanlineSize - 1;
            for (int j = 0; j < width; ++j)
            {
                if (i == 0) pup = 0;
                else pup = obuffer[(i-1) * width + j];
                if (j == 0) pback = 0;
                else pback = obuffer[i * width + j-1];
                if (i == 0 || j == 0) pupback = 0;
                else pupback = obuffer[(i-1) * width + j-1];

                cbyte = ibuffer[i * scanlineSize + j+1];

                // Filter, then set the current byte in data
                switch (scanFilter)
                {
                    case FilterMethod.None:
                        obuffer[i * width + j] = cbyte;
                        break;
                    case FilterMethod.Sub:
                        obuffer[i * width + j] = cast(ubyte)(cbyte + pback);
                        break;
                    case FilterMethod.Up:
                        obuffer[i * width + j] = cast(ubyte)(cbyte + pup);
                        break;
                    case FilterMethod.Average:
                        obuffer[i * width + j] = cast(ubyte)(cbyte + (pback + pup) / 2);
                        break;
                    case FilterMethod.Paeth:
                        obuffer[i * width + j] = cast(ubyte)(cbyte + paeth(pback, pup, pupback));
                        break;
                    default:
                        return false;
                }
            }
        }
        else
        {
            for (int j = 0; j < width; ++j)
            {
                for (int k = 0; k < bytesPerPixel * channels; ++k)
                {
                    if (i == 0) pup = 0;
                    else pup = obuffer[((i-1) * width + j) * bytesPerPixel * channels + k];
                    if (j == 0) pback = 0;
                    else pback = obuffer[(i * width + j-1) * bytesPerPixel * channels + k];
                    if (i == 0 || j == 0) pupback = 0;
                    else pupback = obuffer[((i-1) * width + j-1) * bytesPerPixel * channels + k];

                    // Get the current byte from ibuffer
                    cbyte = ibuffer[i * (width * bytesPerPixel * channels + 1) + j * bytesPerPixel * channels + k + 1];

                    // Filter, then set the current byte in data
                    switch (scanFilter)
                    {
                        case FilterMethod.None:
                            obuffer[(i * width + j) * bytesPerPixel * channels + k] = cbyte;
                            break;
                        case FilterMethod.Sub:
                            obuffer[(i * width + j) * bytesPerPixel * channels + k] = cast(ubyte)(cbyte + pback);
                            break;
                        case FilterMethod.Up:
                            obuffer[(i * width + j) * bytesPerPixel * channels + k] = cast(ubyte)(cbyte + pup);
                            break;
                        case FilterMethod.Average:
                            obuffer[(i * width + j) * bytesPerPixel * channels + k] = cast(ubyte)(cbyte + (pback + pup) / 2);
                            break;
                        case FilterMethod.Paeth:
                            obuffer[(i * width + j) * bytesPerPixel * channels + k] = cast(ubyte)(cbyte + paeth(pback, pup, pupback));
                            break;
                        default:
                            return false;
                    }
                }
            }
        }
    }

    return true;
}

///
uint crc32(R)(R range, uint inCrc = 0) if (isInputRange!R)
{
    uint[256] generateTable()
    {
        uint[256] table;
        uint crc;
        for (int i = 0; i < 256; i++)
        {
            crc = i;
            for (int j = 0; j < 8; j++)
                crc = crc & 1 ? (crc >> 1) ^ 0xEDB88320UL : crc >> 1;
            table[i] = crc;
        }
        return table;
    }

    static const uint[256] table = generateTable();

    uint crc;

    crc = inCrc ^ 0xFFFFFFFF;
    foreach(v; range)
        crc = (crc >> 8) ^ table[(crc ^ v) & 0xFF];

    return (crc ^ 0xFFFFFFFF);
}
